future-architect/vuls

scan/redhat.go
sudo optoin is lacking when yum updateinfo --security update on rhel@aws
```
[Apr 10 18:35:34] ERROR [rhel:22] Failed to scan vulnerable packages
[Apr 10 18:35:34] ERROR [localhost] Failed to scan. err: ec2-user@52.192.199.226:22: Failed to yum updateinfo --security update. status: 1, stdout: Loaded plugins: amazon-id, rhui-lb, security
Repo rhui-REGION-client-config-server-6 forced skip_if_unavailable=True due to: /etc/pki/rhui/cdn.redhat.com-chain.crt
Repo rhui-REGION-client-config-server-6 forced skip_if_unavailable=True due to: /etc/pki/rhui/product/rhui-client-config-server-6.crt
Repo rhui-REGION-client-config-server-6 forced skip_if_unavailable=True due to: /etc/pki/rhui/rhui-client-config-server-6.key
Repo rhui-REGION-rhel-server-releases forced skip_if_unavailable=True due to: …
```
=> fix error while yum updateinfo --security update on rhel@aws

README.md, scan/sshutil.go
Updated readme to include chmod 600 on the authorized_keys file to force
the correct permissions.
=> Typo fix and updated readme

README.fr.md
Almost everything has been translated to french
=> Fr readme translation

commands/cmdutil.go, commands/discover.go, commands/prepare.go, commands/scan.go, config/jsonloader.go, config/loader.go, config/tomlloader.go, scan/redhat.go, scan/serverapi.go, scan/sshutil.go
- add -ask-sudo-password option (scan, prepare)
- add -ask-key-password option (scan, prepare)
- warning when plain password defined in config
- password masking in debug mode
- fix a bug while yum changelog
=> Fix no password in config

cveapi/cve_client.go, scan/redhat.go, scan/redhat_test.go
-  Fix Error while parsing yum check-update if the package not in rpm -qa 
-  Fix yum check-update --security to yum check-update 
- Stop debug logging while HTTP GET
=> Fix parse yum check update

commands/prepare.go, commands/scan.go, commands/tui.go, report/logrus.go, scan/sshutil.go, util/logutil.go
Note that windows suppoort are still having issue that gocui doesn't work correctly on windows.
=> Support Windows

scan/redhat.go
Default set  "Is this ok [y/N]:" is N.
=> Fix yes no infinite loop while doing yum update --changelog on root@CentOS #47

commands/scan.go
-cvss-over flag was not working because not set to config struct.
=> Fix -cvss-over flag #59

.gitignore, README.md, commands/scan.go, report/json.go, report/slack.go, report/stdout.go, report/textfile.go, report/tui.go, report/util.go
https://github.com/kotakanbe/go-cve-dictionary/pull/16
=> Add -report-text option, Fix small bug of report in japanese

setup/docker/README.ja.md, setup/docker/README.md
remove "$ cd $GOPATH/src/github.com/future-architect/vuls/setup/docker"
=> Remove unnecessary step in readme of docker setup

commands/configtest.go, commands/scan.go
=> wrong log packages

setup/docker/dockerfile/Dockerfile, setup/docker/dockerfile/scripts/scan_for_vulsrepo.sh
More fix #160.
Make sure vulsrepo on docker is available!
=> Fix: setup vulsrepo

README.ja.md, setup/docker/dockerfile/scripts/fetch_jvn_all.sh, setup/docker/dockerfile/scripts/fetch_jvn_last2y.sh, setup/docker/dockerfile/scripts/fetch_jvn_latest.sh
see https://github.com/kotakanbe/go-cve-dictionary/pull/21
The scripts are under setup/docker/dockerfile/scripts.
=> Change scripts for data fetching from jvn

scan/redhat.go
=> Fix parse Error for yum check-update #165

commands/history.go, commands/scan.go, commands/tui.go, config/config.go, report/json.go, report/tui.go, report/util.go, report/writer.go
-results-dir option of scan subcommand didn't work fine. 
I fixed the issue.
=> Fix -results-dir option of scan subcommand

setup/docker/README.ja.md, setup/docker/README.md
Update the paths referenced in the README to match the current project structure.
=> Fix path in setup/docker/README

scan/serverapi.go
https://github.com/future-architect/vuls/pull/183
=> Fix defer cache.DB.close

README.ja.md, README.md, report/mail.go
fix README because git v2 is not needed anymore.
and fix error messages.
=> fix readme

README.fr.md, README.ja.md, README.md, commands/prepare.go, commands/scan.go, scan/freebsd_test.go
I found some misspelling.  Please check these sentences.
=> fix some misspelling.

report/json.go
json-dir name was changed in #265 
I forgot to fix the dirname pattern...
=> Fix JSON-dir regex pattern #265

report/mail.go
=> Add date header to report mail.

README.ja.md, README.md, commands/configtest.go, commands/prepare.go, commands/report.go, commands/scan.go, config/config.go, scan/base_test.go, util/logutil.go
Log directory is currently hard-coded to `/var/log/vuls`.
I added option `-log-dir` to change log directory.
=> Add -log-dir option

commands/scan.go
Log of localhost was not output to file. #301
=> Fix a bug in logging (file output) at scan command

scan/redhat.go
=> Fix yum updateinfo options

scan/debian.go
=> Reduce privilege requirements for commands that don't need sudo on Ubuntu/Debian

commands/configtest.go, commands/scan.go
Small typo I noticed when testing vuls today.
=> Fix typo contianer -> container

commands/report.go
=> Don't check for a CVE DB when CVE Dictionary URL is defined

config/config.go, models/models.go, scan/base.go, scan/serverapi.go
=> Add image information for docker containers

README.ja.md, README.md, scan/freebsd.go
=> Change the command used for os detection from uname to freebsd-version

commands/util.go, glide.lock, models/models.go, scan/base.go
=> Avoid null slice being null in JSON

README.ja.md
Improve kanji character in README.ja.md
=> Improve kanji character

README.ja.md, README.md, report/util.go
=> Fix candidate to confidence.

README.ja.md, README.md, scan/redhat.go
Closes #375 
***Is this ready for review?:*** Yes 
***Is it a breaking change?:*** Yes
=> Obsolete CentOS5 support

README.ja.md
Correct Japanese postpositional particle
=> Fix Japanese typo

README.ja.md, README.md, commands/report.go, commands/tui.go, commands/util.go, config/config.go, cveapi/cve_client.go, models/models.go
I fixed that vuls did not report when MySQL backend was specified.
=> Fix Bug of Mysql Backend

README.ja.md, README.md, commands/report.go, commands/util.go, commands/util_test.go, config/config.go, report/localfile.go
Closes https://github.com/future-architect/vuls/issues/255
Compare differences from previous results
- Search the old directories if result does not exist in the previous directory
```
$ vuls report -diff
```
=> Notify the difference from the previous scan result

README.ja.md
fix typo
README.ja.md
please see README.ja.md
=> fix typo in README.ja.md

setup/docker/README.md
Duplicate
https://github.com/future-architect/vuls/blob/af5a1204bc42cd87312ff022597aeb1f28722840/setup/docker/README.md#step3-configtest
=> Remove duplicate command in README

README.ja.md
typo miss README.ja.md
typo miss README.ja.md
see commit diff
=> typo README.js.md

models/scanresults.go
=> add serveruuid field

report/report.go
export FillWithOval method.
change method name from fillWithOval to FillWithOval
=> export FillWithOval

report/report.go
export fillCveInfo
change fillCveInfo into FillCveInfo
=> export fill cve info

setup/docker/README.md, setup/docker/vulsrepo/latest/Dockerfile, setup/docker/vulsrepo/latest/README.md
Changed to use vulsrepo-server
Change docker file
docker run -dt -v $PWD:/vuls -p 5111:5111 vuls/vulsrepo
=> use_vulsrepo-server

config/config.go, report/report.go
add windows type
add windows type
=> add windows type

commands/discover.go
=> Fix ping option of discover subcommand #471

README.ja.md, README.md, commands/report.go
Closes #475 
Fix 
- command/report.go
- README.md
=> Fix a arg of report subcommand

README.ja.md, README.md, models/packages.go, scan/redhat.go, scan/redhat_test.go
Issues `yum ps` to detect processed affected by next update on RedHat, CentOS, Amazon , Oracle.
`AffectedProcs` key under Packages will be added by this P/R.
```
{
"Packages" : {
"wpa_supplicant": {
"Name": "wpa_supplicant",
"Version": "1:2.0",
"Release": "17.el7_1",
"NewVersion": "1:2.0",
"NewRelease": "21.el7_3",
"Arch": "x86_64",
"Repository": "updates",
"Changelog": {
"Contents": "* Tue Aug  9 21:00:00 2016 Davide Caratti <dcaratti@redhat.com> - 1:2.0-21\n- fix wpa_supplicant.sysconfig to avoid duplicate -u and -f arguments (rh #1351388)\n\n* Mon Mar 21 21:00:00 2016 Lubomir Rintel <lrintel@redhat.com> - 1:2.0-20\n- D-Bus: Don't do <deny send_interface=\"...\" /> in dbus service file (rh #1319796)\n\n* Mon Jan 11 21:00:00 2016 Lubomir Rintel <lrintel@redhat.com> - 1:2.0-19\n- n …
```
=> Detect processes affected by update using yum-ps	

README.ja.md, README.md
I was modified spell miss of README.md
I checked spell miss using Atom Editor. And commited using IntelliJ IDEA.
Sorry, unnecessary differences came out, so I reverted once.
Please check diff of file.
Best Regards,
Yasuyuki Sato.
=> Modified Spell Miss of "README.md".

config/jsonloader.go
Fix typo in `config/jsonloader.go` .
Fix typo.
Read diff.
***Is this ready for review?:*** yes  
***Is it a breaking change?:*** no
=> Fix typo in config/jsonloader.go

report/util.go
Just fixed typo in console messages.
=> Fix typo Privious -> Previous

config/tomlloader.go
Bug of #531 
```
[Nov  6 09:42:01] ERROR [localhost] Error loading /Users/kotakanbe/go/src/github.com/future-architect/vuls/config.toml, amaama is invalid. User is empty
[Nov  6 09:42:01] ERROR [localhost] If you update Vuls and get this error, there may be incompatible changes in config.toml
[Nov  6 09:42:01] ERROR [localhost] Please check README: https://github.com/future-architect/vuls#configuration
```
=> Fix config.toml validation

README.ja.md, README.md
=> README Typo Update

README.ja.md, README.md, oval/alpine.go
Bug fix of #194 
Remove empty CveContent output to JSON with Alpine Linux scan
see diff
scan, reprot and then see json
=> Remove empty CveContent output to JSON with Alpine Linux scan

oval/redhat.go
=> Add more kernel related packages (Fix #541) #549

README.ja.md, README.md, scan/redhat.go, scan/redhat_test.go
=> RHEL's Fast Scan no longer required internet connection and root privilege

scan/redhat.go
Closes #560 
see diff
scan amazon linux2
=> Support Amazon Linux2

oval/redhat.go
Super simple typo fix in a comment.
=> Fixed Typo

Gopkg.lock, Gopkg.toml, commands/report.go, config/config.go, config/config_test.go, config/tomlloader.go, report/syslog.go, report/syslog_test.go, scan/freebsd.go
Support a reporting via Syslog
Use `log/syslog`
https://golang.org/pkg/log/syslog/
```
$ nc -l 5140
```
```
...
[syslog]
protocol = "tcp"
port = "5140"
tag = "vuls"
```
=> Support a reporting via Syslog

config/config.go
Closes #608 
remove a validation of hipchat
vuls report -to-hipchat
=> fix: remove a validation of hipchat

commands/report.go, config/config.go, config/config_test.go
Fix validations for reporting.
see diff
- edit config
- ./vuls report
=> fix: validation on reporting

report/slack.go
Closes #611
see the diff
vuls report -to-slack and check whether a packcage information is displayed.
=> feat: Display pkg information to slack notification #611

report/util.go, report/util_test.go
In the diff option, also let us know that the package was newly released,
test
=> inform new release on diff option

models/vulninfos.go
The score on the TUI list is incorrect.
=> Fix maxCvssScore

Gopkg.lock, models/packages.go, scan/debian.go, scan/debian_test.go, scan/redhat.go, scan/redhat_test.go
Execute `checkrestart` on postScan when scanning Debian, Ubuntu
scan with -deep option
***Is it a breaking change?:*** Yes
=> feat: checkrestart for Ubuntu and Debian

scan/redhat.go
Fix the following errors on RHEL 5
```
[Unknown format: Loading "rhnplugin" plugin, fields: [Loading "rhnplugin" plugin]] 
```
```
Command line error: no such option: --color
```
- Skip "Loading" line
- Check whether `yum` has `--color` option by `yum --help | grep color`
Scan RHEL 5
=> [WIP] fix(scan): fix RHEL 5

Gopkg.lock, Gopkg.toml, cache/bolt.go, commands/report.go, commands/tui.go, config/config.go, models/cvecontents.go, models/cvecontents_test.go, models/scanresults.go, models/scanresults_test.go, models/utils.go, models/vulninfos.go, models/vulninfos_test.go, oval/debian.go, oval/redhat.go, oval/redhat_test.go, report/cve_client.go, report/db_client.go, report/localfile.go, report/report.go, report/slack.go, report/syslog.go, report/syslog_test.go, report/tui.go, report/util.go, report/util_test.go, scan/serverapi.go, util/logutil.go
Closes #XXXXX
Support NVD-JSON
https://github.com/kotakanbe/go-cve-dictionary/pull/75
=> Support NVD JSON and CVSS3 of JVN

commands/report.go, config/config.go, config/tomlloader.go, report/chatwork.go, report/chatwork_test.go
Closes #XXXXX
- [✓ ] Write tests
- [✓ ] Write documentation
- [✓] Check that there aren't other open pull requests for the same issue/feature
- [✓] Format your source code by `make fmt`
- [✓] Pass the test by `make test`
- [✓] Provide verification config / commands
- [✓] Enable "Allow edits from maintainers" for this PR
- [✓] Update the messages below
**・document**
https://github.com/vulsdoc/vuls/pull/26
**・test report done**
=> Chatwork support

report/hipchat.go
=> refactoring : hipchat

report/stride.go
- use fmt.Sprintf
- use serverInfo
- indent
only view code!
I actually tested it.
=> Refactor stride

config/config.go, models/vulninfos.go, report/chatwork.go, report/stride.go
Show CVSS severity on TUI for Ubuntu
./vuls tui
=> fix(tui): show CVSS severity on TUI for Ubuntu

scan/debian.go
The policy of fast scan mode is below.
- no root
- no deps
But the current implementation, `reboot-notifier` is required on Debian.
Installation of the reboot-required package is optional. If it is not installed, display warning at configtest.
see diff 
- Uninstall reboot-notifier on scan target server(Debian)
- configtest
```
$ go build ;and ./vuls configtest deb7 
[May 21 14:29:08]  INFO [localhost] Validating config...
[May 21 14:29:08]  INFO [localhost] Detecting Server/Container OS...
[May 21 14:29:08]  INFO [localhost] Detecting OS of servers...
[May 21 14:29:08]  INFO [localhost] (1/1) Detected: deb7: debian 7.11
[May 21 14:29:08]  INFO [localhost] Detecting OS of containers...
[May 21 14:29:08]  INFO [localhost] Checking dependencies...
[May 21 14:29:08]  WARN [deb7] …
```
=> fix(configtest): Only warning when reboot-notifier is not installed on Debian

models/packages.go, models/packages_test.go, oval/alpine.go, oval/debian.go, oval/redhat.go, oval/suse.go, oval/util.go, oval/util_test.go
=> Fix(reporting): NotFixedYet of SourcePackage in OVAL match on Debian and Ubuntu

scan/suse.go, scan/suse_test.go
=> refactor(suse): add testcase for detectSUSE

.travis.yml, Gopkg.lock, Gopkg.toml, oval/oval.go, oval/util.go
Closes #679
update deps
./vuls report
***Is it a breaking change?:*** No
=> fix(report): record not found on reporting with OVAL #679

Gopkg.lock, commands/report.go, config/config.go, config/tomlloader.go, report/report.go, report/saas.go
add `-to-saas` option in report
=> add(report) add -to-saas option

report/util.go
table.SetHeaderColor does not need in case of formatFullPlainText().
=> remove table.SetHeaderColor codes

Gopkg.lock, config/config.go, report/syslog.go
replace syslog pkg
`log/syslog` 
Since `log / syslog` can not be used in windows environment, it changed to `github.com/RackSec/srslog`
=> change syslog pkg

config/tomlloader.go
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>
=> config: remove commented-out code from tomlloader

models/packages.go, report/tui.go, report/util.go
Show the repository of affected pkgs in TUI, -format-full-text
=> feat(report): show repository of affected pkgs

Gopkg.lock, Gopkg.toml, gost/gost.go, gost/microsoft.go, models/cvecontents.go
=> add ms gost

models/scanresults.go, scan/base.go
I entered the value of scanMode in the scan result json.
If you look inside config, scanMode was added, but it was difficult to understand, so I added it.
=> add scan mode

gost/redhat.go
check VulnInfo.CveContent is nil before set
Fixes #728 
***Is this ready for review?:*** YE
=> fix(report): nil pointer in deep scan mode #728

Gopkg.lock, exploit/exploit.go, models/vulninfos.go
=> fix exploit db

gost/debian.go, gost/microsoft.go
fix new cve contents (windows, debian)
related to https://github.com/future-architect/vuls/pull/725
=> fix(report): nil pointer on reporting for Debian

models/scanresults.go, models/vulninfos.go, report/tui.go, report/util.go
format-list
tui summary view
fix(report): Display CVEs detected by CPEs with -ignore-unfixed flag
related #740 
=> feat(report): Display CERT information to reports

exploit/exploit.go
export convertToModels in exploit
=> export exploit func

Gopkg.lock
update pkg to incorporate the latest gost https://github.com/knqyf263/gost/pull/18
=> fix(gost) update pkg to incorporate the latest gost

alert/alert_jp.go, models/vulninfos.go, report/report.go
add X-CERT data convert to json.
run `vuls scan` and `vuls report`, then check `results/current/xxxx.json`
=> add alert data to result json

scan/serverapi.go
Re-SSH when the first connection of SSH stalled.
Fixes #699 
=> fix(scan): OS detection ssh timeout in first run #699

Gopkg.lock, exploit/exploit.go, models/vulninfos.go
Reflected bug fix for go-exploitdb
https://github.com/mozqnet/go-exploitdb/pull/15
=> Reflected bug fix for go-exploitdb

Gopkg.lock
https://github.com/kotakanbe/goval-dictionary/pull/56
Fixes https://github.com/kotakanbe/goval-dictionary/pull/56
=> fix(oracle): vuls report returns different result each time in the case of Oracle Linux

report/email.go
=> add(report) -format-list option to -to-email

commands/discover.go, commands/report.go, config/config.go, config/tomlloader.go, report/telegram.go, report/telegram_test.go
=> Add Telegram support

report/report.go, report/util.go
Fixes #751 
Scan for Amazon, CentOS
=> fix(report): detect 0 vulns for Amazon, FreeBSD, Raspbian

README.md
=> feat(README): contiruters shield

report/report.go
change implemention of integration
=> change implemention of integration

report/saas.go, scan/serverapi.go, util/util.go
add scanner info in `-to-saas`
=> add scanner info in -to-saas

scan/suse.go, scan/suse_test.go
Fix https://github.com/future-architect/vuls/issues/515#issuecomment-470621281
`make test` 
=> fix(scan): parse error on SUSE #515

Gopkg.lock, Gopkg.toml
see https://github.com/future-architect/vuls/issues/789
=> fix(report): cpe match bug: go-cve-dictionary#120

report/slack.go, scan/serverapi.go
Fixes #776
`./vuls report -to-slack -format-one-line-text`
=> feat(slack): enable -format-one-line-text with -to-slack

Gopkg.lock
update go-cve-dictionary
https://github.com/kotakanbe/go-cve-dictionary/pull/125
=> update cve dictionary

commands/configtest.go, commands/report.go, commands/scan.go, commands/server.go, commands/tui.go, github/github.go, models/scanresults.go, report/db_client.go, report/report.go, report/saas.go, report/tui.go, report/util.go, scan/executil.go, scan/serverapi.go, server/server.go
Return error when GitHub Integration failed such as wrong token, URL
- tried valid token ... no err
- tried invalid token ... error occurred
=> fix(report): Error when GitHub integration failed

commands/report.go
Exit 1 when scan result has errors in reporting
=> fix(report): exit 1 when scan result has errors

Gopkg.lock, models/scanresults.go, scan/base.go, scan/executil.go, scan/serverapi.go
add a key of scannedVia in scanResult struct
=> add scannedVia field to know the way of access such as SSH, local or pseudo

errof/errof.go, github/github.go
Implement Vuls's own error code
=> Implement Vuls's own error code

models/scanresults.go, models/vulninfos.go, wordpress/wordpress.go
The number of fixed/total count was wrong.
./vuls report
=> fix(report): fix the number of fixed/total in reporting

oval/debian.go
The kernel related keys in OVAL has been changed for Ubuntu 16.
This cause the false negative of kernel vulns on Ubuntu 16.
30 CVE-IDs related to the kernel increased.
```
$ cat ~/work/ubuntu-kernel-bug/u16/localhost.json | jq ".scannedCves |length"
244
$…  cat results/current/localhost.json | jq ".scannedCves |length"                                                             Thu May 23 22:31:17 2019
274
```
Newly detected CVE-IDs(Ubuntu 16)
```
~/g/s/g/f/vuls   *$…  diff /tmp/keys.old /tmp/keys.new                                                                                   14.2m  Thu May 23 22:29:57 2019
104a105,106
>   "CVE-2017-18241",
>   "CVE-2017-18249",
168a171
>   "CVE-2018-1120",
169a173,175
>   "CVE-2018-12126",
> …
```
=> [WIP]fix(scan): false negative of kernel related vulns on Ubuntu 16

oval/debian.go
=> fix(report): warning only if the kernel version is unknown

README.md
=> fix typos, extraneous text in README.md

scan/amazon.go, scan/centos.go, scan/oracle.go, scan/redhatbase.go, scan/rhel.go
In order to refresh a metadata in `fast-root` and `deep` scan mode.
see also https://github.com/vulsdoc/vuls/commit/8fb79a4fbfb1edf1e4d6740e01d4c14acb96edb0
=> fix(scan): exec `yum makecache` to update metadata on RedHat based linux

scan/redhatbase.go
In order to fetch changelogs for only updatable pkg.
=> fix(scan): fetch only updatable package changelogs

models/scanresults.go
=> fix(report): remove extra check logic #802

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
Use multi ISSUE_TEMPLATE
https://github.com/goodwithtech/dockle/issues/new/choose
=> enhance issue_template

commands/scan.go, config/config.go, config/ips.go, models/scanresults.go, scan/base.go, scan/serverapi.go
=> retrieve ips(deep security) identifiers

GNUmakefile, models/packages.go, report/tui.go, report/util.go, scan/amazon.go, scan/base.go, scan/base_test.go, scan/centos.go, scan/debian.go, scan/redhatbase.go, scan/rhel.go, scan/utils.go
Execute `lsof` on the scan target server to get Listen ports.
Then check which package ports belongs to.
```
$ sudo lsof -P -i | grep LISTEN
rpcbind    1626      rpc    8u  IPv4  10115      0t0  TCP *:111 (LISTEN)
rpcbind    1626      rpc   11u  IPv6  10118      0t0  TCP *:111 (LISTEN)
rpc.statd  1647  rpcuser    9u  IPv4   9049      0t0  TCP *:40957 (LISTEN)
rpc.statd  1647  rpcuser   11u  IPv6   9053      0t0  TCP *:58927 (LISTEN)
sshd       1805     root    3u  IPv4  10333      0t0  TCP *:22 (LISTEN)
sshd       1805     root    4u  IPv6  10335      0t0  TCP *:22 (LISTEN)
sendmail   1835     root    4u  IPv4  10366      0t0  TCP localhost:25 (LISTEN)
```
Please describe the tests that you ran to verify your changes. Provide instructions so we …
=> feat(scan): Display listen port of affected procs for each vulnerable pkgs

scan/amazon.go
yum-plugin-ps no need anymore.
https://github.com/future-architect/vuls/pull/855
=> fix(configtest): remove yum-plugin-ps check on Amazon Linux

scan/alpine.go
Add the ability to scan Alpine with Offline mode
Ran vuls on an alpine docker with no network
=> Allow Offline scanning on Alpine

config/config.go, go.mod, models/library.go, models/packages.go, oval/util.go, report/slack.go, scan/base_test.go, scan/container.go
To be able to scan `amazonlinux` image.
```
[servers.image]
type="pseudo"
[servers.image.images.amazon2]
name="amazonlinux"
tag="2"
[servers.image.images.amazon1]
name="amazonlinux"
tag="1"
```
=> for Amazon Linux image

report/report.go
change key ja to jp in alertDict.ja.team
./vuls report and check result json
=> fix(report): fix cert key in result json ja to jp

config/config.go, util/logutil.go
fix(log): add .log extension to vuls logfile
=> fix(log): add .log extension to vuls logfile

gost/base.go, gost/redhat.go
=> fix cve judgment

scan/alpine.go, scan/base.go, scan/debian.go, scan/debian_test.go
Warning if unable to get IP address on the scan target server. (Debug log In the current implementation)
Fix a test case bug.
=> Warn no ip

go.mod, go.sum, scan/container.go
Updated fanal to use aws session token
=> Feature: Updated fanal to use aws session token

scan/centos.go, scan/rhel.go
refs #947 
confittest on RHEL8, CentOS8
=> fix(configtest): yum-utils instead of dnf-utils on RHEL8, Cent8

go.mod, go.sum
Fixes #949 
```
$ su - unko
$ ./vuls report
EROR[04-27|17:28:09] Failed to create a log file              err="open /var/log/vuls/cve-dictionary.log: permission denied"
2020/04/27 17:28:09 failed to open logfile: /var/log/vuls/localhost.log open /var/log/vuls/localhost.log: permission denied
Failed to fire hook: open /var/log/vuls/localhost.log: permission denied
[Apr 27 17:28:09]  INFO [localhost] Validating config...
2020/04/27 17:28:09 failed to open logfile: /var/log/vuls/localhost.log open /var/log/vuls/localhost.log: permission denied
Failed to fire hook: open /var/log/vuls/localhost.log: permission denied
[Apr 27 17:28:09]  INFO [localhost] Loaded: /home/ubuntu/go/src/github.com/future-architect/vuls/results/2020-04-27T15:48:47+09:00
2020/04/27 17:28:09 failed to open logfile: …
```
=> fix(logging): panic if no write permission #949

go.mod, go.sum, report/report.go, report/report_test.go
=> fix(uuid): change uuid lib to go-uuid #929

scan/serverapi.go
=> fix : suspicious append call without element argument 

.goreleaser.yml, contrib/future-vuls/cmd/main.go, contrib/trivy/cmd/main.go
=> Fix releaser

report/util.go
I added the information because the vulnerability was detected and displayed as if there was no vulnerability when there was no difference.
=> add diff-mode info

contrib/trivy/parser/parser.go, contrib/trivy/parser/parser_test.go
=> fix trivy parser test

go.mod, go.sum
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f02dc112448]
```
=> fix(report): fix segfault while uploading to s3

scan/base.go
feat(libscan): enable to scan vulns of libs with pseudo #1035
Fixes #1035
test with this config.toml
```
[servers.localgem]
lockfiles = [
"/home/ubuntu/work/redmine/gem1/Gemfile.lock"
]
```
=> feat(libscan): enable to scan vulns of libs with pseudo #1035

models/scanresults.go, models/scanresults_test.go, report/stdout.go, scan/freebsd.go, scan/freebsd_test.go
Fixes #1042
./vuls scan freebsd
=> fix(scan-freebsd): also get installed with `pkg info` #1042

commands/report.go, config/config.go, config/tomlloader.go, models/scanresults.go, report/localfile.go, report/report.go
I added `IgnoredJSONKeys` to config.toml.
For example, the value of the key specified will be removed from the JSON file at the reporting time.
You can define this per server in config.toml. 
If you want to specify them all at once, you can define the default section.
```
[servers.localgem]
lockfiles = [
"/home/ubuntu/work/redmine/gem1/Gemfile.lock"
]
ignoredJSONKeys = [
"scannedIpv4Addrs",
]
```
Define keys in config.toml and reporting, then check the specified key removed.
=> feat(report): IgnoredJSONKyes to clear values in result json

.gitignore, cmd/vuls/main.go
=> fix a compile error #1083

config/config.go, libmanager/libManager.go, oval/debian.go, oval/util.go, oval/util_test.go, report/db_client.go, report/report.go, report/util.go, server/server.go
It was dirty, so I'll refactor it.
=> refactor(report): around FillCveInfo

models/cvecontents.go, models/utils.go, models/vulninfos.go, report/report.go, report/tui.go
```
✗  ubuntu@dev  ~│g│s│g│f│vuls  ⎇ master~  diff localgem.json results/current/localgem.json
25c25
<     "reportedAt": "2020-12-15T15:40:37.01606951+09:00",
---
>     "reportedAt": "2020-12-16T06:51:38.287200022+09:00",
27c27
<     "reportedRevision": "build-20201215_153140_47e42ce",
---
>     "reportedRevision": "build-20201216_064222_d576b6c",
7920a7921,7928
>             "exploits": [
>                 {
>                     "exploitType": "NVD",
>                     "id": "",
>                     "url": "https://hackerone.com/reports/413388",
>                     "description": ""
>                 }
>             ],
8070a8079,8086
>             "exploits": [
>                 {
>                     "exploitType": "NVD",
> …
```
=> feat(report): add exploit link in NVD as a source

models/cvecontents.go, models/cvecontents_test.go, models/scanresults_test.go, models/vulninfos.go, models/vulninfos_test.go, report/syslog.go, report/syslog_test.go, report/util.go, report/util_test.go
refactor(nvdxml): Remove codes related to NVD xml(deprecated)
make test passed
=> refactor(nvdxml): Remove codes related to NVD xml(deprecated)

config/config.go, config/tomlloader.go
remove a deprecated option.
***Is this ready for review?:***  YES
=> refactor(config): remove DependencyCheckXMLPath in config.toml

config/config.go, report/report.go, subcmds/configtest.go, subcmds/saas.go, subcmds/scan.go, wordpress/wordpress.go, wordpress/wordpress_test.go
=> refactor(report): remove Integration.apply

scan/redhatbase.go
- supports CentOS Stream
- vuls scan output Failed to parse CentOS in case of CentOS Stream.
=> fix(scan): Failed to parse CentOS Stream

models/utils.go
Fixed not to split empty string
=> fix(cvecontent) Fixed not to split empty string

config/config.go, report/azureblob.go, report/localfile.go, report/s3.go, scan/freebsd.go, subcmds/report.go
Fixes #1068 
./vlus report -format-xml
=> fix(xml): remove -format-xml #1068

scan/redhatbase.go
vuls issues the following command to get the `dnf module list` as a non-root user.
`dnf --assumeyes --cacheonly --color=never --quiet module list --enabled`
However, depending on the environment, vuls may get a gpg key import error.
This command will not update the cache.
I think there is no problem with the workaround of giving the --nogpgcheck option to avoid the error.
https://github.com/future-architect/vuls/pull/1136/files#diff-4042a5edc6fe46227e20dba912398f4672538ca75cbb5b4d78d9b98388998d3aR706
If you have a better solution, please let me know.
Relevant information on the Internet
- https://github.com/geerlingguy/ansible-role-kubernetes/issues/67
- https://bugzilla.redhat.com/show_bug.cgi?id=1768206
- https://bugzilla.redhat.com/show_bug.cgi?id=1350930
- …
=> fix(scan): add --nogpgcheck to dnf mod list to avoid `Error: Cache-only enabled but no cache for *`

models/scanresults.go, models/scanresults_test.go, models/vulninfos.go, models/vulninfos_test.go, report/slack.go, report/syslog.go, report/syslog_test.go, report/tui.go, report/util.go
=> feat(report): range notion calculated by severity when no-cvss-score

errof/errof.go, wordpress/wordpress.go
=> feat(wordpress): define API limit exceed error for wpscan.com

scan/redhatbase.go
// rpm exit code means `the number` of errors.
// https://listman.redhat.com/archives/rpm-list/2005-July/msg00071.html
// If we treat non-zero exit codes of `rpm` as errors,
// we will be missing a partial package list we can get.
For example, in the following cases, the affected process will be missing partially.
```
time="Feb  9 06:07:34" level=debug msg="Failed to parse rpm -qf line: file /run/log/journal/3d5c05376530a2eb49e3e90576f83c5b/system.journal is not owned by any package, r: execResult: servername: \n  cmd: rpm -qf --queryformat \"%{NAME} %{EPOCHNUM} %{VERSION} %{RELEASE} %{ARCH}\\n\" /usr/lib/systemd/systemd-journald /run/log/journal/3d5c05376530a2eb49e3e90576f83c5b/system.journal /run/systemd/journal/kernel-seqnum /usr/lib64/ld-2.17.so /usr/lib64/libacl.so.1.1.0 …
```
=> fix(scan): ignore `rpm -qf` exit status

gost/microsoft.go, models/vulninfos.go
add workaround into mitigation
=> fix(gost/microsoft) add workaround into mitigation

scan/base.go, scan/debian.go, scan/redhatbase.go, scan/redhatbase_test.go
The Red Hat family allows different architectures and different versions of the same package to live together.
However, in the current implementation, the following warning may occur in this case.
```
[Feb 11 06:34:22]  WARN [c7] Failed to FindByFQPN: Failed to find the package: libgcc-4.8.5-39.el7:
github.com/future-architect/vuls/models.Packages.FindByFQPN
```
```
[root@ip-192-168-0-154 ~]# curl -OL http://mirror.centos.org/centos/7/os/x86_64/Packages/libgcc-4.8.5-44.el7.i686.rpm
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  110k  100  110k    0     0  55347      0  0:00:02  0:00:02 --:--:-- 55372
[root@ip-192-168-0-154 ~]# rpm -ivh libgcc-4.8.5-44.el7.i686.rpm
Preparing... …
```
=> fix(scan): yum ps warning for Red Hat family

.github/workflows/goreleaser.yml, .github/workflows/test.yml, .github/workflows/tidy.yml, go.mod, go.sum
https://github.com/kotakanbe/goval-dictionary/pull/122
=> fix(ubuntu): Fix deferred packages not showing as affected

subcmds/scan.go
Fixes #1184 
```
ubuntu@dev  ~│g│s│g│f│vuls  ⎇ fix-scan-arg~  cat config.toml
[servers]
port = "local"
ubuntu@dev  ~│g│s│g│f│vuls  ⎇ fix-scan-arg~  ./vuls scan 
[Mar  3 12:20:02] ERROR Failed to create log file. path: /var/log/vuls/localhost.log, err: open /var/log/vuls/localhost.log: permission denied
[Mar  3 12:20:02]  INFO [localhost] vuls-v0.15.9-build-20210303_120012_1d0c5de
[Mar  3 12:20:02]  INFO [localhost] Start scanning
[Mar  3 12:20:02]  INFO [localhost] config: /home/ubuntu/go/src/github.com/future-architect/vuls/config.toml
[Mar  3 12:20:02]  INFO [localhost] Validating config...
[Mar  3 12:20:02]  INFO [localhost] Detecting Server/Container OS... 
[Mar  3 12:20:02]  INFO [localhost] Detecting OS of servers... 
[Mar  3 12:20:02]  INFO …
```
=> fix(scan): scan all servers in the config if no args #1184

subcmds/configtest.go, subcmds/scan.go
=> fix(configtest): all servers in the config if no args #1184

scanner/serverapi.go
Export function of creating scan result from pkg list 
=> feat(scanner) export pkg list scan method

config/os.go, config/os_test.go
add to support Ubuntu 20.10
```
% make test
--- PASS: TestEOL_IsStandardSupportEnded/Ubuntu_20.10_supported (0.00s)
```
```
% vuls report
example (ubuntu20.10)
=========================================
Total: 0 (Critical:0 High:0 Medium:0 Low:0 ?:0)
0/0 Fixed, 0 poc, 0 exploits, en: 0, ja: 0 alerts
776 installed
Warning: Some warnings occurred.
[Standard OS support will be end in 3 months. EOL date: 2021-07-01]
No CVE-IDs are found in updatable packages.
776 installed
```
=> fix(config): add Ubuntu 20.10

detector/detector.go, gost/gost.go
Fixes #1217 
Tested this P/R using the method described in the issue and confirmed that the number did not increase.
=> fix(gost): close gost DB connection in server mode #1217

subcmds/discover.go
Confit template is displayed when `vuls discover 172.0.0.1/32` becouse of #1224 
```bash
$ go run cmd/vuls/main.go discover 127.0.0.1/32
[Apr 28 14:19:41]  INFO [localhost] vuls-`make build` or `make install` will show the version-
[cveDict]
#type = ["sqlite3", "mysql", "postgres", "redis", "http" ]
#sqlite3Path = "/path/to/cve.sqlite3"
#url        = ""
[ovalDict]
#type = ["sqlite3", "mysql", "postgres", "redis", "http" ]
#sqlite3Path = "/path/to/oval.sqlite3"
#url        = ""
[gost]
#type = ["sqlite3", "mysql", "postgres", "redis", "http" ]
#sqlite3Path = "/path/to/gost.sqlite3"
#url        = ""
[exploit]
#type = ["sqlite3", "mysql", "postgres", "redis", "http" ]
#sqlite3Path = "/path/to/go-exploitdb.sqlite3"
#url        = ""
[metasploit] …
```
=> refactor(git-conf): config template in github section changed

models/vulninfos.go
Fixes #1233 
45 + 77 + 78 + 8 + 4 = 212
=> fix(report): include the num of criticals in total #1233

.gitignore, integration/data/results/amazon_2.json, integration/data/results/centos_7.json, integration/data/results/debian_10.json, integration/data/results/oracle.json, integration/data/results/rails.json, integration/data/results/rhel_71.json, integration/data/results/rhel_8.json, integration/data/results/ubuntu_1804.json, integration/data/results/ubuntu_2004.json
https://github.com/future-architect/vuls/blob/master/GNUmakefile#L94
=> chore: add test data for integration test

gost/gost.go
Fixes [issue#1263](https://github.com/future-architect/vuls/issues/1263)
Tested by following steps to reproduce detailed on issue, posting package list to Vuls in local server mode using `OS-Family: ubuntu`.
=> fix(gost): Use DBDriver ctx in Psuedo

Dockerfile, logging/logutil.go
Fix the following error.
```
$ docker build .
...
go: downloading github.com/Azure/go-autorest/autorest/date v0.2.0
logging/logutil.go:103:13: undefined: io.Discard
note: module requires Go 1.16
make: *** [GNUmakefile:36: install] Error 2
```
I confirmed that I can docker build on my local pc.
=> fix(docker): docker build error

models/library.go
https://vuls.io/docs/en/usage-scan-non-os-packages.html#library-vulns-scan
=> chore: update find-lock file type

detector/cve_client.go, go.mod, go.sum
Refs https://github.com/vulsio/go-cve-dictionary/pull/224
=> feat(go-cve): add error handling

go.mod, go.sum
Refs https://github.com/vulsio/go-exploitdb/pull/64
=> refactor(exploitdb): use pipeline effectively

models/vulninfos.go
=> style: fix lint

scanner/base.go
=> fix(scanner/base) export libFile fields

README.md, go.mod, go.sum, reporter/util.go, tui/tui.go
The module is updated because a new data source has been added to go-exploitdb.
https://github.com/vulsio/go-exploitdb/pull/78
```console
$ go-exploitdb fetch inthewild
$ vuls scan && vuls report
$ grep '"exploitType": "InTheWild",' results/current/localhost.json | wc -l
237
```
=> chore(mod): update go-exploitdb module

GNUmakefile, go.mod, go.sum
update trivy v0.27.1 .
```console
$ make diff
...
diff -c ''/home/mainek00n/github/github.com/MaineK00n/vuls/integration/results'/2022-04-27T15:26:04+09:00' ''/home/mainek00n/github/github.com/MaineK00n/vuls/integration/results'/2022-04-27T15:26:05+09:00'
echo "old: ''/home/mainek00n/github/github.com/MaineK00n/vuls/integration/results'/2022-04-27T15:26:04+09:00' , new: ''/home/mainek00n/github/github.com/MaineK00n/vuls/integration/results'/2022-04-27T15:26:05+09:00'"
old: ''/home/mainek00n/github/github.com/MaineK00n/vuls/integration/results'/2022-04-27T15:26:04+09:00' , new: ''/home/mainek00n/github/github.com/MaineK00n/vuls/integration/results'/2022-04-27T15:26:05+09:00'
for jsonfile in ''/home/mainek00n/github/github.com/MaineK00n/vuls/integration/results'/2022-04-27T15:26:04+09:00'/*. …
```
=> chore(deps): update trivy v0.27.1

models/library.go
feat(library) output library type when err
=> feat(library) output library type when err

contrib/future-vuls/cmd/main.go
- Enabled to specify an environment variable called VULS_TAGS to include the server tag in json uploaded to futureVuls.
=> add VULS_TAGS env into contirib/future-vuls

contrib/future-vuls/cmd/main.go
=> fix(contriv/fvuls) initialize optional map

contrib/trivy/parser/v2/parser.go, contrib/trivy/parser/v2/parser_test.go
fill image info into scan results
=> feat(contrib/trivy) fill image info into scan results

saas/saas.go
add optional of VULS_TAGS from env
```
VULS_TAGS="aaa,ffff" go run cmd/scanner/main.go saas
{
"jsonVersion": 4,
"lang": "",
"serverUUID": "7e2885d7-35de-19ec-60ce-eb371a2b49e8",
"serverName": "forti",
"family": "pseudo",
"release": "",
"container": {
"containerID": "",
"name": "",
"image": "",
"type": "",
"uuid": ""
},
"platform": {
"name": "other",
"instanceID": ""
},
"scannedAt": "2022-07-04T11:47:24.011486+09:00",
"scanMode": "fast mode",
"scannedVersion": "`make build` or `make install` will show the version",
"scannedRevision": "",
"scannedBy": "ma2no.lan",
"scannedVia": "pseudo",
"scannedIpv4Addrs": [],
"reportedAt": "0001-01-01T00:00:00Z",
"reportedVersion": "", …
```
=> feat(saas) add vuls tags from env

reporter/slack.go
fix vuls report not send to each server name's channel.
(when slack's channel is "${servername}" in configuration file)
- set to slack's channel is "${servername}" 
- vuls report -to-slack
=> fix(report): send report to each slack channel

go.mod, go.sum, reporter/localfile.go, reporter/sbom/cyclonedx.go, subcmds/report.go
add CycloneDX format
```console
or 
```
=> feat(report): add cyclonedx format

.github/workflows/golangci.yml
update version for golangci-lint  on github actions
=> chore: update version for golangci-lint

logging/logutil.go
=> fix: add comment

detector/github.go, models/github.go, models/vulninfos.go, reporter/chatwork.go, reporter/email.go, reporter/googlechat.go, reporter/localfile.go, reporter/sbom/cyclonedx.go, reporter/slack.go, reporter/stdout.go, reporter/syslog.go, reporter/telegram.go, server/server.go
=> style: fix typo

detector/github.go
fix(detector/github) change timeout 10s to 10m
=> fix(detector/github) change timeout 10s to 10m

.goreleaser.yml
add windows for snmp2cpe in goreleaser
=> feat(ci): add windows exe for snmp2cpe

gost/debian.go, gost/ubuntu.go
I have added comments to the parts that were difficult to understand at first glance.
=> add comments

gost/debian.go, gost/debian_test.go, gost/ubuntu.go, gost/ubuntu_test.go
check kernel source package more strictly
https://go.dev/play/p/3ovVScL4zNL
=> feat(gost/ubuntu): check kernel source package more strictly

subcmds/saas.go
Since the current directory is no longer created, this part is no longer needed.
=> fix(saas): remove current directory part

gost/debian_test.go
=> test: sort []cveContent by CVEID

scanner/base.go
Classify lsof errors and do not print WARN log if it can be determined that there is no problem.
```console
root@3f61eccb5a0f:~# lsof -i -P -n
COMMAND PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
sshd      1 root    3u  IPv4 1217677      0t0  TCP *:22 (LISTEN)
sshd      1 root    4u  IPv6 1217679      0t0  TCP *:22 (LISTEN)
sshd     19 root    4u  IPv4 1228440      0t0  TCP 172.17.0.3:22->172.17.0.1:42736 (ESTABLISHED)
root@3f61eccb5a0f:~# lsof -i -P -n -V
COMMAND PID USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
sshd      1 root    3u  IPv4 1217677      0t0  TCP *:22 (LISTEN)
sshd      1 root    4u  IPv6 1217679      0t0  TCP *:22 (LISTEN)
sshd     36 root    4u  IPv4 1235109      0t0  TCP 172.17.0.3:22->172.17.0.1:39442 (ESTABLISHED)
```
```console
root@b360c93561fa:~# lsof -i -P -n …
```
=> chore(scanner): do not show logs when lsof: no Internet files located

scanner/scanner.go, scanner/windows.go, scanner/windows_test.go
- export DetectKBsFromKernelVersion
=> feat(windows) export DetectKBsFromKernelVersion

contrib/snmp2cpe/pkg/cpe/cpe.go, contrib/snmp2cpe/pkg/cpe/cpe_test.go
add other fortinet products.
Note, however, that I do not have any Fortinet products other than FortiGate, so this implementation is based on the assumption that SNMP would respond in this manner.
=> feat(contrib/snmp2cpe): add other fortinet products

contrib/future-vuls/pkg/cpe/cpe.go
output detail of loading toml error
=> fix(contrib/future-vuls) output detail of loading toml error

config/config_v1.go
=> chore: remove refs to deprecated io/ioutil

config/os.go, config/os_test.go
=> chore(os): update EOL

scanner/scanner.go
This commit removes rand.Seed() from scanner package.
See more info 👉 https://pkg.go.dev/math/rand#Seed
=> chore: remove rand.Seed()

scanner/alma.go, scanner/amazon.go, scanner/base.go, scanner/centos.go, scanner/debian.go, scanner/fedora.go, scanner/rhel.go, scanner/rocky.go, scanner/suse.go
revert lsof command for futurevuls users
=> feat(scanner): revert lsof command for futurevuls users

config/os.go, config/os_test.go
AmazonLinux 1 support has been extended from 2023/6/30 to 2023/12/31, and the EOL determination map has been changed.
=> chore(config):Modification of AmazonLinux 1 maintenance deadline

scanner/macos.go
remove unnecessary error check
=> fix(scanner/macos): remove unnecessary error check

config/config_v1.go, saas/uuid.go, subcmds/configtest.go, subcmds/scan.go
* https://vuls.io/docs/en/usage-settings.html is 404.
* Perhaps, is https://vuls.io/docs/en/config.toml.html correct?
=> style(log) config.toml template docs url

contrib/snmp2cpe/pkg/cpe/cpe_test.go, detector/github.go, detector/util.go, reporter/syslog_test.go, reporter/util.go, tui/tui.go
=> style: fix some typos in comments

.github/dependabot.yml
groups:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
github-actions:
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#github-actions
=> feat(ci): group aws-sdk-go-v2 updates, check github actions update

README.md
=> docs: correct ubuntu oval link

gost/microsoft.go, gost/microsoft_test.go
ignore other products that do not have KBs
by unit test
=> fix(gost/windows): ignore other products that do not have KBs

detector/vuls2/vendor.go, detector/vuls2/vuls2.go
- Fix data source preference bug.
- Prior to this, oval v1 is prefered to v2
- Fix root id selection bug.
- Prior to this, selection of 3+ root IDs are buggy (range map dependent)
Using vuls-compare.
ref: https://github.com/future-architect/vuls/pull/2075#issuecomment-2526996047
=> fix(detector/vuls2): fix post convert bugs

detector/vuls2/vendor.go
=> fix(detector/vuls2): lower stauts string and compare

go.mod, go.sum
=> chore(deps): update vuls2

contrib/trivy/parser/v2/parser_test.go, contrib/trivy/pkg/converter.go
refs https://github.com/future-architect/vuls/pull/2120
unit test
=> feat(contrib/trivy-to-vuls): add version in LibraryFixedIns

.github/workflows/docker-publish.yml, .github/workflows/goreleaser.yml, .goreleaser.yml, GNUmakefile
review of build flags, increase of runner storage
=> chore(ci): review of build flags, increase of runner storage

detector/vuls2/vuls2.go
fill cvss v4.0
```console
$ tree vuls-data-extracted-test/
vuls-data-extracted-test/
├── data
│   └── 2025
│       └── TEST-2025-0001.json
└── datasource.json
2 directories, 2 files
$ cat vuls-data-extracted-test/datasource.json 
{
"id": "test",
"name": "test data"
}
$ cat vuls-data-extracted-test/data/2025/TEST-2025-0001.json
{
"id": "TMP-2025-0001",
"vulnerabilities": [
{
"content": {
"id": "TMP-2025-0001",
"description": "This is a test vulnerability.",
"severity": [
{
"type": "cvss_v40",
"source": "test",
"cvss_v40": {
"vector": "CVSS:4.0/AV:N/AC:L/AT:N/PR:H/UI:A/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N",
"score": 4.6,
"severity": "MEDIUM"
}
}
],
"published": "2025-05-01T15:00:00Z"
},
"segments": [
{
"ecosystem": …
```
=> feat(detector/vuls2): fill cvss v4.0

go.mod, go.sum
Fixes #1540 
```console
$ vuls discover 127.0.0.1/24 | grep "^\[servers.127-0-0-" | wc -l
[May  8 12:58:28]  INFO [localhost] vuls-0.30.0-358cbf59b8480330cebed319dee1bfc4c5704c7e-2025-03-18T06:42:29Z
100
```
```console
$ vuls discover 127.0.0.1/24 | grep "^\[servers.127-0-0-" | wc -l
[May  8 12:58:20]  INFO [localhost] vuls-v0.30.0-build-20250508_125646_c5be265
254
```
=> chore(deps): bump github.com/kotakanbe/go-pingscanner

detector/vuls2/vuls2.go, go.mod, go.sum
Fixes #2213 
```powershell
PS C:\Users\vagrant> .\vuls.exe report --refresh-cve 2025-05-22T00-00-00+0900
time="May 21 10:25:40" level=info msg="vuls-v0.32.0-build-20250522_022450_3bc9815" 
time="May 21 10:25:40" level=info msg="Validating config..." 
time="May 21 10:25:40" level=info msg="cveDict.type=sqlite3, cveDict.url=, cveDict.SQLite3Path=C:\\Users\\vagrant\\cve.sqlite3" 
time="May 21 10:25:40" level=warning msg="cveDict.SQLite3Path=C:\\Users\\vagrant\\cve.sqlite3 file not found" 
time="May 21 10:25:40" level=info msg="ovalDict.type=sqlite3, ovalDict.url=, ovalDict.SQLite3Path=C:\\Users\\vagrant\\oval.sqlite3" 
time="May 21 10:25:40" level=warning msg="ovalDict.SQLite3Path=C:\\Users\\vagrant\\oval.sqlite3 file not found" 
time="May 21 10:25:40" level=info msg="gost.type=sqlite3, …
```
=> chore(deps): bump github.com/MaineK00n/vuls2

.github/workflows/scorecard.yml
fixes https://github.com/future-architect/vuls/actions/workflows/scorecard.yml
=> fix(ci): replace with actual default branch name

config/vulnDictConf.go, detector/vuls2/vuls2.go
save digest of the vuls2 db
```console
$ vuls report
$ jq -r '.config.report.vuls2' results/2025-09-07T18-23-51+0900/localhost.json 
{
"Repository": "ghcr.io/vulsio/vuls-nightly-db:0",
"Digest": "sha256:49ec9421e96d300b47a1ed552e9c790548def161e0e1b8fb12c75ea15319a0d1",
"Path": "",
"SkipUpdate": false
}
```
=> feat(detector/vuls2): save digest of the vuls2 db

detector/detector.go, detector/vuls2/vendor.go, detector/vuls2/vuls2.go, go.mod, go.sum, oval/redhat.go, oval/util.go, oval/util_test.go
detect fedora with vuls2
```console
$ curl -sL --create-dirs --output results/2025-09-09T00-00-00+0900/fedora_38.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/results/fedora_38.json
$ curl -sL --create-dirs --output results/2025-09-09T00-00-00+0900/fedora_42.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/results/fedora_42.json
version = "v2"
[cveDict]
type = "sqlite3"
[ovalDict]
type = "sqlite3"
[gost]
type = "sqlite3"
[exploit]
type = "sqlite3"
[metasploit]
type = "sqlite3"
[kevuln]
type = "sqlite3"
[cti]
type = "sqlite3"
[vuls2]
repository = "ghcr.io/vulsio/vuls-nightly-db:0"
[default]
[servers]
EOS
```
```console
$ …
```
=> feat!(detector): detect fedora with vuls2

contrib/future-vuls/cmd/main.go, go.mod, go.sum
Just remove https://github.com/3th1nk/cidr from the dependency.
Preparation: Using https://github.com/MaineK00n/vuls-targets/
```
docker run --rm -itd -p 161:161/udp --name vt-snmp vuls-target:snmp
```
Error path:
```
% PATH=.:$PATH ./future-vuls discover --cidr '127.0.0.1/XXXX' --community juniper-mx960-13-3r9-13
Error: Invalid cidr range
Usage:
future-vuls discover --cidr <CIDR_RANGE> --output <OUTPUT_FILE> [flags]
Examples:
future-vuls discover --cidr 192.168.0.0/24 --output discover_list.toml
Flags:
--cidr string           cidr range
--community string      snmp community name. default: public
-h, --help                  help for discover
--output string         output file
--snmp-version string   snmp version v1,v2c and v3. default: v2c …
```
=> refactor(contrib/future-vuls): remove cidr dependency
