- commands/prepare.go
- commands/scan.go
- scan/linux.go
- scan/redhat.go
- scan/serverapi.go
Enable vuls to scan In the case of sudo password is required (not configured NOPASSWORD in /etc/sudoers) on RHEL, CentOS and Amazon Linux.
```
echo password | sudo sh -c 'yum check-update'
to 
echo password | sudo -S yum check-update
```
> Fix sudo option on RedHat like Linux, change some messages.

- scan/redhat.go
- scan/redhat_test.go
When Parsing the result of yum check-update, error occurred at the line below.
``` 
Obsoleting Packages 
```
> Fix error while parsing yum check-update #24

- README.md
- commands/scan.go
- config/config.go
- models/models.go
- report/slack.go
- report/util.go
If you don't want to display unscored CVEs. (displayed ? at cvss score), scan with -ignore-unscored-cves option.
> Add ignore-unscored-cves option

- README.md
- commands/history.go
- commands/tui.go
- db/db.go
- main.go
- report/tui.go
- add vuls history subcommand
- vuls tui scan_history_id
> Enable to show previous scan result

- .gitignore
- README.md
- commands/scan.go
- models/models.go
- report/json.go
- report/slack.go
- report/util.go
- report/writer.go
- scan/debian.go
- scan/linux.go
- scan/redhat.go
- scan/serverapi.go
- Add -report-json option. 
Scan results will be available in JSON format in the $PWD/result/current/ directory. 
- Fix sort order of scan report (order by score, CVE-ID)
> Add JSONWriter, Fix CVE sort order of report

- commands/scan.go
- config/config.go
- cveapi/cve_client.go
It is an error in go-cve-dictionary API when result of scan is many.
> Add option for it get cve detail from cve.sqlite3.

- scan/freebsd.go
- scan/serverapi.go
Created scan/freebsd.go to enable package searching on FreeBSD. The file uses the many functions of pkg to get the job done, including pkg version, pkg info, and pkg query. 
scan/serverapi.go is also changed to call the detectBSD function in freebsd.go
> Added FreeBSD support.

- .gitignore
- scan/redhat_test.go
- scan/sshutil.go
I fixed the following error of scaning RHEL servers.
```
% go run main.go scan
INFO[0000] Start scanning
INFO[0000] config: /Users/matsunosadayuki/go/plugins/src/github.com/future-architect/vuls/config.toml
INFO[0000] cve-dictionary: http://127.0.0.1:1323
[Jun  5 12:59:22]  INFO [localhost] Validating Config...
[Jun  5 12:59:22]  INFO [localhost] Detecting Server OS...
[Jun  5 12:59:26]  INFO [localhost] (1/1) Detected vuls-dev-rhel: rhel 6.5
[Jun  5 12:59:26]  INFO [localhost] Detecting Container OS...
[Jun  5 12:59:26]  INFO [localhost] Scanning vulnerabilities...
[Jun  5 12:59:26]  INFO [localhost] Check required packages for scanning...
[Jun  5 12:59:26]  INFO [localhost] Scanning vulnerable OS packages...
[Jun  5 13:00:36] ERROR [vuls-dev-rhel] Failed to scan vulnerable packages
[Jun …
```
> fix rhel check-update format and add *config.toml into .gitignore

- config/config.go
- models/models.go
- report/util.go
- report/writer.go
- scan/debian.go
- scan/debian_test.go
- scan/freebsd.go
- scan/freebsd_test.go
- scan/serverapi.go
- scan/sshutil.go
- Implement of the remaining parts of https://github.com/future-architect/vuls/pull/90 .
- Add test case.
- Don't use bash on FreeBSD #91
> Enable to detect vulnerabilities on FreeBSD

- README.md
- commands/scan.go
- config/config.go
- scan/freebsd.go
- scan/serverapi.go
- scan/sshutil.go
Vuls supports different types of SSH.  
By Defaut, using a native Go implementation from crypto/ssh.   
This is useful in situations where you may not have access to traditional UNIX tools.
To use external ssh command, specify this option.   
This is useful If you want to use ProxyCommand or chiper algorithm of SSH that is not supported by native go implementation.
> [WIP]Support scanning with external ssh command

- scan/freebsd.go
An error occurred when the old vuln db file is remaining . 
```
[Jun 27 05:04:00] ERROR [localhost] Failed to scan. err: kanbe@192.168.11.11:22: Failed to pkg audit -F -f /tmp/vuln.dbFetching vuln.xml.bz2: 100%  605 KiB 206.5kB/s    00:03
pkg: pkg_audit_fetch(open out fd): Permission denied
, Stderr:
```
Remove the vuln db file before pkg audit -F.
> Remove vulndb file before pkg audit

- README.ja.md
- README.md
- commands/scan.go
This change adds to help to specify server option on `vuls scan` command.
In passing this change fix trivial typo too.
> Fix scan command help

- README.ja.md
- README.md
Fix wrong link in README 
```
- github.com/bumptech/glide
+ github.com/Masterminds/glide
```
> Fix README wrong links

- README.ja.md
- README.md
- commands/prepare.go
- commands/scan.go
- config/config.go
- glide.lock
- glide.yaml
- report/azureblob.go
- report/s3.go
- scan/debian.go
To put results in Azure Blob Storage, configure following settings in Azure before scanning.
- Create a container
```
$ vuls scan \
-cve-dictionary-dbpath=$PWD/cve.sqlite3 \ 
-report-azure-blob \
-azure-container=vuls \
-azure-account=test \
-azure-key=access-key-string 
```
With this sample command, it will ..
- Use SSH Key-Based authentication with empty password (without -ask-key-password option)
- Sudo with no password (without -ask-sudo-password option)
- Scan all servers defined in config file
- Put scan result(JSON) in Azure Blob Storage. The container name is "vuls", storage account is "test" and accesskey is "access-key-string"
account and access key can be defined in environment variables.
```
$ export AZURE_STORAGE_ACCOUNT=test
$ export …
```
> Support -report-azure-blob option

- README.ja.md
- README.md
- commands/discover.go
- config/config.go
- config/tomlloader.go
- models/models.go
- scan/base.go
- scan/redhat.go
Optional key-value will be outputted to JSON.
The key-value in the default section will be overwritten by servers section's key-value.
For instance, you can use this option for Azure ResourceGroup name,  Azure VM Name and so on
- config.toml
```toml
[default]
optional = [
["key1", "default_value"],
["key3", "val3"],
]
[servers.bsd]
host     = "192.168.11.11"
user     = "kanbe"
optional = [
["key1", "val1"],
["key2", "val2"],
]
```
- all.json
```json
[
{
"ServerName": "bsd",
"Family": "FreeBSD",
"Release": "10.3-RELEASE",
.... snip ...
"Optional": [
[  "key1", "val1" ],
[  "key2", "val2" ],
[  "key3", "val3" ]
]
}
]
```
> [WIP]Add optional key-values that will be outputted to JSON in config

- README.ja.md
add some tips about NVD/JVN initial scripts and how to update vuls and go-cve-dictionary.
> add tips about NVD JVN issue

- scan/base.go
`r` referred to the response of command, `type curl`, so status is 0 when it was evaluated in `switch` statement.
> Fix platform detection.

- README.ja.md
- README.md
- commands/configtest.go
- commands/scan.go
- main.go
- scan/base.go
- scan/debian.go
- scan/freebsd.go
- scan/redhat.go
- scan/serverapi.go
- scan/sshutil.go
- util/util.go
Configtest subcommand check if vuls is able to connect via ssh to servers/containers defined in the config.toml.  
```
$ vuls configtest --help
configtest:
configtest
[-config=/path/to/config.toml]
[-ask-key-password]
[-ssh-external]
[-debug]
[SERVER]...
-ask-key-password
Ask ssh privatekey password before scanning
-config string
/path/to/toml (default "/Users/kotakanbe/go/src/github.com/future-architect/vuls/config.toml")
-debug
debug mode
-ssh-external
Use external ssh command. Default: Use the Go native implementation
```
> Add configtest subcommand. skip un-ssh-able servers.

- scan/redhat.go
- scan/redhat_test.go
- This high-speed scanning is only valid to sshExecNative mode.
- Because there are Pty and persing issues in sshExecExternal.
- :relieved:
> Support high-speed scanning for CentOS

- README.ja.md
- README.md
- scan/redhat.go
- scan/sshutil.go
- Fix no tty error while scanning with -external-ssh
- High speed scan in -ssh-external mode (see. #138 )
> Fix no tty error while executing with -external-ssh option

- scan/debian.go
Add LANG=en_US.UTF-8 at the beginning of apt command.
Currently, on Ubuntu, no vulnerabilities are found when system locale is not English.
> Fix apt command to scan correctly when system locale is not english

- README.ja.md
- README.md
- commands/configtest.go
- commands/prepare.go
- commands/scan.go
- config/config.go
- config/loader.go
- config/tomlloader.go
- scan/debian.go
- scan/freebsd.go
- scan/redhat.go
- scan/serverapi.go
- scan/sshutil.go
Disable -ask-sudo-password option for security reasons.
Vuls user have to be able to execute below commands via SSH without sudo password.
- CentOS, RHEL, Amazon Linux ... `/usr/bin/yum`
- Debian, Ubuntu ... `/usr/bin/apt-get, /usr/bin/apt-cache`
Example of /etc/sudoers on target servers
- CentOS, Amazon Linux, RedHat Enterprise Linux
```
vuls ALL=(root) NOPASSWD: /usr/bin/yum
```
- Ubuntu, Debian
```
vuls ALL=(root) NOPASSWD: /usr/bin/apt-get, /usr/bin/apt-cache
```
> Disable -ask-sudo-password for security reasons

- scan/debian.go
- scan/redhat.go
> Fix CVE-ID is truncated to 4 digits

- setup/docker/dockerfile/Dockerfile
When I tried `docker-compose up -d`, but encoutered bug.
```
Step 25 : RUN cp -rp /tmp/vulsrepo/src/* /usr/share/nginx/html/vulsrepo
---> Running in 5e3c7fbc4e6b
cp: cannot stat '/tmp/vulsrepo/src/*': No such file or directory
ERROR: Service 'vuls' failed to 
```
This affected below PR https://github.com/usiusi360/vulsrepo/pull/20
> Fix bug: Vuls on Docker

- scan/debian.go
- scan/redhat.go
Hi, I've started reading the code of vuls yesterday and noticed the many regexp compilation on runtime. Specifically, we should avoid calling regexp.Compile in loops because it affects the performance badly. What do you think?
> Reduce regular expression compilation

- config/config.go
- scan/debian.go
- scan/serverapi.go
- scan/sshutil.go
- util/logutil.go
Changelog cache was not working on Docker enviroment because the key was servername.
I fix the problem.
I changed the key of changelog cache from servername to containerID@servername.
> Fix not working changelog cache on Container

- README.ja.md
- README.md
- commands/scan.go
- config/config.go
- scan/serverapi.go
> Add only-containers option to scan subcommand #122

- README.ja.md
- README.md
- commands/discover.go
- glide.lock
- glide.yaml
- report/mail.go
ref #146
fix conflict and reopen it.
> change e-mail package from gomail to net/smtp

- scan/redhat.go
- scan/redhat_test.go
When package was installed from ISO or CD/DVD it can contain repository name with whitespaces. Example from one of our servers:
```bash
$ LANG=en_US.UTF-8 yum --color=never check-update -q | tr -s " " | grep pytalloc
pytalloc.x86_64 2.1.5-1.el6_7 base 
pytalloc.x86_64 2.1.5-1.el6_7 base 
pytalloc.x86_64 2.0.7-2.el6 @CentOS 6.5/6.5
```
In this case vuls can't parse last line from example because in `parseYumCheckUpdateLine` number of fields is limited by 3.
> Fixed bug with parsing update line on CentOS/RHEL

- scan/debian.go
- scan/redhat.go
LANGUAGE is more priority than LANG.
http://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html
```
2.3.2 Locale Environment Variables
A locale is composed of several locale categories, see Aspects. When a program looks up locale dependent values, it does this according to the following environment variables, in priority order:
LANGUAGE
LC_ALL
LC_xxx, according to selected locale category: LC_CTYPE, LC_NUMERIC, LC_TIME, LC_COLLATE, LC_MONETARY, LC_MESSAGES, ...
LANG
```
> Fix locale env var LANG to LANGUAGE

- glide.lock
- report/tui.go
Previously, the method just returned an error if an error occurred (or nil if no error).
The new method now returns the view as well as well as the error object.  Updated to ignore the
view and handle the error object as usual.
Fix for issue #228.
https://github.com/future-architect/vuls/issues/228
> Handle the refactored gocui SetCurrentView method.

- glide.lock
- report/tui.go
The following is the error:
go/src/github.com/future-architect/vuls/report/tui.go:52: multiple-value gocui.NewGui() in single-value context
> Fixed error for the latest version of gocui

- README.ja.md
- README.md
- commands/discover.go
- commands/scan.go
- config/config.go
- config/tomlloader.go
- contrib/owasp-dependency-check/parser/parser.go
[OWASP Dependency check](https://www.owasp.org/index.php/OWASP_Dependency_Check) is a utility that identifies project dependencies and checks if there are any known, publicly disclosed, vulnerabilities.
Benefit of integrating Vuls And OWASP Dependency Check is below.
- Automatic Update of Vuls config when the libraries are updated.
- Reporting by Email or Slack by using Vuls.
- Reporting in Japanese
- OWASP Dependency Check supports only English
How to integrate Vuls with OWASP Dependency Check
- Execute OWASP Dependency Check with --format=XML option.
- Define the xml file path of dependency check in config.toml.
```
[servers]
[servers.172-31-4-82]
host         = "172.31.4.82"
user        = "ec2-user"
keyPath     = "/home/username/.ssh/id_rsa"
dependencyCheckXMLPath = …
```
> Integrate OWASP Dependency Check

- commands/scan.go
- config/config.go
- cveapi/cve_client.go
New PR for the mysql support.  Previous one was done on master and additional commits went into it before they were ready.  
This PR requires changes made to kotakanbe/go-cve-dictionary a couple of days ago.
kotakanbe/go-cve-dictionary#25
> Add support for reading CVE data from MySQL.

- commands/prepare.go
use sshproxy in "vuls".
"scan subcommand" is supported -ssh-external option, but "prepare subcommand" isn't supported it.
I need -ssh-external option to "prepare subcommand".
and modify gofmt.
> add '-ssh-external' option to prepare subcommand

- scan/debian.go
For details, see #235 
It's better to scan after removing cache.db.
> Fix changelog cache bug on Ubuntu and Debian #235

- README.ja.md
- README.md
- commands/scan.go
- glide.lock
- models/models.go
- report/xml.go
Add the XML output in order to facilitate cooperation with other tools.
> Add the XML output

- commands/configtest.go
- commands/discover.go
- commands/history.go
- commands/prepare.go
- commands/scan.go
- commands/tui.go
- glide.lock
- main.go
Corresponding to https://github.com/google/subcommands/pull/5.
- See also https://github.com/kotakanbe/go-cve-dictionary/pull/32
> Moved golang.org/x/net/context to context

- config/config.go
- config/tomlloader.go
- models/models.go
- scan/redhat.go
- scan/redhat_test.go
If you define as below in config.toml.
```
[servers.cent6]
host     = "127.0.0.1"
port     = "20062"
user     = "vuls"
keyPath  = "/path/to/id_rsa"
enablerepo = "updates,base"
```
Vuls issues yum with --enablerepo option
- yum check-update
```
yum --color=never --enablerepo=updates,base check-update
```
- yum --changelog update
```
yum  --enablerepo=updates,base --changelog update wget
```
See #246
For now, base and updates repository are supported.
Because a change-log format of additional yum repository is different  for each repos...
> Supports yum --enablerepo option (supports only base,updates for now)

- scan/debian.go
Setting `DEBIAN_FRONTEND=noninteractive` may be more robust if doing more with `apt-get`.
> Fix non-interactive `apt-get install` #251

- report/azureblob.go
- report/json.go
- report/s3.go
- report/util.go
This is a standard format that still preserves natural ordering in the results, is arguably easier to read, and also provides both seconds and time zone information, e.g. `2006-01-02T15:04:05Z07:00`.
> Use RFC3339 timestamps in the results

- commands/prepare.go
- config/config.go
- scan/sshutil.go
This minor refactor checks the SSHExternal flag during validations, rather that setting it and then quietly ignoring it on Windows machines.
> Stop quietly ignoring `--ssh-external` on Windows

- models/models.go
- scan/base.go
- scan/serverapi_test.go
An output of "vuls scan -report-*" may be different with each other, even though the target servers are not changed at all.
Because [the CvePacksInfo.Packs are generated in parallel by goroutines](https://github.com/future-architect/vuls/blob/46f96740a2d085863cd650afd53def2ad95e856d/scan/debian.go#L425-L456), the order is indeterminate.
This behavior makes difficult to implement [a custom feature](http://qiita.com/usiusi360/items/90bad397c16c07a9630b) to notify the difference from the previous scan result.
[MEMO] The pull request might also be helpful for #255.
> Keep output of "vuls scan -report-*" to be same every times

- report/mail.go
Vuls report mail has NO charset header.
This pull request contain 'Content-Type: text/plain; charset=utf8' header.
> Add Content-Type header to report/mail.go .

- config/tomlloader.go
- scan/base.go
- scan/base_test.go
- scan/serverapi.go
- scan/sshutil.go
Support scanning LXD Container .
> Add LXD support

- scan/redhat.go
OS : CentOS 6.8
Even if I forget to write `/bin/echo` in sudoers file, `vuls configtest` will succeed.
However, `vuls scan` will fail because `echo N` is used in `getAllChangelog`.
```
$ sudo cat /etc/sudoers | grep vuls
vuls ALL=(root) NOPASSWD: /usr/bin/yum
$ vuls configtest
[Jan 22 23:18:05]  INFO [localhost] Validating Config...
[Jan 22 23:18:05]  INFO [localhost] Detecting Server/Contianer OS...
[Jan 22 23:18:05]  INFO [localhost] Detecting OS of servers...
[Jan 22 23:18:06]  INFO [localhost] (1/1) Detected: vagrant: centos 6.8
[Jan 22 23:18:06]  INFO [localhost] Detecting OS of containers...
[Jan 22 23:18:06]  INFO [localhost] Checking sudo configuration...
[Jan 22 23:18:06]  INFO [vagrant] sudo ... OK
[Jan 22 23:18:06]  INFO [localhost] SSH-able servers are below...
vagrant
$ vuls …
```
> Check whether echo is executable with nopasswd

- setup/docker/README.md
If I run command according to README.md, `vuls prepare` will fail.
I think that it is because `stdin` is not opened.
```
$ docker run --rm -v ~/.ssh:/root/.ssh:ro -v $PWD:/vuls -v $PWD/vuls-log:/var/log/vuls vuls/vuls prepare -config=./config.toml
time="2017-01-21T13:07:34Z" level=info msg="Start Preparing (config: ./config.toml)"
time="2017-01-21T13:07:34Z" level=info msg="Validating Config..."
time="Jan 21 13:07:34" level=info msg="Detecting OS... "
time="Jan 21 13:07:34" level=info msg="Detecting OS of servers... "
time="Jan 21 13:07:35" level=info msg="(1/1) Detected: vagrant: centos 6.8"
time="Jan 21 13:07:35" level=info msg="Detecting OS of containers... "
time="Jan 21 13:07:35" level=info msg="Checking sudo configuration... "
time="Jan 21 13:07:36" level=info msg="sudo ... OK" …
```
> Update docker README

- README.ja.md
- README.md
- commands/configtest.go
- commands/report.go
- commands/scan.go
- commands/tui.go
- commands/util.go
- config/config.go
- scan/redhat.go
#294
Solved the problem of trying to read from STDIN and stopping on the way when running from CRON or AWS Lambda.
> Add -pipe flag #294

- README.ja.md
- README.md
- scan/redhat.go
In the case of CentOS,  we need to write `/bin/echo` to sudoers.
```
vuls ALL=(root) NOPASSWD: /usr/bin/yum, /bin/echo
```
However, with CentOS 6,7 , `yum --assumeno` option makes `/bin/echo` unnecessary.
> Use --assumeno option

- glide.lock
see https://github.com/kotakanbe/go-cve-dictionary/pull/40
> Update glide.lock to fix create-log-dir error.

- cache/bolt.go
- cache/bolt_test.go
- cache/db.go
- scan/debian.go
- scan/debian_test.go
In the past implementations, there was a bug in the Cache of Ubuntu / Debian's Changelog, which lacked detection of vulnerability.
This bug was fixed.
If you are using Vuls to detect Ubuntu / Debian vulnerabilities please update to the latest version.
see https://github.com/future-architect/vuls#update-vuls-with-glide
Note that this bug has no effect on other than Ubuntu / Debian scanning.
> Fix the changelog cache logic for ubuntu/debian

- glide.lock
see https://github.com/kotakanbe/go-cve-dictionary/pull/41
> Update glide.lock to fix import error

- README.ja.md
- README.md
- scan/redhat.go
- scan/sshutil.go
https://github.com/future-architect/vuls/pull/315
`yum` which is old release does not have `--assumeno`.
It is available if I update `yum` , but I changed to not use sudo when echo.
> Do not use sudo when echo

- commands/configtest.go
- commands/prepare.go
- commands/report.go
- commands/scan.go
- commands/tui.go
- glide.lock
- models/models.go
- report/email.go
- report/slack.go
- report/tui.go
- report/util.go
- scan/base.go
- scan/debian.go
- scan/executil.go
- scan/freebsd.go
- scan/redhat.go
- scan/serverapi.go
- scan/unknownDistro.go
- util/logutil.go
see #264
Until now, when an error occurred in one of the servers during scanning, scanning was terminated halfway.This P/R change the scan to continue for servers that did not have errors.
Test
> Continue scanning even when some hosts have tech issues

- scan/debian.go
- scan/serverapi.go
I tested on Raspbian jessie.
```
pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie
```
> Support Raspbian

- README.ja.md
- README.md
- commands/report.go
- config/config.go
- report/email.go
- report/email_test.go
I accidentally closed...
I'm sorry to send PR again.
https://github.com/future-architect/vuls/pull/310
> Add -format-one-email option

- commands/report.go
Because error handling was missing
> add error handling

- report/email.go
- report/email_test.go
I think, with this code, `cc` address will not receive e-mail.
This is because `emailConf.To` is specified to `to` field.
https://github.com/future-architect/vuls/blob/master/report/email.go#L125
Please check if vuls send to `cc` address.
> Bug fix: not send e-mail to cc address

- README.ja.md
- README.md
- commands/report.go
- commands/util.go
- models/models.go
- report/slack.go
- report/tui.go
- report/util.go
- scan/debian.go
- scan/debian_test.go
- scan/freebsd.go
- scan/redhat.go
Added an item called Confidence to the report. 
Describe the description in README.md.
```
CVE-2016-5636
-------------
Score           10.0 (High)
Vector          (AV:N/AC:L/Au:N/C:C/I:C/A:C)
Summary         Integer overflow in the get_data function in zipimport.c in CPython (aka Python)
before 2.7.12, 3.x before 3.4.5, and 3.5.x before 3.5.2 allows remote attackers
to have unspecified impact via a negative data size value, which triggers a
heap-based buffer overflow.
CWE             https://cwe.mitre.org/data/definitions/190.html
NVD             https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2016-5636
MITRE           https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-5636
CVE Details     http://www.cvedetails.com/cve/CVE-2016-5636
CVSS Claculator …
```
> Output confidence score of detection accuracy and detection method to JSON or Reporting

- main.go
remove unused import line.
It was no longer necessary because access to gorm was limited to go-cve-dictionary library.
compile & run vuls.
> remove unused import line.

- scan/executil.go
Closes https://github.com/future-architect/vuls/issues/360
Increase the width (256→1000)
You need the multi-line changelog.
If the output of one line exceeds the specified width (256), it will start new line in the middle.
> Increase the width of RequestPty

- README.ja.md
- README.md
- models/models.go
- report/azureblob.go
- report/email.go
- report/localfile.go
- report/s3.go
- report/stdout.go
- report/tui.go
- report/util.go
- scan/debian.go
- scan/debian_test.go
- scan/executil.go
- scan/redhat.go
- scan/redhat_test.go
In case of updating vulnerable package, it is helpful to see a changelog information.
The output change log includes only the difference between the currently installed version and candidate version.
Closes #341 
**NOTE**
**Amazon/RHEL/FreeBSD will be implemented after abolition of prepare subcommand. #365**
remove cache.db
> Output changelog in report, TUI and JSON for Ubuntu/Debian/CentOS

- scan/executil.go
Closes https://github.com/future-architect/vuls/issues/359
Change ssh option from `-t` to `-tt`.
If ssh has no local tty, `-tt` option should be used to force pseudo-terminal allocation.
```
$ man ssh
-t      Force pseudo-terminal allocation.  This can be used to execute arbitrary screen-based programs on a remote machine, which can be very useful, e.g. when implementing menu services.Multiple -t options force tty allocation, even if ssh has no local tty.
```
```
$ ./vuls scan -ssh-external
```
> Change ssh option from -t to -tt

- scan/redhat.go
For RHEL, sudo privilege is required at yum check-update
Closes #371
./vuls scan
> sudo yum check-update on RHEL

- models/models.go
- report/util.go
Closes #373
Don't count duplicate package names.
Make sure that the number of updatable packages of vuls scan result and yum check-update are the same
> Fix updatalbe packages count #373

- README.ja.md
- README.md
- report/s3.go
Closes #250 
Please create the following IAM role and attach it to the EC2 instance, run `vuls report`.
```
{
"Version": "2012-10-17",
"Statement": [
{
"Effect": "Allow",
"Action": [
"s3:ListAllMyBuckets"
],
"Resource": "arn:aws:s3:::*"
},
{
"Effect": "Allow",
"Action": [
"s3:PutObject"
],
"Resource": "arn:aws:s3:::vuls/*"
}
]
}
```
```
$ vuls report \
-format-json \
-to-s3 \
-aws-region=ap-northeast-1 \
-aws-s3-bucket=vuls
```
> Support IAM role for report to S3.

- scan/debian.go
- scan/debian_test.go
Closes #362 #328 
see #362
see testcase
> Fix scan confidence on Ubuntu/Debian/Raspbian #362

- README.ja.md
- README.md
- commands/configtest.go
- commands/discover.go
- commands/scan.go
- config/config.go
- config/tomlloader.go
- models/models.go
- scan/base.go
- scan/executil.go
- scan/serverapi.go
- before
```
[servers]
[servers.172-31-4-82]
host         = "172.31.4.82"
user        = "ec2-user"
keyPath     = "/home/username/.ssh/id_rsa"
containers = ["${running}"]
[servers.172-31-4-82.container]
type = "lxd" # or "docker"
```
- after
```
[servers]
[servers.172-31-4-82]
host         = "172.31.4.82"
user        = "ec2-user"
keyPath     = "/home/username/.ssh/id_rsa"
[servers.172-31-4-82.containers]
type = "lxd" # or "docker"
included  = ["${running}"]
excluded = ["ubuntu1", "fa30c26ed699"]
```
Please note that plural form 's' is attached
[servers.172-31-4-82.container] -> [servers.172-31-4-82.container**s**]
Closes #285 
- Change config.toml to specify containers not to be scanned.
- Exclude non-scanned containers during scan.
- scan …
> Change container scan format in config.toml

- README.ja.md
- README.md
> Fix README

- README.md
- report/util.go
- report/writer.go
- scan/redhat.go
- scan/redhat_test.go
Signed-off-by: Avi Miller <avi.miller@oracle.com>
Closes #385
Modified the existing `scan/redhat.go` and `scan/redhat_test.go` source to identify Oracle Linux. Also updated `report/util.go` and `report/writer.go` to reference the correct URL for the Oracle Linux CVE and Errata information.
Scan an Oracle Linux Docker image. You can scan `oraclelinux:5`, `oraclelinux:6` and `oraclelinux:7`. The last image/tag is also `oraclelinux:latest`
> Add Oracle Linux support

- commands/tui.go
```
$ ./vuls tui
INFO[0000] Validating config...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4132d06]
goroutine 1 [running]:
panic(0x4710bc0, 0xc4200121b0)
/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/future-architect/vuls/vendor/github.com/Sirupsen/logrus.(*Entry).Debugf(0x0, 0x47c980a, 0x1b, 0xc42017ce30, 0x1, 0x1)
/Users/kotakanbe/go/src/github.com/future-architect/vuls/vendor/github.com/Sirupsen/logrus/entry.go:177 +0x26
github.com/future-architect/vuls/cveapi.cvedictClient.FetchCveDetailsFromCveDB(0x0, 0x0, 0xc42036c580, 0x5, 0x8, 0xc42017d418, 0x6, 0x4, 0xc4200001a0, 0x0)
/Users/kotakanbe/go/src/github.com/future-architect/vuls/cveapi/cve_client.go:137 +0xcd …
```
> Fix nil-ponter in TUI

- commands/report.go
"vuls report" returns the following error
```
[vuls@testvuls vuls]$ ./vuls report -format-short-text
[Mar 30 22:59:51]  INFO [localhost] Validating config...
[Mar 30 22:59:51]  INFO [localhost] cve-dictionary: /opt/vuls/cve.sqlite3
[Mar 30 22:59:51]  INFO [localhost] Loaded: %!s(func([]string) (string, error)=0x48b470)
vuls-server (centos6.8)
=======================
Total: 0 (High:0 Medium:0 Low:0 ?:0)    0 updatable packages
...
```
fix L388.
I checked the operation in the environment where phenomena occurred.
> fix report option Loaded error-info

- scan/executil.go
If containers were run with their user set to something other than root, docker exec will exec the command in the container as that user by default. Unfortunately, this causes many package manager commands to fail. This commit adds --user root to the docker exec command so that commands executed inside the container will always run as root.
> Add --user root to docker exec command

- scan/executil.go
Error message:
[Apr  2 13:36:49] DEBUG [localhost] Failed to Dial to u16, err: ssh: must specify HostKeyCallback, Retrying in 552.330144ms...
It is caused by breaking changes of Go library.
https://go-review.googlesource.com/c/38701/
> Fix SSH dial error

- README.ja.md
- README.md
- commands/configtest.go
I'd like to scan only containers.
`scan` subcommand has `-containers-only` option.
https://github.com/future-architect/vuls/pull/190
However, `configtest` doesn't have `-containers-only` option.
Then, an error about a host server occur.
I added `-containers-only` option to `configtest`.
```
$ vuls configtest -containers-only
```
> Add containers-only option to configtest

- README.ja.md
- README.md
- commands/configtest.go
- commands/scan.go
- config/config.go
- scan/executil.go
Closes #415 
Remove ssh-external option.
Add ssh-native-insecure option.
Run Vuls with/without this option.
> Change default ssh method from go library to external command

- lock.json
- report/slack.go
- report/tui.go
- report/util.go
- report/writer.go
The NVD site was renewed and the URL was changed.
> Change NVD URL to new one

- README.ja.md
- README.md
- scan/executil.go
Closes #415 
Change options of SSH command.
1. Remove the entry of target server in $HOME/ssh/.known_hosts
2. Vuls scan -> Error will be occurred because faild to connect via ssh 
3. SSH manually to add a host key to known_hosts
4. Vuls scan -> success
[TODO] Fix README
> SSH Hostkey check

- README.ja.md
- README.md
- commands/scan.go
- scan/serverapi.go
I added configuration for timeouts inside of scan command, which were hard-coded until now. I came across issue with timeouts for platform detection when testing with servers in Europe.
By adding two new flags for scan command.
Either try connect to servers in opposite side of world with default configuration or decrease timeouts configuration to see that values are used.
***Is it a breaking change?:*** No
> Define timeout for vulnerabilities scan and platform detection

- README.ja.md
- README.md
- commands/configtest.go
- commands/scan.go
- scan/serverapi.go
I got the following error.
```
$ vuls configtest
[Mar 31 20:12:18]  INFO [localhost] Validating config...
[Mar 31 20:12:18]  INFO [localhost] Detecting Server/Container OS...
[Mar 31 20:12:18]  INFO [localhost] Detecting OS of servers...
[Mar 31 20:12:28] ERROR [localhost] Timed out while detecting servers
[Mar 31 20:12:28] ERROR [localhost] (1/1) Timed out: ubuntu1404
[Mar 31 20:12:28] ERROR [localhost] Failed to init servers: No scannable servers
exit status 1
```
The timeout for detecting server OS is hard coded to 30 seconds.
https://github.com/future-architect/vuls/blob/master/scan/serverapi.go#L156
https://github.com/future-architect/vuls/blob/master/scan/serverapi.go#L218
I fixed this.
For `configtest`,  `-timeout` option has already implemented, so I used it.
For `scan`, I added …
> Enable -timeout option when detecting OS

- Gopkg.lock
- README.ja.md
- README.md
- commands/report.go
- commands/tui.go
- config/config.go
- cveapi/cve_client.go
Add support for PostgreSQL as a DB storage back-end
Add gorm's dialects of PostgreSQL.
Use postgresSQL as a vuls DB back-end.
> Add support for PostgreSQL as a DB storage back-end

- Gopkg.lock
- Gopkg.toml
- cache/bolt.go
- cache/bolt_test.go
- commands/discover.go
- config/config.go
- config/tomlloader.go
- report/cve_client.go
- report/slack.go
- report/tui.go
- scan/base.go
- scan/debian_test.go
- scan/executil.go
- util/logutil.go
This errors occurred.
```
grouped write of manifest, lock and vendor: error while writing out vendor tree: error while exporting github.com/sirupsen/logrus: /var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/.gitignore already exists, no checkout
/var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/.travis.yml already exists, no checkout
/var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/CHANGELOG.md already exists, no checkout
/var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/LICENSE already exists, no checkout
/var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/README. …
```
> change logrus package to lowercase and update other packages

- models/vulninfos.go
- scan/redhat.go
- scan/redhat_test.go
Extract the description of `yum --color=never --security updateinfo updates`, and put it into JSON.
```
===============================================================================
Amazon Linux AMI 2014.03 - ALAS-2016-720: medium priority package update for wget
===============================================================================
Update ID : ALAS-2016-720
Release :
Type : security
Status : final
Issued : 2016-07-14 16:30
CVEs : CVE-2016-4971
Description : Package updates are available for Amazon Linux AMI that fix the
: following vulnerabilities: CVE-2016-4971:
:         GNU wget before 1.18 allows remote servers
:         to write to arbitrary files by redirecting
:         a request from HTTP to a crafted FTP
:         resource. 1343666:
: CVE-2016-4971 wget: Lack of …
```
> Extract Advisory.Description on RHEL, Amazon, Oracle

- Gopkg.lock
- README.ja.md
- README.md
- commands/report.go
- config/config.go
- report/s3.go
I want to put to s3 with a specific directory name.
Add S3 directory option `-aws-s3-dir=/path/to/results's/parent`
```
$ vuls report -to-s3 -format-json -aws-region=ap-northeast-1 -aws-s3-bucket=vuls -aws-s3-dir=something/something -aws-profile=vuls
```
> add s3 dirctory option

- commands/tui.go
Closes #396, #439
At tui,  did not load config.toml.
I fixed it.
./vuls tui
> Fix to read config.toml at tui

- setup/docker/README.md
- setup/docker/goval-dictionary/latest/Dockerfile
- setup/docker/goval-dictionary/latest/README.md
Add oval docker settings
add dockerfile
```
$ for i in `seq 5 7`; do \
docker run --rm -it \
-v $PWD:/vuls \
-v $PWD/goval-dictionary-log:/var/log/vuls \
vuls/goval-dictionary fetch-redhat $i; \
done
```
> add oval docker

- commands/configtest.go
- commands/discover.go
- commands/report.go
- commands/scan.go
- commands/tui.go
- fix some typos in fixed strings.
- modified to use the correct domain for documents. (example.com)
none
read diff.
> fix typos in commands.

- report/tui.go
Sort ScanResults by servername, container-name
> Fix sort order of servers on TUI

- README.ja.md
- README.md
- scan/redhat.go
Add a check logic to CheckIfSudoNopasswd()
```
$ /vuls configtest --deep rhel
[Sep 14 08:48:40]  INFO [localhost] Validating config...
[Sep 14 08:48:40]  INFO [localhost] Detecting Server/Container OS...
[Sep 14 08:48:40]  INFO [localhost] Detecting OS of servers...
[Sep 14 08:48:47]  INFO [localhost] (1/1) Detected: rhel: redhat 7.2
[Sep 14 08:48:47]  INFO [localhost] Detecting OS of containers...
[Sep 14 08:48:47]  INFO [localhost] Checking dependencies...
[Sep 14 08:48:50]  INFO [rhel] Dependencies ... Pass
[Sep 14 08:48:50]  INFO [localhost] Checking sudo settings...
[Sep 14 08:48:50]  INFO [rhel] Checking... sudo yum --color=never repolist
[Sep 14 08:48:52]  INFO [rhel] Checking... sudo yum --color=never --security updateinfo list updates
[Sep 14 08:48:54]  INFO [rhel] Checking... …
```
> Check whether repoquery with sudo nopasswd in deep scan mode on RedHat

- setup/docker/vulsrepo/latest/Dockerfile
Change the config file name of vulsrepo.
Change docker file
docker run -dt -v $PWD:/vuls -p 5111:5111 vuls/vulsrepo
> fix vulsrepo dockerfile

- Gopkg.lock
- README.ja.md
- README.md
- config/config.go
- models/cvecontents.go
- models/vulninfos.go
- oval/suse.go
- oval/util.go
- report/report.go
- scan/redhat.go
- scan/serverapi.go
- scan/suse.go
- scan/suse_test.go
- scan/utils.go
- scan/utils_test.go
Support SUSE Enterprise Linux Server 11 and 12.
> Support SUSE Enterprise Linux

- Gopkg.lock
- README.ja.md
- README.md
- commands/report.go
- config/config.go
- models/scanresults.go
- models/scanresults_test.go
- report/report.go
Closes #485 
Add -ignore-unfixed to report subcommand
Run report with -ignore-unfixed
> Add -ignore-unfixed option to report subcommand #485

- README.md
- commands/tui.go
- report/report.go
- report/slack.go
- report/util.go
Add below options to TUI subcommand.
[-cvss-over=7]
[-ignore-unscored-cves]
[-ignore-unfixed]
> Add filter options to tui subcommand

- report/report.go
Refactoring.
pass cpename by args when calling FillCveInfo
see FillCveInfo
> pass cpename by args when calling FillCveInfo

- util/util.go
Closes #XXXXX
Just fix typo in comments
no need to verify,  just in comments
> fix typo from "enviroment" to "environment"

- scan/debian.go
- scan/executil.go
- scan/executil_test.go
Closes #519 
- Escaped the dollars with a backslash. 
- Swapped the double quotes and single quotes so that correctly executed.
```
$ bash -c 'dpkg-query -W -f="\${binary:Package},\${db:Status-Abbrev},\${Version},\${Source},\${source:Version}\n"'
$ dpkg-query -W -f="\${binary:Package},\${db:Status-Abbrev},\${Version},\${Source},\${source:Version}\n"
```
> Fix package query fails on debian based container (#519)

- .gitignore
- Gopkg.lock
- commands/report.go
- commands/tui.go
- oval/debian.go
- oval/oval.go
- oval/redhat.go
- oval/suse.go
- oval/util.go
- report/cve_client.go
- report/db_client.go
- report/report.go
- util/logutil.go
log output nothing without new log instance
unify and change the location where db instances are created
add init function in util.go
change the location of new db
1. vuls scan
2. vuls report 
> Refactor the DB connection creation to easy testing

- Gopkg.lock
- README.ja.md
- README.md
- config/config.go
- report/slack.go
Fix to send slack notification using API.
By using thread in API, slack message does not become chaos.
add function to send msg by api
- get slack legacy api token
https://api.slack.com/custom-integrations/legacy-tokens
-  add slack api token into config.toml
```
[slack]
#hookURL      = "https://hooks.slack.com/services/abc123/defghijklmnopqrstuvwxyz"
legacyToken =       "xoxp-11111111111-legacytoken-1111111111"
channel      = "#channel"
iconEmoji    = ":ghost:"
authUser     = "vuls"
notifyUsers  = ["@matsuno"]
```
- run vuls report
```
$ vuls report -to-slack -cvss-over=7
```
- result
> send slack msg by api

- README.ja.md
- README.md
- commands/discover.go
- config/config.go
- config/tomlloader.go
- report/report.go
- scan/pseudo.go
- scan/serverapi.go
Closes #512 
I added `type = "pseudo"` to config.toml setting.
Specify this when you want to detect vulnerability by specifying cpename without SSH connection.
The pseudo type does not do anything when scanning.
Search for NVD at report time and detect vulnerability of software specified as cpenamae.
```
[servers.s1]
cpeNames = ["cpe:/a:rubyonrails:ruby_on_rails:4.2.1"]
```
see also [Usage: Scan vulnerabilites of non-OS packages](https://github.com/future-architect/vuls#usage-scan-vulnerabilites-of-non-os-packages)
> Add pseudo server type for non-ssh scanning (only cpe scan) #512

- README.ja.md
- README.md
- scan/executil.go
- scan/executil_test.go
Solve the problem that RedHat's deep scan stops halfway.
https://github.com/future-architect/vuls/pull/495#issuecomment-341893414
- Do not add sudo to Piped command
In the current implementation, the command to be PIPE only existed in `yum changelog` in redhat.go
- Fix README
scan RedHat with --deep
> Insert `sudo` only at the beginning of command in deep scan #495

- oval/util.go
- oval/util_test.go
Closes #535 
Detect modified package versions of CentOS and Scientific with regular expressions.
Temporarily impersonate package version.
Run OvalMatch to the modified package.
https://wiki.centos.org/Manuals/ReleaseNotes/CentOS7#head-45636299c88753daf7f91aaabffeb2cdb64470ec
https://wiki.centos.org/Manuals/ReleaseNotes/CentOS6.9#head-8d5fecfca6aa658ed4f76d3cbe3d1526ea2bc735
> Fix: Misdetection of OvalMatch for CentOS and Scientific in oval/util.go

- commands/tui.go
- oval/redhat.go
- oval/util.go
- oval/util_test.go
Dirty Cow was miss-detected on RedHat based linux because RedHat7's  OVAL has below entry(DIRTY COW).
```
<definition class="patch" id="oval:com.redhat.rhsa:def:20170372" version="602">
...
<criterion comment="kernel is earlier than 0:4.5.0-15.2.1.el7" test_ref="oval:com.redhat.rhsa:tst:20170372013"/>
```
If the running kernel is 3 series, the version comparison would be wrong.
This CVE was also fixed in kernel 3 series.
https://access.redhat.com/errata/RHSA-2016:2098
```
kernel-3.10.0-327.36.3.el7.x86_64.rpm
```
So, if the major version of running kernel is different from oval's version, vuls ignore the oval entry.
see diff
```
yum -y update on CentOS7.
vuls scan 
vuls report
```
Confirm that the DIRTY COW is not detected.
***Is this ready …
> Fix false positive: ignore oval info when kernel major version is different

- scan/redhat.go
in README
```
vuls ALL=(ALL) NOPASSWD:/usr/bin/yum --color=never repolist, /usr/bin/yum --color=never --security updateinfo list updates, /usr/bin/yum --color=never --security updateinfo updates, /usr/bin/repoquery, /usr/bin/yum --color=never changelog all *
```
Scan with scan -skip-broken issues 
`
$ yum --color=never -skip-broken changelog all package-name 
`
It does not match the definition written in sudoers.
So I change the place to attach `yum changelog` option.
see the diff
scan with --deep, --skip-broken on redhat machine.
> Fix yum changelog option

- scan/suse.go
Closes #515
I replaced strings.HasPrefix call with strings.Index call for the lines returned by `zypper q -lu` as it seems that output contains some extra bytes, confusing HasPrefix.
I verified it by scanning a SLES 11 SP4 box.
***Is this ready for review?:*** yes  
> Replace strings.HasPrefix with strings.Index for SuSE scanner

- scan/redhat.go
- scan/utils.go
Closes #553 
Some commands do not use single quotes.
See #553
> Fix some RPM related commands failed in the container

- scan/redhat.go
Error handling of "Reboot Required" detection was strict.
If the return value is 0 and the string exists on the standard output, detection continues.
If the return value is 1, detection is omitted but no warning is issued.
In other cases (when the execution of the rpm command fails), an error occurs.
> Change error handling of "Reboot Required" detection

- README.ja.md
- README.md
- scan/base.go
- scan/executil.go
- scan/executil_test.go
LXC container support without LXD
Container type "lxc" has been added.
We assume an environment where LXD is not installed, so use "lxc-ls" command and "lxc-attach" command.
If old style settings are left in the container, warnings are inherently output to STDERR.
STDERR is redirected to "/dev/null" because it mixes with STDOUT during parsing.
Just like any other container (Docker and LXD), you need to connect to the host as root or a user with the required privileges.
It is possible to test in environments where "lxc-ls" and "lxc-attach" can be used.
I tested on Proxmox VE 5.1 (Debian 9 based virtualization host).
> LXC container support without LXD

- report/s3.go
Fix typo of error message when using "-to-s3" option.
fix typo.
you can confirm error message with: `vuls report -to-s3`
> fix typo in reports/s3.go

- oval/util.go
Closes #578 
see diff
report with -ovaldb-url
> Fix a bug of sending to closed socket while oval access via HTTP #578

- scan/redhat.go
Fix one of the causes (?) of #532 
**There are other causes as well.**
see diff
Please execute Deep Scan to "Oracle Linux 5.11" which executed "yum downgrade at".
> Fixed panic occurred when blank line continued in changelog

- commands/configtest.go
- commands/scan.go
- config/config.go
- models/packages.go
- scan/debian.go
- scan/redhat.go
Closes #561 
Add offline option to scan and configtest subcommand.
`./vuls scan` ... show the number of new version 
`./vuls scan -fast` ... show the number of new version
`./vuls scan -offline` ... Don't show the number of new version
> Add offline option to scan and configtest

- report/report.go
When executing report with an error in scanning, the following error message is output
```
[Feb 12 10:46:13] ERROR [localhost] Failed to fill OVAL information: OVAL for  is not implemented yet
```
Change to show a kindness message :)
```
[Feb 12 10:55:34] ERROR [localhost] Failed to fill OVAL information: Probably an error occurred during scanning. Check the error message
```
related
#598
#600
> fix: Kindness error message in reporting

- commands/report.go
- config/config.go
- report/s3.go
Support AWS S3 Server-Side Encryption
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html
Adding a new `-aws-s3-server-side-encryption` option which can be used to set the SSE method.
Publish reports to S3 with `-aws-s3-server-side-encryption=AES256`.
They should have the `Encryption` property set to `AES256`.
> Support AWS S3 Server-Side Encryption

- config/config.go
- models/scanresults.go
- scan/alpine.go
- scan/base.go
- scan/base_test.go
- scan/debian.go
- scan/freebsd.go
- scan/freebsd_test.go
- scan/pseudo.go
- scan/redhat.go
- scan/serverapi.go
- scan/unknownDistro.go
Add IP addresses of the scanned server to scan results.
Execute `ip addr` or `ifconfig` (depends on OS).
Skip loopback address or link-local address, etc.  (https://golang.org/pkg/net/#IP.IsGlobalUnicast)
Check JSON results after scan.
It will contain `IPv4Addrs` and `IPv6Addrs`.
***Is it a breaking change?:*** NO (Only add columns)
> Add IP address to scan results

- report/util.go
- scan/redhat.go
```
[Mar  6 14:01:39]  WARN [localhost] Failed to parse RedHat/CentOS version: %sexecResult: servername: mystifying_newton@c7idcf
cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none root@210.129.54.232 -p 7003 -i /Users/kota/.ssh/kanbe_idcf_id_rsa -o PasswordAuthentication=no stty cols 1000; docker exec --user 0 59bca0188fde /bin/sh -c 'cat /etc/redhat-release'
exitstatus: 0
stdout: Derived from Red Hat Enterprise Linux 7.1 (Source)
stderr:
err: %!s(<nil>)
```
support CentOS cloud image
https://bugzilla.redhat.com/show_bug.cgi?id=1332025
```
The cloud image is the standard CentOS image from
http://cloud.centos.org/centos/7/images/
They have split the release information out to …
```
> fix: support CentOS cloud image

- oval/redhat.go
- report/report.go
- report/util.go
- report/util_test.go
- Enable to report -diff for containers.
- Corrected false detection of diff
There was a possibility that a certain OVAL Def contains multipule CVEs, and if each lastModified is different, it may be false detected.
see diff
> fix: bug of report -diff option

- commands/report.go
- config/config.go
- config/tomlloader.go
- report/hipchat.go
- report/hipchat_test.go
> hipchat support

- report/hipchat.go
Closes #XXXXX
for example
https://nvd.nist.gov/vuln/detail\         ->          https://nvd.nist.gov/vuln/detail/CVE-2015-2328
vuls report -to-hipchat
> fix link nvd on hipchat

- scan/executil.go
To enables the sharing of multiple sessions over a single network connection to add controlmaster after host directive. 
https://www.cyberciti.biz/faq/linux-unix-reuse-openssh-connection/
https://en.wikibooks.org/wiki/OpenSSH/Cookbook/Multiplexing
netstat -an | grep 10.1
```
tcp4       0      0  192.168.11.6.63618     10.1.54.232.7003    ESTABLISHED
tcp4       0      0  192.168.11.6.63696     10.1.54.232.7003    TIME_WAIT
tcp4       0      0  192.168.11.6.63697     10.1.54.232.7003    TIME_WAIT
tcp4       0      0  192.168.11.6.63698     10.1.54.232.7003    TIME_WAIT
tcp4       0      0  192.168.11.6.63699     10.1.54.232.7003    TIME_WAIT
tcp4       0      0  192.168.11.6.63700     10.1.54.232.7003    TIME_WAIT
tcp4       0      0  192.168.11.6.63701     10.1.54.232.7003    TIME_WAIT …
```
> fix: SSH session multiplexing

- commands/scan.go
- config/config.go
- scan/executil.go
Add SSH -vvv option to scan subcommand.
It is useful for SSH connection trouble debugging.
> feat: Add -vvv option (SSH) to scan cmd

- Gopkg.lock
- Gopkg.toml
- commands/configtest.go
- commands/scan.go
- commands/util.go
- scan/executil.go
I added #616 
Bug, when scanning with Docker dontainer with the following command, an error occurrs.
```
docker run --rm \
>        -v ~/.ssh:/root/.ssh:ro \
>        -v $PWD:/vuls \
>        -v $PWD/vuls-log:/var/log/vuls \
>        -v /etc/localtime:/etc/localtime:ro \
>        -e "TZ=Asia/Tokyo" \
>        vuls/vuls scan \
>        -debug \
```
The reason is that vuls do not have write permission for ControlPath.
```
"-o", `ControlPath=~/.ssh/controlmaster-%r-%h.%p`,
```
https://github.com/future-architect/vuls/commit/50b105c4afda4064457ed7512747abd28ba9f935#diff-d2cd8aa61e6589e85271b9ab653d911fR279
Because Docker mount it as readonly as Docker Volume.
```
>        -v ~/.ssh:/root/.ssh:ro \
```
So Vuls create at the beginning of scan or configtest to $HOME/.Vuls and set SSH ControlPath …
> fix: change ControlPath to .vuls of SSH option

- scan/debian_test.go
Fix gofmt warn
Change indent.
```
$ gofmt -d -s scan/debian_test.go  
```
> fix(fmt): fix gofmt warn

- scan/executil.go
Closes #639
Use servername for SSH ControlPath filename
./vuls scan
> fix(scan): too long for Unix domain socket tmp file

- report/syslog.go
- report/syslog_test.go
Add `scanned_at` into syslog report.
Extract `ScannedAt` from `ScanResult`.
```
```
```
<129>2018-05-11T11:05:44+09:00 PC vuls[59729]: scanned_at="2018-05-11 10:58:40.381092554 +0900 JST" server_name="ubuntu1604" os_family="ubuntu" os_release="16.04" ipv4_addr="192.168.33.11" ipv6_addr="" packages="libncurses5,libncursesw5,libtinfo5,ncurses-base,ncurses-bin,ncurses-term" cve_id="CVE-2017-13731" severity="MEDIUM" cvss_score_v2="4.30" cvss_vector_v2="AV:N/AC:M/Au:N/C:N/I:N/A:P" cwe_id="CWE-119"
```
> Add scanned_at into syslog report

- report/syslog.go
- report/syslog_test.go
Send logs via syslog even if no CVE-IDs found.
If `messages` are empty slice, add `messages` to "No CVE-IDs are found".
```
```
```
$ nc -l 5140
<38>2018-05-16T12:41:42+09:00 iMac.local vuls[40916]: scanned_at="2018-05-16 12:35:14.625713325 +0900 JST" server_name="debian8" os_family="debian" os_release="8.10" ipv4_addr="10.0.2.15,192.168.33.16" ipv6_addr="" message="No CVE-IDs are found"
```
> Send logs via syslog when no CVE-IDs found

- scan/debian.go
`vuls configtest` was complaining about the official mysql image:  *reboot-notifier is not installed*.
Debian's `reboot-notifier`  packages depends on `gnome-packagekit` which I don't think it will be installed for any of the debian based docker images, so its safe to disable it.
config.toml
```
[servers]
port = "local"
[servers.localhost.containers]
includes = ["debian"]
````
```
docker run -d --rm --name=debian debian tail -f /dev/null`
vuls configtest -containers-only
```
> Don't check reboot-notifier package for debian containers

- setup/docker/go-cve-dictionary/latest/Dockerfile
- setup/docker/goval-dictionary/latest/Dockerfile
- setup/docker/vuls/latest/Dockerfile
- setup/docker/vulsrepo/latest/Dockerfile
Use alpine based images to reduce size.
Uncompressid sizes:
vulsrepo: from **66.8MB** to **15.8MB**
vuls: from **1.54GB** to **36.5MB**
goval-dictionary: from **967MB** to **23.6MB**
go-cve-dictionary: from **1.05GB** to **23.8MB**
Multistage builds with **golang:alpine** image
`docker build`
> Move to alpine based docker images

- setup/docker/vuls/latest/Dockerfile
Fix HTTP POST error for https webhooks
`vuls report -to-slack`
> Add missing ca-certificates, needed for slack webhook

- commands/configtest.go
- commands/scan.go
- config/config.go
- scan/executil.go
Closes #417 
add -ssh-config option to scan and configtest.
scan with -vvv option In order to check the option of SSH actually being executed.
> feat(scan): add -ssh-config option #417

- report/syslog.go
- report/syslog_test.go
Add title to syslog
Extract a title from `CveContents` of RedHat.
```
```
```
$ nc -l 514
<129>2018-06-05T16:15:42+09:00 MBP vuls[52919]: scanned_at="2018-06-05 14:40:05.611697546 +0900 JST" server_name="centos6" os_family="centos" os_release="6.9" ipv4_addr="10.0.2.15,192.168.33.10" ipv6_addr="" packages="procps" cve_id="CVE-2018-1126" cwe_id="" source_link="https://nvd.nist.gov/vuln/detail/CVE-2018-1126" summary="procps-ng before version 3.3.15 is vulnerable to an incorrect integer size in proc/alloc.* leading to truncation/integer overflow issues. This flaw is related to CVE-2018-1124." title="RHSA-2018:1777: procps security update (Important)"
```
***Is it a breaking …
> Add title to syslog

- models/vulninfos.go
Vuls displays the wrong CVSS scores.
```
CVE-2018-1111      10.0 CRITICAL (redhat) 
```
The correct score is `7.5`.
Alghough `10.0` is calculated by the severity, this score is used because it is higher than the actual score.
I fixed this bug.
Use `MaxCvssScore()` 
Scan RedHat OS.
```
$ vuls scan
...
CVE-2018-1111   7.5 CRITICAL (redhat)
...
```
> fix(report): use the CVSS score not calculated from severity preferentially

- report/syslog.go
- report/syslog_test.go
Add all CVSS scores (NVD, JVN, RedHat, etc.)
Iterate all CveContents
```
```
```
$ nc -l 514
<129>2018-06-06T20:44:11+09:00 MBP vuls[77805]: scanned_at="2018-06-06 16:19:18.923111854 +0900 JST" server_name="debian8" os_family="debian" os_release="8.10" ipv4_addr="10.0.2.15,192.168.33.11" ipv6_addr="" packages="linux-image-3.16.0-4-amd64" cve_id="CVE-2018-5750" cvss_score_nvd_v2="2.10" cvss_vector_nvd_v2="AV:L/AC:L/Au:N/C:P/I:N/A:N" cwe_id="CWE-200" source_link="https://nvd.nist.gov/vuln/detail/CVE-2018-5750" summary="The acpi_smbus_hc_add function in drivers/acpi/sbshc.c in the Linux kernel through 4.14.15 allows local users to obtain sensitive address information by reading dmesg data from an SBS HC printk call."
```
You don't have to satisfy all of the …
> feat(syslog): add all CVSS scores/vectors

- scan/suse.go
add fix to support SLES variant OS for SAP applicance, whose OS is SLES_SAP and verion is 12.1.0.1. 
Closes #671
add one condition for SLES_SAP, plus the verion checking for it 
modify any SLES, edit file /etc/os-release, change two lines
```
NAME="SLES_SAP"
VERSION_ID="12.1.0.1"
```
***Is this ready for review?:***  YES
> pull request to add SLES variant OS SLES_SAP support

- .travis.yml
- commands/report.go
- commands/server.go
- config/config.go
- main.go
- report/http.go
- scan/alpine.go
- scan/debian.go
- scan/freebsd.go
- scan/pseudo.go
- scan/redhatbase.go
- scan/redhatbase_test.go
- scan/serverapi.go
- scan/serverapi_test.go
- scan/unknownDistro.go
- server/server.go
Support server mode
Add server subcommand.
Support `application/json` and `text/plain`.
In the case of `text/plain`, `X-Vuls-OS-Family`, `X-Vuls-OS-Release` and `X-Vuls-Kernel-Release` headers are required.
Support OS: RHEL/CentOS/Debian/CentOS
```
$ vuls server -listen 0.0.0.0:5515
[Jul  5 22:32:46]  INFO [localhost] Validating config...
...
[Jul  5 22:32:46]  INFO [localhost] Listening on 0.0.0.0:5515
```
```
$ ssh vuls@centos6
$ curl -X POST -H "Content-Type: text/plain" -H "X-Vuls-OS-Family: `awk '{print tolower($1)}' /etc/redhat-release`" -H "X-Vuls-OS-Release: `awk '{print $3}' /etc/r
edhat-release`" -H "X-Vuls-Kernel-Release: `uname -r`" --data-binary "`rpm -qa --queryformat "%{NAME} %{EPOCHNUM} %{VERSION} %{RELEASE} %{ARCH}\n"`" http://192.168.33.1:5515/
```
```
$ cat centos6.json …
```
> feat(server): support server mode

- Gopkg.lock
- report/cve_client.go
> fix(report): database is locked with SQLite3 backend #681

- Gopkg.lock
- report/tui.go
fix an error of cpeNames matching
```
[Sep 13 12:38:24] ERROR [localhost] Failed to detect vulns of [cpe:/o:juniper:junos:10.1]: Malformed constraint:  <= 12.1x46:d72
```
for details, see 
https://github.com/kotakanbe/go-cve-dictionary/issues/97
https://github.com/kotakanbe/go-cve-dictionary/pull/98
> fix(cpe): update deps to avoid parsing err of cpeNames

- commands/report.go
Fix the following error.
- Error 
```
ERRO[0000] SQLite3 DB path (cvedb) must be a *Absolute* file path. -cvedb-path:
ERRO[0000] SQLite3 DB path (cvedb) is not exist:
```
- config.toml
```
[cveDict]
type = "mysql"
url = "database connection string"
[ovalDict]
type = "sqlite3"
path = "/path/to/oval.sqlite3"
[gost]
type = "mysql"
url = "database connection string"
```
> fix(report): fix an error while loading cveDict.type in config.toml

- report/azureblob.go
- report/localfile.go
- report/s3.go
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>
> report: simplify `x = x <op> y` to `x <op>= y`

- commands/util.go
If s is a slice, then `s[:]` is identical to just `s`.
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>
> commands: simplify `s[:]` to s

- gost/redhat.go
- gost/redhat_test.go
When CWE in gost is `CWE-665->(CWE-200|CWE-89)`
Vuls shows `cweID: "CWE-665->(CWE-200"` , `cweID: "CWE-89)"`
***Is this ready for review?:***YES
> fix(gost): a bug of parseCwe

- Gopkg.lock
- README.md
- commands/discover.go
- commands/report.go
- commands/tui.go
- config/config.go
- config/tomlloader.go
- exploit/exploit.go
- exploit/exploit_test.go
- exploit/util.go
- models/scanresults.go
- models/vulninfos.go
- report/db_client.go
- report/report.go
- report/tui.go
- report/util.go
add exploitdb
Using exploitdb, it was possible to check whether there is an exploit in cve detected by vuls
https://www.exploit-db.com/
https://github.com/mozqnet/go-exploitdb
> Display exploit codes information for each detected CVE-IDs

- Gopkg.lock
- Gopkg.toml
- commands/report.go
- commands/server.go
- commands/tui.go
- config/config.go
- exploit/exploit.go
- gost/debian.go
- gost/gost.go
- gost/redhat.go
- models/scanresults.go
- oval/alpine.go
- oval/debian.go
- oval/oval.go
- oval/redhat.go
- oval/suse.go
- report/cve_client.go
- report/db_client.go
- report/report.go
If you use go-cve-dictionary, goval-dictionary, gost, go-exploitdb as http server mode, type of each dictionary have to be defined `http`
config.toml
```
[cveDict]
type = "http"
url = "http://localhost:1323"
[ovalDict]
type = "http"
url = "http://localhost:1324"
[gost]
type = "http"
url = "http://localhost:1325"
[exploit]
type = "http"
url = "http://localhost:1326"
```
also add `http` to command line args.
Fixes #721
> fix(report): fix cvedb-url, add -cvedb-type=http

- scan/debian.go
- scan/debian_test.go
`apt policy` shows the repository name of updatable packages.
The repository name will be included to json result in -fast-root scan mode because it's necessary to refresh meta information by `apt-get update` with root privileges.
```
apt policy zsh
zsh:
Installed: 5.4.2-3ubuntu3
Candidate: 5.4.2-3ubuntu3
Version table:
*** 5.4.2-3ubuntu3 500
500 http://jp.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
100 /var/lib/dpkg/status
```
Tested on Ubuntu18, Debian 9.
> feat(scan): get repository name of updatable pkgs for debian/ubuntu

- models/vulninfos.go
fix(report): return both scores of gost and oval
`./vuls report` shows both CVSS scores of oval and gost.
> fix(report): return both scores of gost and oval

- GNUmakefile
The build time is now output when version is displayed with -v
I confirmed that it was built and displayed
```
$ ./vuls -v
vuls v0.6.1 20190118_040151_4b49e11
```
vuls <version> <build day> <build time> <commit hash>
> add build time

- models/scanresults.go
- scan/serverapi.go
add Scanner's IPv4 and IPv6 to ScanResults.
Run vuls scan locally, and I get following result:
```
...
"scannedAt":"2019-01-18T13:09:16.143774+09:00",
"scanMode":"fast mode",
"scannedVersion":"v0.6.1",
"scannedRevision":"4b49e11",
"scannedBy":"amachitomoyanoMacBook-puro.local",
"scannedIpv4Addrs":["192.168.1.12"],
"scannedIpv6Addrs":null,
...
```
> add ScannedIPv4Addrs and ScannedIPv6Addrs

- report/util.go
I deleted tab from output message of "No CVE-IDs are found in updatable packages.".
The reason for deleting is to include the output result of Vuls in JSON and become a parse error when registering to GitHub Issues.
If you need a tab, would you tell me the reason.
```
$ vuls report -ignore-unfixed -format-list -config=config.toml -cvss-over=8 | od -c
[Jan 24 14:46:16]  INFO [localhost] Validating config...
[Jan 24 14:46:16]  INFO [localhost] Loaded: /home/centos/work/vuls/results/2019-01-24T14:43:18Z
[Jan 24 14:46:16]  INFO [localhost] Validating db config...
INFO[0000] -cvedb-type: sqlite3, -cvedb-url: , -cvedb-path: /home/centos/cve.sqlite3 
INFO[0000] -ovaldb-type: sqlite3, -ovaldb-url: , -ovaldb-path: /home/centos/go/src/github.com/kotakanbe/goval-dictionary/oval.sqlite3 
INFO[0000] …
```
> Delete tab from output in case of No CVE-IDs

- Gopkg.lock
- commands/report.go
- config/config.go
- config/tomlloader.go
- github/github.go
- models/vulninfos.go
- report/report.go
- report/slack.go
- report/tui.go
- report/util.go
- server/server.go
GitHub tracks reported vulnerabilities in certain dependencies and provides security alerts to affected repositories. [GitHub Security Alerts](https://help.github.com/articles/about-security-alerts-for-vulnerable-dependencies/).
It becomes possible to import vulnerabilities detected by GitHub via GitHub 's API.
```
[servers.serverA]
user = "root"
host = "10.0.0.1"
port = "22"
keyPath = "/Users/kanbe/.ssh/id_rsa"
[servers.serverA.githubs."vulsdoc/vuls"]
token   = "xxxxYourTokenxxx"
```
To ignore vulnerabilities dismissed on GitHub,  Added `-ignore-github-dismissed` option to report subcommand.
```
$ ./vuls report -h                                                                                                 
report:
report
...
[-ignore-github-dismissed]
... …
```
> feat(report): GitHub security alerts integration

- models/cvecontents.go
Fixed simplest cases of append calls that have no
effect aside from driving Go static analysis tools crazy.
One issue remains (#784) since I'm not sure
what would be the right behavior there.
> models: fix no-op append calls

- report/email.go
- report/email_test.go
Fix for SMTP Servers without authentication
Support additional scenarios for -format-one-line-text
#719
#633 
Sent emails from both authenticated and not-authenticated SMTP Servers
vuls report -to-email
vuls report -to-email -format-one-email
vuls report -to-email -format-one-line-text -format-one-email
vuls report -to-email -format-one-line-text
> Handle no-auth SMTP Servers and one liner email fix

- Gopkg.lock
Fixes #793
Fixed a bug that could not be detected under certain conditions during CPE-based scanning.
Everyone using CPE based match should update Vuls to the latest version. There is no need to re-fetch DB, as it is guaranteed to be backward compatible.
For Details, see https://github.com/kotakanbe/go-cve-dictionary/pull/123/files
> fix(report): Critical Bug Fix for CPE based scanning #793

- commands/configtest.go
- commands/scan.go
I have changed the config.toml reference URL to https://vuls.io/docs/en/usage-settings.html as the mentioned one - https://github.com/future-architect/vuls#configuration - doesnt exist in Readme file
> Updated config.toml reference url

- models/vulninfos.go
- oval/debian.go
- oval/util.go
- oval/util_test.go
The key name of a kernel has been changed in OVAL for Ubuntu 18.
I fixed the detection logic.
`Not fixed yet` in a report is also fixed.
Use `not fixed yet` data in OVAL except for CentOS.
OVAL detection for CentOS uses RHEL's OVAL.
The patch provided status is different from CentOS and RHEL.
So,  the Version comparison(`new version` vs `fixed in version` in OVAL) is needed to judge `fixed` or `not fixed yet` for CentOS.
```
~/w/u18  ls                                                                                                                                        Thu May 23 16:45:23 2019
localhost.json     localhost.json.new
~/w/u18  diff * …
```
> fix(scan): a bug of kernel Vulns detection on Ubuntu18

- gost/redhat.go
see #827 
`./vuls report` with gostdb and check the results
> fix(report-redhat): fix false negative of `affected` vulns #827

- wordpress/wordpress.go
WPVULNDB API often says "429 Too Many Requests".
If vuls report got 429, sleep 1 min and try again. vuls report give up over 3 times retry.
NO
I tested in HEAD of master branch.
https://vuls-github.slack.com/archives/C0VTPKS3T/p1559186059012100
> fix(report): WordPress(WPVULNDB API) 429 Too Many Requests

- server/server.go
The report of vuls server (running with `-to-localfile -format-json`) will always have the `scannedAt` attribute as `0001-01-01T00:00:00Z`. There is an explicit check for the value in the parameter before creation of directory - if the value equals `time.IsZero()` then the directory name is set to the current time. However, the `scannedAt` time in the report stays the same as before. 
https://github.com/future-architect/vuls/blob/master/server/server.go#L83-L98
When parsing the local json files of scanned hosts, the timestamp of all the servers remains as `0001-01-01T00:00:00Z`. 
In the PR, I have changed the `scannedAt` attribute in the report to current time so that the json files contain the correct time of scan. 
`make test`
```
?   	github.com/future-architect/vuls	[no test files]
? …
```
> Changing the scannedAt time in the original result

- go.mod
Updated `go.mod` to use valid version of goval-dictionary -- v0.1.3-0.20190613053258-078b163b76ec
Fixes #838
make install
make test
***Is this ready for review?:*** Yes
> update goval-dictionary dependency to valid version

- scan/serverapi.go
Supported AmazonLinux for server mode. Content-Type "application/json" was already implemented.
I implemented Content-Type "plain / text".
```
$ ./vuls server -listen 0.0.0.0:5515 -to-localfile -format-json
$ docker run -it --rm amazonlinux:2016.09.0.20161028  /bin/bash
$ curl -X POST -H "X-Vuls-Server-Name: local" -H "Content-Type: text/plain" -H "X-Vuls-OS-Family: amazon" -H "X-Vuls-OS-Release: 2 (Karoo)" -H "X-Vuls-Kernel-Release: 4.9.125-linuxkit" --data-binary "`rpm -qa --queryformat "%{NAME} %{EPOCHNUM} %{VERSION} %{RELEASE} %{ARCH}\n"`"  http://${HOST_IP}:5515/vuls
$ docker run -it --rm amazonlinux:2.0.20190508  /bin/bash
$ curl -X POST -H "X-Vuls-Server-Name: local" -H "Content-Type: text/plain" -H "X-Vuls-OS-Family: amazon" -H …
```
> Supported AmazonLinux for server mode

- commands/server.go
Changes that don't require config.toml in server mode.
Change default value of configPath to blank.
```
$ vuls server -ovaldb-type=redis -ovaldb-url=redis://localhost:6379 -cvedb-type=redis -cvedb-url=redis://localhost:6379
[Jun 26 14:34:37] ERROR [localhost] Error loading /vuls/config.toml. err: open /vuls/config.toml: no such file or directory
```
```
$ vuls server -ovaldb-type=redis -ovaldb-url=redis://localhost:6379 -cvedb-type=redis -cvedb-url=redis://localhost:6379
[Jun 26 14:35:32]  INFO [localhost] Validating config...
[Jun 26 14:35:32]  INFO [localhost] Validating db config...
INFO[0000] -cvedb-type: redis, -cvedb-url: redis://localhost:6379, -cvedb-path:
INFO[0000] -ovaldb-type: redis, -ovaldb-url: redis://localhost:6379, -ovaldb-path:
INFO[0000] -gostdb-type: sqlite3, …
```
> Changes that don't require config.toml in server mode

- commands/server.go
- server/server.go
I fixed the bug of race condition in vuls server-mode.
The server-mode runs report.NewDBClient only once the first time.
NewDBClient returns multiple DBs.
At this time, internally execute github.com/kotakanbe/go-cve-dictionary/db.NewDB which returns driver.
After this, The server-mode always execute functions such as NewOvalDB for the same driver .
This driver has the family property (e.g. d. Ovaldb).
After that, server-mode always executes functions like NewOvalDB for the same driver.
So, when a request from different OS is made asynchronously, ovaldb is rewritten.
I added below log in goval-dictionary/db/redis.go. 
```
func (d *RedisDriver) NewOvalDB(family string) error {
fmt.Println("Call NewOvalDB")
fmt.Printf("Pre NewOvalDB: %s\n", family)
switch family {
case c.CentOS:
d.ovaldb = …
```
> Fix race condition in server-mode

- commands/scan.go
- config/config.go
- scan/base.go
Add `-ips` option to scan cmd. 
This option retrieve ips's server information.
> Add ips flag to scan

- scan/base.go
#What did you implement:
Avoid warning
```
[Jul  6 10:10:13]  WARN [localhost] Warning: Some warnings occurred while scanning on localhost: [Failed to dpkg-ps:
github.com/future-architect/vuls/scan.(*debian).postScan
/root/go/src/github.com/future-architect/vuls/scan/debian.go:270
- Failed to ls of:
github.com/future-architect/vuls/scan.(*debian).dpkgPs
/root/go/src/github.com/future-architect/vuls/scan/debian.go:1159
- Failed to SSH: execResult: servername: 
cmd: lsof -i -P -n | grep LISTEN
exitstatus: 1
stdout: 
stderr: 
err: exit status 1:
github.com/future-architect/vuls/scan.(*base).lsOfListen
/root/go/src/github.com/future-architect/vuls/scan/base.go:793 Failed to scan need-restarting processes:
github.com/future-architect/vuls/scan.(*debian).postScan …
```
> fix(scan): allow exit 1 for no match `lsof | grep`

- scan/base.go
Sometimes WordPress processes are running as root user on docker based wordpress site.
wp command warns below when run as root user.
```
root@6ec65aaa6dff:/var/www/html# /usr/local/bin/wp plugin list --path=/var/www/html  -allow-root
Error: YIKES! It looks like you're running this as root. You probably meant to run this as the user that your WordPress installation exists under.
If you REALLY mean to run this as root, we won't stop you, but just bear in mind that any code on this site will then have full control of your server, making it quite DANGEROUS.
If you'd like to continue as root, please run this again, adding this flag:  --allow-root
If you'd like to run it as the user that this site is under, you can run the following to become the respective user:
sudo -u USER -i -- wp <command> …
```
> fix(wordpress): add --allow-root to wp cmd for docker based wp

- commands/server.go
- go.mod
- go.sum
- oval/redhat.go
- oval/util.go
- server/server.go
1. Fix performance. 
Fix the performance degradation introduced by this PR.
https://github.com/future-architect/vuls/pull/857
This PR needs to update go.mod after https://github.com/kotakanbe/goval-dictionary/pull/73/ is merged.
2. Fix bug
```
[Jul  9 19:24:18]  INFO [localhost] : 0 CVEs are detected with Library
[Jul  9 19:24:18]  INFO [localhost] OVAL is fresh: redhat 6.5-x86_64
2019/07/09 19:24:18 http: panic serving 127.0.0.1:55532: runtime error: index out of range
goroutine 154 [running]:
net/http.(*conn).serve.func1(0xc000860000)
/usr/local/Cellar/go/1.12.4/libexec/src/net/http/server.go:1769 +0x139
panic(0x51c10e0, 0x64e2980)
/usr/local/Cellar/go/1.12.4/libexec/src/runtime/panic.go:522 +0x1b5 …
```
> Fix performance and bug

- scan/redhatbase.go
This patch fixed yum makecache gpg check to skip which unuse --nopgpcheck, use --assumeyes.
> fix centos yum makecache --assumeyes

- commands/report.go
- config/config.go
- report/util.go
- util/logutil.go
When there are one or more warnings during the scan, they appear in the report especially in the file "summary.txt" (with the option "-to-localfile").
I want to parse the content of this file to process the scan result. With warnings the parsing is more complicated. Furthermore errors and warnings appear in the logs.
We keep track of the errors and warnings with the command scan, but we could remove them from the command report.
So I added an option -quiet to force logging to a file instead of stdout.
In my case warnings appear when I scan a debian container because checkrestart ins't available (for example). Use -quiet option when there are warnings during your scan, with the option -to-localfile and you would see that there aren't warnings in …
> No warning(s) in the output file with report command (quiet mode)

- scan/serverapi.go
Only divide `scanVuln` into `GetScanResults` and `writeScanResults`
I got the same result before and after.
> scanVuln => GetScanResults and writeScanResults

- commands/scan.go
- config/config.go
- go.mod
- go.sum
- models/library.go
- report/slack.go
- scan/base_test.go
- scan/container.go
- scan/serverapi.go
https://vuls.io/docs/en/usage-scan-non-os-packages.html#options
https://vuls.io/docs/en/usage-scan-wordpress.html#scan-wordpress-core-plugin-theme
```
$ ./vuls scan -h
scan:
scan
[-config=/path/to/config.toml]
[-results-dir=/path/to/results]
[-log-dir=/path/to/log]
[-cachedb-path=/path/to/cache.db]
[-ssh-native-insecure]
[-ssh-config]
[-containers-only]
[-images-only]
[-libs-only]
[-skip-broken]
[-http-proxy=http://192.168.0.1:8080]
[-ask-key-password]
[-timeout=300]
[-timeout-scan=7200]
[-debug]
[-pipe]
[-vvv]
[-ips]
[SERVER]...
-ask-key-password
Ask ssh privatekey password before scanning
-cachedb-path string
/path/to/cache.db (local cache of changelog for Ubuntu/Debian) (default "/home/ubuntu/go/src/github.com/future-architect/vuls/cache.db")
-config string
/path/to/toml (default …
```
> feat(scan): add -wordpress-only and -libs-only flag

- models/vulninfos.go
- models/vulninfos_test.go
- report/tui.go
- report/util.go
- CVE-ID
- CVSS Score
- CVSS Attack Vector
- POC
- US-CERT/JP-CERT
- Fixed
- Pkgs
- CVE-ID
- CVSS Score
- CVSS Attack Vector
- POC
- US-CERT/JP-CERT
- Fixed
- NVD Link
./vuls report
./vuls tui
> fix(report): show POC, CERT in tui and format-list. use vendor summary over NVD

- scan/base.go
vuls scan failed that wordpress site includes poor theme/plugin.
when wp-cli output stderr, vuls scan can't get only json messages. 
Fixes #825 
I checked to ignore the following messages.
```
Unable to open /SITE1/wordpress/wp-content/wflogs/ips.php for reading and writing.
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'goyahso_change_post_object' not found or invalid function name in /SITE1/wordpress/wp-includes/class-wp-hook.php on line 286
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'goyahso_change_post_object' not found or invalid function name in …
```
> fix(scan): ignore wp-cli stderr messages (#825)

- gost/base.go
- gost/debian.go
- gost/gost.go
- gost/microsoft.go
- gost/pseudo.go
- gost/redhat.go
- report/report.go
- scan/base.go
In the current implementation, Vuls fills Red Hat CVE data when the scan target server is RHEL or CentOS. But Red Hat CVE Data is useful for other distros, This P/R fills it on all distros. 
tested on Amazon Linux, CentOS.
> Fill Red Hat CVE data for all distros

- config/config.go
Vuls scan checks ResultsDir Path twice.
I execute vuls scan at latest version(v0.9.1 d6e74cc).
```
$ vuls -v
vuls v0.9.1 build-20191209_233537_d6e74cc
$ vuls scan -results-dir=vuls
[Dec  9 22:40:35]  INFO [localhost] Start scanning
[Dec  9 22:40:35]  INFO [localhost] config: /Users/vuls/config.toml
[Dec  9 22:40:35]  INFO [localhost] Validating config...
ERRO[0000] JSON base directory must be a *Absolute* file path. -results-dir: vuls 
ERRO[0000] JSON base directory must be a *Absolute* file path. -results-dir: vuls
$
```
I execute vuls scan at fixed version(2cdb7bf).
```
$ vuls -v
vuls v0.9.1 build-20191209_234102_2cdb7bf
$ vuls scan …
```
> fix(config): fix double checking ResultsDir Path

- models/vulninfos.go
- models/vulninfos_test.go
- oval/redhat.go
- oval/redhat_test.go
- scan/debian_test.go
Fixes #930 
Scan and report Cent7 with the latest OVAL and check if CVSS vector string is not empty string.
> fix(report): Support CVSS 3.1 for Red Hat OVAL #930

- contrib/owasp-dependency-check/parser/parser.go
Fixes https://github.com/future-architect/vuls/issues/935
Vuls's Dependency Check parser supports for latest Dependency Check. 
Older Dependency Check does not work due to [NVD XML feed retirement](https://nvd.nist.gov/General/News/XML-Vulnerability-Feed-Retirement).
Newer Dependency Check works fine.
But, Vuls supports only older versions of Dependency Check XML schema.
Latest Dependency Check schema is changed from older version to dependency-check.2.3.xsd.
ref https://github.com/jeremylong/DependencyCheck/tree/master/core/src/main/resources/schema
Run OWASP Dependency Check CLI v5.3.0 with [resources include vuln](https://github.com/jeremylong/DependencyCheck/tree/master/core/src/test/resources).
```
dependency-check.sh --format XML --scan …
```
> Support Dependency Check v5.3.0

- config/config.go
- config/tomlloader.go
- config/tomlloader_test.go
- models/scanresults.go
- report/report.go
- scan/base.go
- scan/container.go
- scan/serverapi.go
Scan container images with the digest.
Fixes #937
1. create config.toml
```
[servers.image]
type="pseudo"
[servers.image.images.withdanger]
name="meteogroup/concourse-version-resource"
digest="sha256:4213898e8aaa12d0f71875190fb123690ae9df18b30e5d959b36a4071738bc89"
```
2. vuls scan, reoprt and tui
> feat : scan with image digest

- models/scanresults.go
Fix typo in models/scanresults.go
```
extention -> extension
````
> Fix typo in models/scanresults.go

- scan/centos.go
Fixes #946 
```
$ vuls configtest -ssh-config centos8
[Apr  2 12:34:56]  INFO [localhost] Validating config...
[Apr  2 12:34:56]  INFO [localhost] Detecting Server/Container OS... 
[Apr  2 12:34:56]  INFO [localhost] Detecting OS of servers... 
[Apr  2 12:34:56]  INFO [localhost] (1/1) Detected: centos8: centos 8.1.1911
[Apr  2 12:34:56]  INFO [localhost] Detecting OS of static containers... 
[Apr  2 12:34:56]  INFO [localhost] Detecting OS of containers... 
[Apr  2 12:34:56]  INFO [localhost] Checking Scan Modes...
[Apr  2 12:34:56]  INFO …
```
> fix CentOS8 configtest always failed

- models/vulninfos.go
Fixes #820
- before
- after
- before
-after
> feat(report): display "fixed" when updatable even in fast mode

- oval/debian.go
OVAL for Ubuntu has been changed. The kernel used to be described as `linux-image-*`, but the `-image-` has been removed. ex: changed `linux-image-aws` to `linux-aws`.
For this reason, the detection logic was changed.
Tested on Ubuntu 18.04, 16.04
> fix(report): kernel vulns detection BUG in Ubuntu

- go.mod
- go.sum
> fix(config): not working with empty config #962

- github/github.go
GItHub Security alerts API v4 has been changed.
- OLD
```
query { repository(owner:"kotakanbe", name:"tets") { url, vulnerabilityAlerts(first: 100) { pageInfo{ endCursor, hasNextPage, startCursor}, edges { node { id, externalIdentifier, externalReference, fixedIn, packageName,  dismissReason, dismissedAt } } } } }
```
- Error Msg
```
[Apr 28 13:43:06] ERROR [localhost] Failed to fill with integration: Failed to access GitHub Security Alerts: Failed to access to GitHub API. Response: {"errors":[{"path":["query","repository","vulnerabilityAlerts","edges","node","externalIdentifier"],"extensions":{"code":"undefinedField","typeName":"RepositoryVulnerabilityAlert","fieldName":"externalIdentifier"},"locations":[{"line":1,"column":162}],"message":"Field 'externalIdentifier' doesn't exist on type …
```
> fix(report): GitHub Security Alerts Integration

- models/library.go
find composer.lock files instead of composer.json as the trivy analyzer expects
https://github.com/future-architect/vuls/issues/972
Add composer.lock file with phpwhois 4.2.2 and verify we see CVE-2015-5243 in the output
> composer.lock instaad of composer.json

- go.mod
- go.sum
- oval/util.go
Fixes #965 
https://github.com/future-architect/vuls/issues/965#issuecomment-619691585
> fix(scan): alpine detection #965

- oval/debian.go
The purpose of this pull request is to provide support for Ubuntu20.04.
fixes #952 
【debian.go】
- Add case ubuntu20
- Add kernel names on ubuntu20.04 from OVAL data
- OVAL data for Ubuntu20.04
https://people.canonical.com/~ubuntu-security/oval/oci.com.ubuntu.focal.cve.oval.xml.bz2
- Using ```vuls scan``` 
- Using ```vuls report```
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#952: Support Ubuntu 20.04](https://issuehunt.io/repos/54808920/issues/952)
---
</details>
> Supported Ubuntu20.04

- report/email.go
The purpose of this pull request is to provide support for SMTPS when use ```report -to-email```.
Fixes #945 
【report/email.go】
When ```vuls report -to-email``` using port465(SMTPS), smtp client use TLS connection.
Setting config.toml to use port465
```text
[email]
smtpAddr      = "smtp.xxx.xxx.com"
smtpPort      = "465"
user          = "xxxx"
password      = "xxxxxxx"
from          = "xxxx@xxxx.com"
to            = ["xxxx@xxxx.com"]
subjectPrefix = "[vuls]" 
```
* https://golang.org/pkg/net/smtp/
* https://gist.github.com/chrisgillis/10888032
> Support SMTPS when using report -to-email 

- report/report.go
- server/server.go
- wordpress/wordpress.go
- wordpress/wordpress_test.go
I implemented Cache WpVulnDB.
It reduces access to wpvulndb by caching .
What makes we happy when I add this.
If you use multiple WordPress scans, you can reduce API calls by the same core, plugins and themes.
I tested wordpresses in action.
The request for one server result was the same as the request for two replicated servers results.
> feat(wordpress): Cache WpVulnDB

- server/server.go
Added ReportedAt time for reports submitted from client while server is running in `server` mode. I know that there is already a PR (https://github.com/future-architect/vuls/pull/938) open for this, but it doesn't look like it's in progress and this is a fix that is impacting my use of Vuls. I can be active and make changes if requested, please let me know. 
Fixes #928 
Yes, see verification steps at the end of the PR
there is an open pull request, but it doesn't look active: https://github.com/future-architect/vuls/pull/938
- Create `data.json` file in your current directoy
```json
{
"family": "centos",
"release": "6.9",
"runningKernel": {
"release": …
```
> Added ReportedAt time for server mode reports - fixes #928

- commands/configtest.go
- commands/discover.go
- commands/scan.go
- config/config.go
- config/tomlloader.go
- scan/executil.go
Use the SSH `-F` option to avoid the bug that `.ssh/config` causes an error depending on the owner setting. Also, the command line option: `-ssh-config` has been deprecated.
Fixes #986 
As stated in the issue, I confirmed by executing `scan.sh` of vulsctl.
I used a docker container as the scan destination.
- vulsctl → Docker (Ubuntu20.04)
```terminal
vulsctl on master
❯ cat config.toml
[servers]
[servers.ubuntu]
host = "172.17.0.2"
port = "22"
user = "root"
sshConfigPath = "/root/.ssh/config"
keyPath = "/root/.ssh/id_rsa"
vulsctl on master
❯ ./scan.sh
[Jun 14 16:07:53]  INFO [localhost] Validating config...
[Jun 14 16:07:53]  INFO [localhost] Detecting Server/Container OS...
[Jun 14 16:07:53]  INFO [localhost] Detecting OS of servers...
[Jun 14 …
```
> Fix SSH failure due to .ssh/config owner

- config/config.go
- config/tomlloader.go
- go.mod
- scan/executil.go
The purpose of this pull request is to provide support for ProxyJump option.
Fixes #987 
- [*] New feature (non-breaking change which adds functionality)
When running ```vuls scan --debug -vvv```, I can confirm output ```ssh -J test@test.com:22,test@test1.com:2222 targetmachine```.
Add ProxyJump setting to the Severs section of config.toml.
For example, ```ProxyJump=["user@(hostname or IPaddress):port"]```
【config.toml】
```text
[servers]
[servers.ubuntu]
host         = ""
port        = ""
user        = ""
keyPath     = ""
jumpServer = ["test@test.com:22", "test@test1.com:2222"]
```
If we don't run ProxyJump option, please check **.vuls** directory.
The control master may be the cause.
> Support ProxyJump option when using ssh command 

- commands/configtest.go
- commands/report.go
- commands/scan.go
- commands/server.go
- commands/tui.go
- scan/executil.go
- util/logutil.go
before 
```
ubuntu@dev  ~│g│s│g│f│vuls  ⎇ master…~  ./vuls scan c7
2020/07/31 16:47:37 failed to open logfile: /var/log/vuls/localhost.log open /var/log/vuls/localhost.log: permission denied
Failed to fire hook: open /var/log/vuls/localhost.log: permission denied
[Jul 31 16:47:37]  INFO [localhost] Start scanning
2020/07/31 16:47:37 failed to open logfile: /var/log/vuls/localhost.log open /var/log/vuls/localhost.log: permission denied
Failed to fire hook: open /var/log/vuls/localhost.log: permission denied
[Jul 31 16:47:37]  INFO [localhost] config: /home/ubuntu/go/src/github.com/future-architect/vuls/config.toml
2020/07/31 16:47:37 failed to open logfile: /var/log/vuls/localhost.log open /var/log/vuls/localhost.log: permission denied
Failed to fire hook: open /var/log/vuls/localhost.log: …
```
> fix(log): suppress err msg if no access priv to logfile

- config/config.go
- config/config_test.go
- gost/debian.go
- gost/debian_test.go
- oval/util_test.go
suppress err logging when unsupported debian
> fix(gost): suppress err logging when unsupported debian

- oval/redhat.go
- scan/redhatbase.go
- scan/redhatbase_test.go
- scan/utils.go
Vuls only detects vulnerabilities in the running kernel if multiple versions of the kernel are installed.
kernel-devel can also install several different versions on the OS like `kernel`.
Collect the kernel-devel corresponding to the running kernel.
Running kernel
```
ubuntu@dev  ~│g│s│g│f│vuls  ⎇ master~  uname -a
Linux dev 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linu
```
kernel devel
```
[ec2-user@ip-192-168-0-80 ~]$ rpm -qa | grep kernel-devel
kernel-devel-3.10.0-1062.1.2.el7.x86_64
kernel-devel-3.10.0-1127.19.1.el7.x86_64
```
before
```
"kernel": {
"name": "kernel",
"version": "3.10.0",
"release": "1062.1.2.el7",
"newVersion": "",
"newRelease": "",
"arch": "x86_64",
"repository": "",
"changelog": {
"contents": "",
"method": ""
}
}, …
```
> [WIP]fix(scan): collect a `running` version of kernel-devel

- scan/alpine.go
Avoided the error when scanning alpine linux before apk update.
The reason why the error occurred is that the command ``apk info -v'' outputs ``WARNING: Ignoring APKINDEX.2c4ac24e.tar.gz: No such file or directory''. 
Fixes #1045 
- [*] Bug fix (non-breaking change which fixes an issue)
I confirmed that the scan was completed successfully on alpine linux before running apk update.
> Ignore apk warning when scanning alpine linux before apk update

- scan/base.go
Fixes future-architect/vuls#1055.
When find throws an error, it prefixes an error with the utility name,
(`find` by default), the quoted path where find encountered the error,
and the specific error message.
As it stands now, vuls only filters out the 'Permission Denied' message.
Informal testing in a Ubuntu system found other errors from the procfs
pseudo-filesystem. So this fix will filter out all error messages, as find
is only used to lock for language runtime dependency lockfiles, and
nothing else.
Please describe the tests that you ran to …
> Expand negative grep match for any error for lib scans.

- config/config.go
Fixes #1057 
I forget to increment the version number of Vuls every time :)
The version number is injected at make time, so I'll put the initial values in text.
https://github.com/future-architect/vuls/blob/master/GNUmakefile#L17-L21
```
ubuntu@dev  ~│g│s│g│f│vuls  ⎇ version~  go build 
ubuntu@dev  ~│g│s│g│f│vuls  ⎇ version~  ./vuls -v
vuls `make build` or `make install` will show the version 
```
```
ubuntu@dev  ~│g│s│g│f│vuls  ⎇ version~  make build
...
ubuntu@dev  ~│g│s│g│f│vuls  ⎇ version~  ./vuls -v
vuls v0.12.3 build-20201012_135526_858beab
```
> fix: hard-coded version #1057

- scan/base.go
- scan/base_test.go
- scan/debian.go
- scan/redhatbase.go
AffectedProcs was missing when an error occurred on `rpm -qa`.
Also, fixed a bug of port listening in the case of multiple processes listening to the same port.
> fix(fast-root): affectedProcs, litening ports bug

- commands/report.go
- config/config.go
- report/localfile.go
- report/stdout.go
- report/util.go
Hello,
I added "CSV" support.
Currently only supports normal output.
In the future, full format will be supported.
Fixes #1018
```
root@karas:~# vuls scan
[Aug 15 12:50:58]  INFO [localhost] Start scanning
[Aug 15 12:50:58]  INFO [localhost] config: /root/config.toml
[Aug 15 12:50:58]  INFO [localhost] Validating config...
[Aug 15 12:50:58]  INFO [localhost] Detecting Server/Container OS...
[Aug 15 12:50:58]  INFO [localhost] Detecting OS of servers...
[Aug 15 12:50:58]  INFO [localhost] (1/1) Detected: localhost: ubuntu 18.04
[Aug 15 12:50:58]  INFO [localhost] Detecting OS of containers...
[Aug 15 12:50:58]  INFO [localhost] Checking Scan Modes...
[Aug 15 …
```
> add(report) -format-csv option

- models/packages.go
- models/packages_test.go
- report/report.go
- report/tui.go
- report/util.go
- scan/base.go
- scan/base_test.go
- scan/debian.go
- scan/redhatbase.go
Enable reporting of scan results by Vuls v0.13.0 and earlier in the latest version of Vuls.
In the current implementation, an error occurred.
- scan vuls (before v0.13.0)
- vuls report
```
ubuntu@dev  ~│g│s│g│f│vuls  ⎇ master~  ./vuls.master  tui
[Nov 19 16:11:44] ERROR Failed to create log file. path: /var/log/vuls/localhost.log, err: open /var/log/vuls/localhost.log: permission denied
[Nov 19 16:11:44]  INFO [localhost] Validating config...
INFO[0000] -cvedb-type: sqlite3, -cvedb-url: , -cvedb-path: /home/ubuntu/go/src/github.com/kotakanbe/go-cve-dictionary/cve.sqlite3 
[Nov 19 16:11:44] ERROR [localhost] Failed to parse /home/ubuntu/go/src/github.com/future-architect/vuls/results/2020-11-19T16:11:02+09:00/localhost.json: json: cannot unmarshal string into Go struct field …
```
> fix(portscan): to keep backward compatibility before v0.13.0

- scan/serverapi.go
refs #1071 
Changed to also clear when scanning.
Run the scan in the following config.toml, and make sure that the key is not included in the json.
```
port = "local"
user = "vuls"
ignoredJSONKeys = [
"scannedIpv4Addrs",
"ipv4Addrs",
]
```
```
ubuntu@dev  ~│g│s│g│f│vuls  ⎇ ignore-json-keys-scan~  less results/current/localhost.json | jq "." | grep -3 "ipv4Addrs"
"wordpress": {},
"ignoredJSONKeys": [
"scannedIpv4Addrs",
"ipv4Addrs"
]
}
},
ubuntu@dev  ~│g│s│g│f│vuls  ⎇ ignore-json-keys-scan~  less results/current/localhost.json | jq "." | grep -3 "scannedIpv4Addrs"
],
"wordpress": {},
"ignoredJSONKeys": [
"scannedIpv4Addrs",
"ipv4Addrs"
]
}
```
> feat(scan): IgnoredJSONKyes to clear values in result json #1071

- models/vulninfos.go
- report/util.go
- wordpress/wordpress.go
vuls report skip wpvulndb poor versioning data
Fixes #1088 
- vuls report skip wpvulndb poor versioning data
- replace from wpvulndb.com to wpscan.com
```
[vuls@vuls ~]$ vuls report -debug -ignore-unscored-cves -lang=ja -cvss-over=7 -to-email -format-full-text
:snip
[Dec 10 13:17:50] DEBUG [localhost] https://wpscan.com/api/v3/plugins/search-regex
[Dec 10 13:17:50] DEBUG [localhost] https://wpscan.com/api/v3/plugins/tinymce-advanced
[Dec 10 13:17:50]  INFO [localhost] [match] tinymce-advanced installed: 4.1.9, fixedIn: 4.2.3
[Dec 10 13:17:50] DEBUG …
```
> fix(report): wpvulndb poor versioning(#1088)

- gost/debian.go
- gost/debian_test.go
- models/packages.go
- models/scanresults.go
- models/vulninfos_test.go
- oval/oval.go
- oval/util_test.go
- report/report.go
- scan/base.go
- scan/serverapi.go
```
/home/ubuntu/go/src/github.com/future-architect/vuls/gost/debian.go:26:1: exported method Debian.Supported should have comment or be unexported
/home/ubuntu/go/src/github.com/future-architect/vuls/models/packages.go:190:1: exported function NewPortStat should have comment or be unexported
/home/ubuntu/go/src/github.com/future-architect/vuls/models/scanresults.go:508:1: exported method ScanResult.ClearFields should have comment or be unexported
/home/ubuntu/go/src/github.com/future-architect/vuls/report/report.go:394:1: exported function DetectCpeURIsCves should have comment or be unexported
/home/ubuntu/go/src/github.com/future-architect/vuls/scan/base.go:601:6: exported type DummyFileInfo should have comment or be unexported …
```
> refactor: fix build warnings, typos

- .github/workflows/tidy.yml
- .goreleaser.yml
Place the vuls-scanner binary on the release page when pushing tags.
https://github.com/future-architect/vuls/releases
Make binaries for multiple architectures.
- 386
- amd64
- arm
- arm64
The vuls-scanner binary does not include the report function.
> feat(scanner): vuls-scanner binary on release archive

- GNUmakefile
- subcmds/report.go
- subcmds/server.go
- subcmds/tui.go
Remove the below options and use config.toml.
```
./vuls server -h
Server:
Server
...
[-cvedb-type=sqlite3|mysql|postgres|redis|http]
[-cvedb-sqlite3-path=/path/to/cve.sqlite3]
[-cvedb-url=http://127.0.0.1:1323 or DB connection string]
[-ovaldb-type=sqlite3|mysql|redis|http]
[-ovaldb-sqlite3-path=/path/to/oval.sqlite3]
[-ovaldb-url=http://127.0.0.1:1324 or DB connection string]
[-gostdb-type=sqlite3|mysql|redis|http]
[-gostdb-sqlite3-path=/path/to/gost.sqlite3]
[-gostdb-url=http://127.0.0.1:1325 or DB connection string]
[-exploitdb-type=sqlite3|mysql|redis|http]
[-exploitdb-sqlite3-path=/path/to/exploitdb.sqlite3]
[-exploitdb-url=http://127.0.0.1:1326 or DB connection string]
[-msfdb-type=sqlite3|mysql|redis|http]
[-msfdb-sqlite3-path=/path/to/msfdb.sqlite3] …
```
> fix(server): make config loading same as scan

- config/config.go
- config/tomlloader.go
- report/http.go
- subcmds/report.go
Use SQLite3 in current dir if not specified in config.toml
Report without specifying the path of SQLite3 in config.toml.
Confirmed that SQLite3 in the current directory is used.
```
✗  ubuntu@dev  ~│g│s│g│f│vuls  ⎇ master~  ./vuls tui --refresh-cve
[Dec 26 07:54:24] ERROR Failed to create log file. path: /var/log/vuls/localhost.log, err: open /var/log/vuls/localhost.log: permission denied
[Dec 26 07:54:24]  INFO [localhost] Validating config...
INFO[0000] -cvedb-type: sqlite3, -cvedb-url: , -cvedb-path: /home/ubuntu/go/src/github.com/future-architect/vuls/cve.sqlite3
[Dec 26 07:54:24]  INFO [localhost] Loaded: /home/ubuntu/go/src/github.com/future-architect/vuls/results/2020-12-26T07:22:12+09:00
[Dec 26 07:54:24]  INFO [localhost] Validating db config...
INFO[0000] -cvedb-type: sqlite3, …
```
> fix(reprot): use SQLite3 in current dir if not specified

- scan/redhatbase.go
- scan/redhatbase_test.go
Fix parse error on `rpm -qf`
```
[Dec 30 07:17:50]  WARN [c7s] err: Failed to execute yum-ps:
github.com/future-architect/vuls/scan.(*redhatBase).postScan
/home/ubuntu/go/src/github.com/future-architect/vuls/scan/redhatbase.go:177
- Failed to find the package: error:-file:/run/log/journal/346a500b7fb944199748954baca56086/system.journal:-Permission.denied:
github.com/future-architect/vuls/models.Packages.FindByFQPN
/home/ubuntu/go/src/github.com/future-architect/vuls/models/packages.go:72
[Dec 30 07:17:52]  WARN [localhost] Some warnings occurred during scanning on c7s. Please fix the warnings to get a useful information. Execute configtest subcommand before scanning to know the cause of the warnings. warnings: [Failed to execute yum-ps: …
```
> fix(scan): add an error case for `rpm -qa`

- gost/base.go
- gost/redhat.go
> refactor(gost): Duplicate code into function

- oval/util.go
- oval/util_test.go
`0:2-el8 < 0:2-el8_3`
`# yum install rpmdevtools`
```
[root@ip-192-168-0-219 ~]# rpmdev-vercmp
Epoch1: 0
Version1: 2
Release1: el8_3.1
Epoch2: 0
Version2: 2
Release2: el8_3
0:2-el8_3.1 > 0:2-el8_3
[root@ip-192-168-0-219 ~]# rpmdev-vercmp
Epoch1: 0
Version1: 2
Release1: el8
Epoch2: 0
Version2: 2
Release2: el8_3
0:2-el8 < 0:2-el8_3
```
https://stackoverflow.com/a/26047243/1834557
> fix(redhat): possibility of false positives on RHEL

- config/config.go
- config/os.go
- config/os_test.go
- oval/debian.go
- oval/util.go
- oval/util_test.go
- report/util.go
- scan/serverapi.go
- subcmds/scan.go
- util/util.go
- util/util_test.go
- now + 3months <  standard support EOL
```
Scan Summary
rhel6   redhat6 389 installed
Warning: [Standard OS support will be end in 3 months. EOL date: 2020-11-30]
```
- standard support EOL < now < extended support EOL
```
Scan Summary
rhel6   redhat6 389 installed
Warning: [Standard OS support is EOL(End-of-Life). Purchase extended support if available or upgrading your OS is recommended. Extended support available until 2024-06-30. Check the vendor site.]
```
- extended support EOL < now
```
Scan Summary
rhel6   redhat6 389 installed
Warning: [Standard OS support is EOL(End-of-Life). Purchase extended support if available or upgrading your OS is recommended. Extended support is also EOL. There are many Vulnerabilities that are not …
```
> feat(report): display EOL information to scan summary

- config/os.go
- config/os_test.go
before 
```
Scan Summary
jolly_lovelace@localhost        alpine3.8.4     18 installed, 1 updatable
localhost                       ubuntu18.04     941 installed, 201 updatable
Warning: [Failed to check EOL. Register the issue to https://github.com/future-architect/vuls/issues with the information in `Family: alpine Release: 3.8.4`]
```
after
```
[Jan 12 20:04:18]  WARN [localhost] Some warnings occurred during scanning on localhost. Please fix the warnings to get a useful information. Execute configtest subcommand before scanning to know the cause of the warnings. warnings: [Standard OS support is EOL(End-of-Life). Purchase extended support if available or Upgrading your OS is strongly recommended.]
Scan Summary
jolly_lovelace@localhost        alpine3.8.4 …
```
> fix(scan): err detecting EOL for alpine Linux

- scan/redhatbase.go
before
```
github.com/future-architect/vuls/scan.(*redhatBase).scanPackages
/home/ubuntu/go/src/github.com/future-architect/vuls/scan/redhatbase.go:209
- Failed to dnf module list: execResult: servername: rhel8
cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/ubuntu/.vuls/controlmaster-%r-rhel8.%p -o Controlpersist=10m ec2-user@54.95.80.39 -p 22 -i /home/ubuntu/.ssh/stg.pem -o PasswordAuthentication=no stty cols 1000; dnf --cacheonly --color=never --quiet module list --enabled
exitstatus: 1
stdout: Error: Cache-only enabled but no cache for 'rhui-client-config-server-8'
stderr:
err: %!s(<nil>), cmd: dnf --cacheonly --color=never --quiet module list --enabled: …
```
> fix(scan): kindness msg when no-cache err on dnf mod list

- config/tomlloader.go
- scan/redhatbase.go
* Bypass with -assumeyes when dnf module list stoped at GPG key import prompt appeared.
* Fix to use ssh default user when server.user is empty.
> fix dnf prompt and ssh user

- config/tomlloader.go
```
[default]
port = "local"
```
```
If you update Vuls and get this error, there may be incompatible changes in config.toml
Please check config.toml template : https://vuls.io/docs/en/usage-settings.html
Failed to set default value to config. server: localhost, err:
github.com/future-architect/vuls/config.TOMLLoader.Load                                                                                                 /home/ubuntu/go/src/github.com/future-architect/vuls/config/tomlloader.go:39
- server.user is empty:
github.com/future-architect/vuls/config.setDefaultIfEmpty
/home/ubuntu/go/src/github.com/future-architect/vuls/config/tomlloader.go:159
```
see above
> fix(config): err occurs when host not set in local-scan-mode

- report/email.go
The cause of this bug is passing nil as the argument of c.Auth() when the auth is not obtained.
```golang
if ok, param := c.Extension("AUTH"); ok {
authList := strings.Split(param, " ")
auth = e.newSaslClient(authList)
}
// The following code has a problem
if err = c.Auth(auth); err != nil {
return xerrors.Errorf("Failed to authenticate: %w", err)
}
```
- After
```golang
if ok, param := c.Extension("AUTH"); ok {
authList := strings.Split(param, " ")
auth = e.newSaslClient(authList)
if err = c.Auth(auth); err != nil {
return xerrors.Errorf("Failed to authenticate: %w", err)
}
}
```
Fixes #1130 
- [*] Bug fix (non-breaking change which fixes an issue)
I confirmed that I would receive an email. (Gmail)
https://github.com/future-architect/vuls/blob/3bacb648a5c8d7ca744b5d76057eca7a05c7df43/repo …
> fix(email.go):Fix runtime error(invalid memory address)

- models/packages.go
- models/packages_test.go
- report/util_test.go
- scan/debian.go
- scan/debian_test.go
before 
```
"packages": {
"NetworkManager": {
"name": "NetworkManager",
"version": "1:1.26.0",
"release": "9.el8_3",
"newVersion": "1:1.26.0",
"newRelease": "12.el8_3",
"arch": "x86_64",
"repository": "rhel-8-baseos-rhui-rpms",
"changelog": {
"contents": "",
"method": ""
},
"AffectedProcs": [
{
"pid": "830",
"name": "NetworkManager"
}
]
},
```
after 
```
"packages": {
"NetworkManager": {
"name": "NetworkManager",
"version": "1:1.26.0",
"release": "9.el8_3",
"newVersion": "1:1.26.0",
"newRelease": "12.el8_3",
"arch": "x86_64",
"repository": "rhel-8-baseos-rhui-rpms",
"AffectedProcs": [
{
"pid": "830",
"name": "NetworkManager"
}
]
},
....
```
./vuls scan , ./vuls report, check json
> fix(model): omit changelog from json if empty

- scan/base.go
Scan with the following config.toml, vuls connects via ssh and issues `wp` command, which results in an error.
```
[default]
[default.wordpress]
osUser = "hoge"
docRoot = "/path"
cmdPath = "fuga"
[servers]
[servers.localgem]
lockfiles = [
"/home/ubuntu/work/redmine/gem1/Gemfile.lock"
]
```
```
[Jan 21 06:28:24] DEBUG [localhost] execResult: servername: localgem
cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/ubuntu/.vuls/controlmaster-%r-localgem.%p -o Controlpersist=10m @ -p  stty cols 1000; sudo -u hoge -i -- fuga cli version --allow-root
exitstatus: 255
stdout: 
stderr: usage: ssh [-46AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
[-D …
```
> fix(scan): skip wordpress scan for preudo servers

- github/github.go
- models/cvecontents.go
- models/vulninfos.go
- report/tui.go
- scan/redhatbase.go
GHSA detail information is now displayed when reporting with GitHub integration.
- CVE
- non-CVE
For detail about GHSA integration, see [Usage: Integrate with GitHub Security Alerts](https://vuls.io/docs/en/usage-scan-non-os-packages.html#usage-integrate-with-github-security-alerts)
./vuls report
> feat(github): display GitHub Security Advisory details

- oval/redhat.go
Fixes #1146 
$ ./vuls report
```
"redhat": {
"type": "redhat",
"cveID": "CVE-2019-10906",
"title": "RHSA-2019:1152: python-jinja2 security update (Important)",
"summary": "snip",
"cvss2Score": 0,
"cvss2Vector": "",
"cvss2Severity": "",
"cvss3Score": 9,
"cvss3Vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:H",
"cvss3Severity": "Important",
...snip...
},
```
> fix(report): set severity in Red Hat OVAL to both CVSS v3 and v2 #1146

- saas/saas.go
- saas/uuid.go
Changed the format of s3 key of saas option
Erase time information from s3 key
> fix(saas) change saas upload s3 key

- config/config.go
- report/report.go
When in `scanModules = ["wordpress"]`, the os package will be empty. 
Fixed a bug that caused wordpress vulnerability detection to be skipped in this case.
```
[servers.kusanagi]
host = "xxx"
user = "kanbe"
keyPath = "/home/ubuntu/.ssh/id_rsa"
scanModules = ["wordpress"]
[servers.kusanagi.wordpress]
osUser = "kusanagi"
docRoot = "/home/kusanagi/xxx/DocumentRoot/"
cmdPath = "/usr/local/bin/wp"
```
> fix(report): wordrpess scanning skipped when package is empty

- config/exploitconf.go
- config/gocvedictconf.go
- config/gostconf.go
- config/govaldictconf.go
- exploit/util.go
- github/github.go
- gost/util.go
- models/vulninfos.go
- oval/oval.go
- oval/util.go
- report/chatwork.go
- report/cve_client.go
- report/slack.go
- report/telegram.go
- saas/saas.go
- util/util.go
- wordpress/wordpress.go
Vuls send HTTP requests when reporting, e.g., GitHub Security Alerts, go-cve as http server mode, etc.
But, Vuls hadn't set the HTTP timeout, so Vuls was waiting forever for the http response.
./vuls report works fine
> fix(report): set http timeout 10 sec

- report/report.go
- report/util.go
- subcmds/report.go
Removed duplicated logic since it has already been executed in this line, there is no need to execute it again.
https://github.com/future-architect/vuls/blob/master/report/report.go#L98
./vuls report -diff works fine.
> fix(report): remove duplicated refreshing logic when report with -diff

- wordpress/wordpress.go
after 
```
"wpscan": {
"type": "wpscan",
"cveID": "CVE-2013-5988",
"title": "All in One SEO Pack \u003c= 2.0.3 - XSS ",
"summary": "",
"cvss2Score": 0,
"cvss2Vector": "",
"cvss2Severity": "",
"cvss3Score": 0,
"cvss3Vector": "",
"cvss3Severity": "",
"sourceLink": "",
"references": [
{
"link": "https://packetstormsecurity.com/files/123490/"
},
{
"link": "https://www.securityfocus.com/bid/62784/"
},
{
"link": "https://seclists.org/bugtraq/2013/Oct/8"
}
],
"published": "2014-08-01T10:59:02Z",
"lastModified": "2020-09-22T05:58:51Z"
}
```
check the output json
> fix(report): set created_at and updated_at of wpscan.com to json

- contrib/trivy/parser/parser.go
```
ubuntu@dev  ~│g│s│g│f│vuls  ⎇ trivy-time~  ./trivy -q image -f=json ubuntu | ./trivy-to-vuls parse --stdin
"CVE-2018-20839": {
"cveID": "CVE-2018-20839",
"confidences": [
{
"score": 100,
"detectionMethod": "TrivyMatch"
}
],
"affectedPackages": [
{
"name": "libsystemd0",
"notFixedYet": true,
"fixState": "Affected"
},
{
"name": "libudev1",
"notFixedYet": true,
"fixState": "Affected"
}
],
"cveContents": {
"trivy": {
"type": "",
"cveID": "",
"title": "systemd: mishandling of the current keyboard mode check leading to passwords being disclosed in cleartext to attacker",
"summary": "systemd 242 changes the VT1 mode upon a logout, which allows attackers to read cleartext passwords in certain circumstances, such as watching a shutdown, or using Ctrl-Alt-F1 and Ctrl-Alt-F2. This occurs because …
```
> fix(report): set created_at and updated_at of trivy to json

- cmd/vuls/main.go
- scan/alpine.go
- scan/debian.go
- scan/freebsd.go
- scan/pseudo.go
- scan/suse.go
- util/logutil.go
```
✗  ubuntu@dev  ~│g│s│g│f│vuls  ⎇ master~  ./vuls scan vulsdoc
[Feb  4 07:37:27] ERROR Failed to create log file. path: /var/log/vuls/localhost.log, err: open /var/log/vuls/localhost.log: permission denied
[Feb  4 07:37:27]  INFO [localhost] vuls-v0.15.6-build-20210204_073220_64a6222
[Feb  4 07:37:27]  INFO [localhost] Start scanning
...
```
> fix(log): output the version of vuls to log for debugging purpose

- models/packages.go
- scan/redhatbase.go
This warning could occur when multiple installations of the same package (different architectures) installed.
```
[root@ip-192-168-0-154 ~]# rpm -qa | grep glibc-2
glibc-2.17-322.el7_9.x86_64
glibc-2.17-322.el7_9.i686
```
```
Scan Summary
c7      centos7.7.1908  303 installed, 134 updatable
Warning: [Failed to execute yum-ps:
github.com/future-architect/vuls/scan.(*redhatBase).postScan
/home/ubuntu/go/src/github.com/future-architect/vuls/scan/redhatbase.go:177
- Failed to find the package: glibc-2.17-322.el7_9.x86_64:
github.com/future-architect/vuls/models.Packages.FindByFQPN
/home/ubuntu/go/src/github.com/future-architect/vuls/models/packages.go:72]
```
The warning described above is not output.
***Is this ready for …
> fix(scan): yum-ps warning `Failed to find the package`

- scan/base.go
- scan/base_test.go
```
[Feb  6 06:40:31]  WARN [c7] Failed to exec which -bash: execResult: servername: c7
cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/ubuntu/.vuls/controlmaster-%r-c7.%p -o Controlpersist=10m centos@54.199.215.61 -p 22 -i /home/ubuntu/.ssh/stg.pem -o PasswordAuthentication=no stty cols 1000; sudo -S LANGUAGE=en_US.UTF-8 which -bash
exitstatus: 255
stdout: which: invalid option -- 'b'
which: invalid option -- 's'
which: invalid option -- 'h'
Usage: which [options] [--] COMMAND [...]
Write the full path of COMMAND(s) to standard output.
--version, -[vV] Print version and exit successfully.
--help,          Print this help and exit successfully.
--skip-dot       Skip directories in …
```
> fix(scan): fix yum-ps warning `Failed to exec which -bash`

- scan/base.go
- scan/base_test.go
- scan/debian.go
- scan/redhatbase.go
```
[Feb  6 08:27:21] DEBUG [c7] Executing... lsof -i -P -n | grep LISTEN                                                                        
[Feb  6 08:27:21] DEBUG [c7] execResult: servername: c7                                                                                                       
cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/ubuntu/.vuls/controlmaster-%r-c7.%p -o Controlpersist=10m centos@54.199.215.61 -p 22 -i /home/ubuntu/.ssh/stg.pem -o PasswordAuthentication=no stty cols 1000; sudo -S lsof -i -P -n | grep LISTEN                                                                                                                     
exitstatus: 1 …
```
> fix(scan): warning if lsof command not found

- config/config.go
- models/scanresults.go
- models/vulninfos.go
- report/localfile.go
- report/report.go
- report/slack.go
- report/tui.go
- report/util.go
- report/util_test.go
- subcmds/report.go
- subcmds/tui.go
./vuls tui -diff
./vuls report -format-list -diff
./vuls report -format-full-text -diff
./vuls report -format-one-line-text -diff
This patch has the function to output the resolved(patched) CVEs compared to the previous JSON.
--diff option turns on both options -diff-plus and -diff-minus
Document pull request : https://github.com/vulsdoc/vuls/pull/140
> feat(report) : Differences between vulnerability patched items

- oval/util_test.go
Add test-case to verify proper version comparison when either/both/neither of newVer and ovalmodels.Package contain "_minorVersion"
Provides missing test-cases for https://github.com/future-architect/vuls/pull/1176 which fixed https://github.com/future-architect/vuls/issues/1171
I ran `go test -v` within the oval directory.
With the code prior to #1176 , this new test fails any time that ovalmodels.Package contain "_minorVersion" (this is the expected and desired result) : 
```
[root@vuls-210209 oval]# go test -v
=== RUN   TestPackNamesOfUpdateDebian
--- PASS: TestPackNamesOfUpdateDebian (0.00s)
=== RUN   TestParseCvss2
--- PASS: TestParseCvss2 (0.00s)
=== RUN   TestParseCvss3
--- PASS: TestParseCvss3 (0.00s)
=== RUN   TestPackNamesOfUpdate
--- …
```
> Add test-case to verify proper version comparison in lessThan() 

- config/azureconf.go
- config/config.go
- config/httpconf.go
- reporter/http.go
- subcmds/report.go
Use env var if not empty.
- VULS_HTTP_URL
- AZURE_STORAGE_ACCOUNT
- AZURE_STORAGE_ACCESS_KEY
Remove -http-url command line option from report subcmd.
> fix(report): prioritize env vars over config.toml

- contrib/trivy/parser/parser.go
- contrib/trivy/parser/parser_test.go
Fixes #1200 
`go test contrib/trivy/parser` and `go run contrib/trivy/cmd parse -d results -f trivy-vuln` 
***Is this ready for review?:*** YES.
> fix(trivy-to-vuls): converts even if null vulnerabilities

- GNUmakefile
In the initial state, there are no results under the integration directory, and make diff will generate an error. Therefore, we need to add directory and file checks.
I deleted the `integration/results` file and ran `make diff`, and confirmed that it succeeded.
```terminal
$ rm -rf integration/results/
$ make diff
```
- https://vuls.io/docs/en/testing.html
> fix: support for missing files in the results or results directory

- reporter/http.go
- subcmds/report.go
The error occurs due to use of incorrect values like bellow.
```go
reports = append(reports, reporter.HTTPRequestWriter{Proxy: config.Conf.HTTPProxy})
```
So, replace these values to correct values as supposed and rename HTTPProxyWriter's member, Proxy, into URL like bellow.
```go
reports = append(reports, reporter.HTTPRequestWriter{URL: config.Conf.HTTP.URL})
```
Fixes #1213 
After changed, run program with bellow and confirmed exit success.
***Is this ready for review?:*** Yes 
> fix(report): Avoid http reports error when add program argument "-to-http"

- gost/gost.go
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xe157e2]
goroutine 1 [running]:
github.com/future-architect/vuls/gost.Base.CloseDB(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/ubuntu/go/src/github.com/future-architect/vuls/gost/gost.go:33 +0x22
github.com/future-architect/vuls/detector.detectPkgsCvesWithGost.func1(0x150b1d0, 0xc00042a5c0)
/home/ubuntu/go/src/github.com/future-architect/vuls/detector/detector.go:373 +0x35
github.com/future-architect/vuls/detector.detectPkgsCvesWithGost(0x12a8dfa, 0x4, 0xc0005405f0, 0x7, 0x0, 0x0, 0xc000040390, 0x28, 0x0, 0xc000b94600, ...)
/home/ubuntu/go/src/github.com/future-architect/vuls/detector/detector.go:384 +0x3e5 …
```
> fix(report): panic when closing db connection of gost

- scanner/utils.go
Fixes #1199
```
./vuls server
```
```
ubuntu@dev  │tmp  cat paquets.txt
grub2-common 1 2.02 90.el8 noarch
grub2-pc 1 2.02 90.el8 x86_64
grub2-pc-modules 1 2.02 90.el8 noarch
grub2-tools 1 2.02 90.el8 x86_64
grub2-tools-efi 1 2.02 90.el8 x86_64
grub2-tools-extra 1 2.02 90.el8 x86_64
grub2-tools-minimal 1 2.02 90.el8 x86_64
kernel 0 4.18.0 193.el8 x86_64
kernel 0 4.18.0 240.15.1.el8_3 x86_64
kernel-core 0 4.18.0 193.el8 x86_64
kernel-core 0 4.18.0 240.15.1.el8_3 x86_64
kernel-modules 0 4.18.0 193.el8 x86_64
kernel-modules 0 4.18.0 240.15.1.el8_3 x86_64
ubuntu@dev  │tmp  cat paquets-2.txt
grub2-common 1 2.02 90.el8 noarch
grub2-pc 1 2.02 90.el8 x86_64
grub2-pc-modules 1 2.02 90.el8 noarch
grub2-tools 1 2.02 90.el8 x86_64
grub2-tools-efi 1 2.02 90.el8 x86_64
grub2-tools-extra 1 2.02 90.el8 …
```
> fix(report): false positive for kernel-related CVE for RedHat, CentOS, Oracle and Amazon #1199

- oval/util.go
- oval/util_test.go
If there is no *arch* in OVAL DB for Amazon Linux and Oracle, the data is old and false positive, so display an error.
> fix(oracle): display an error when no "arch" in OVAL DB for Oracle

- config/config.go
- detector/detector.go
- subcmds/report.go
To specify config, [Ignore github dismissed](https://vuls.io/docs/en/usage-scan-non-os-packages.html#usage-integrate-with-github-security-alerts), per a repository, chaged the specifiation of config.toml like bellow.
```toml
[servers]
[servers.tttfrfr2]
[servers.tttfrfr2.githubs."owner/REPO_1"]
token = "********************************************"
ignoreGitHubDismissed = true # or false
```
For addition, removed program argument "-ignore-github-dismissed" when report
debug vuls with delve and use config.toml like bellow (hidden token and repository name).
- debug
```bash
$ dlv debug cmd/vuls/main.go -- report
Type 'help' for list of commands.
(dlv) b detector/detector.go:222
Breakpoint 1 (enabled) set at 0x138a771 for …
```
> refactor(git-conf): Specifing ignoreGitHubDismissed per repository

- GNUmakefile
- go.mod
- go.sum
- integration/data/oracle.json
- oval/redhat.go
```
"advisoryID": "\nELSA-2018-3221:  openssl security, bug fix, and enhancement update (MODERATE)\n",
```
```
"advisoryID": "ELSA-2018-3221",
```
The result of `make diff` is as intended.
> fix(oracle): extracting only advisory ID from OVAL.title

- scanner/debian.go
Vuls stop due to panic when SSH connection refused as below.
- vuls scan when SSH connection refused
```bash
$ vuls scan
[May 11 16:41:46]  INFO [localhost] vuls-v0.15.11-build-20210418_144724_27b3e17
[May 11 16:41:46]  INFO [localhost] Start scanning
[May 11 16:41:46]  INFO [localhost] config: /home/$USER/config.toml
...
[May 11 16:41:46]  INFO [localhost] Validating config...
[May 11 16:41:46]  INFO [localhost] Detecting Server/Container OS...
[May 11 16:41:46]  INFO [localhost] Detecting OS of servers...
[May 11 16:45:45] DEBUG [localhost] Executing... ls /etc/debian_version
[May 11 16:45:45] DEBUG [localhost] execResult: servername: err
cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o …
```
> fix(scan): Avoid panic when SSH connection refused

- GNUmakefile
- go.mod
- go.sum
- integration/int-config.toml
- integration/int-redis-config.toml
- models/library.go
- models/scanresults.go
- scanner/base.go
https://github.com/aquasecurity/trivy/compare/v0.17.2...v0.18.3
> feat(lib): support of Go (go.sum) scan

- oval/util.go
- oval/util_test.go
`OVAL DB for oracle is old. Please re-fetch the OVAL`
TUI displays `Not Fixed Yet` when it should be `Fixed`.
> fix(report): detection logic bugs for Oracle Linux

- GNUmakefile
- detector/github.go
- detector/library.go
- detector/util.go
- detector/wordpress.go
- detector/wordpress_test.go
- gost/debian_test.go
- gost/gost_test.go
- gost/redhat_test.go
- gost/util.go
- oval/empty.go
- scanner/base.go
```
ubuntu@dev  ~│g│s│g│f│vuls  ⎇ master~  CGO_ENABLED=0 make build-scanner
GO111MODULE=off go get -u golang.org/x/lint/golint
golint github.com/future-architect/vuls/cache github.com/future-architect/vuls/cmd/scanner github.com/future-architect/vuls/cmd/vuls github.com/future-architect/vuls/config github.com/future-architect/vuls/constant github.com/future-architect/vuls/contrib/future-vuls/cmd github.com/future-architect/vuls/contrib/owasp-dependency-check/parser github.com/future-architect/vuls/contrib/trivy/cmd github.com/future-architect/vuls/contrib/trivy/parser github.com/future-architect/vuls/cwe github.com/future-architect/vuls/detector github.com/future-architect/vuls/errof github.com/future-architect/vuls/gost github.com/future-architect/vuls/logging …
```
> fix(vet): go vet err of `make build-scanner`

- .goreleaser.yml
To fix the error
```
⨯ build failed after 115.56s error=failed to build for linux_386: # github.com/kotakanbe/goval-dictionary/db/rdb
../../../../pkg/mod/github.com/kotakanbe/goval-dictionary@v0.3.6-0.20210429000733-6db1754b1d87/db/rdb/rdb.go:113:16: undefined: sqlite3.Error
../../../../pkg/mod/github.com/kotakanbe/goval-dictionary@v0.3.6-0.20210429000733-6db1754b1d87/db/rdb/rdb.go:114:9: undefined: sqlite3.ErrLocked
../../../../pkg/mod/github.com/kotakanbe/goval-dictionary@v0.3.6-0.20210429000733-6db1754b1d87/db/rdb/rdb.go:114:28: undefined: sqlite3.ErrBusy
../../../../pkg/mod/github.com/kotakanbe/go-cve-dictionary@v0.5.12/db/rdb.go:66:16: undefined: sqlite3.Error
../../../../pkg/mod/github.com/kotakanbe/go-cve-dictionary@v0.5.12/db/rdb.go:67:9: undefined: sqlite3.ErrLocked …
```
> chore: fix build-tags in .goreleaser.yml

- models/library.go
When scanning LockFile, there was a problem that AffectedPackages was empty when FixedIn was an empty character.
check make diff output
> fix(libscan): support empty LibraryFixedIn

- config/os.go
Correct Ubuntu 20.10 EOL's date July 1 to July 22.
see also https://lists.ubuntu.com/archives/ubuntu-announce/2021-June/000269.html
PS
Ubuntu 21.04 was released on April **22**, I guessed 21.04 EOL is January **22**, too :-)
Fixes #1255
> fix Ubuntu 20.10 End of Life on July 22 2021 (#1255)

- go.mod
- go.sum
- oval/oval.go
Version up the goval-dictionary.
Refs https://github.com/kotakanbe/goval-dictionary/pull/136
```console
$ vuls scan && vuls report
[Jun 25 13:31:43]  INFO [localhost] vuls-v0.15.11-build-20210625_132356_3086e27
[Jun 25 13:31:43]  INFO [localhost] Start scanning
[Jun 25 13:31:43]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Jun 25 13:31:43]  INFO [localhost] Validating config...
[Jun 25 13:31:43]  INFO [localhost] Detecting Server/Container OS... 
[Jun 25 13:31:43]  INFO [localhost] Detecting OS of servers... 
[Jun 25 13:31:43]  INFO [localhost] (1/1) Detected: localhost: ubuntu 20.04
[Jun 25 13:31:43]  INFO [localhost] Detecting OS of containers... 
[Jun 25 13:31:43]  INFO [localhost] Checking Scan Modes... 
[Jun 25 13:31:43]  INFO [localhost] …
```
> feat(oval): goval-dictionary update

- oval/debian.go
Support Ubuntu21
add kernelNamesInOval of Ubuntu21.
Fixes #1230
```
% vuls report -format-full-text
example (ubuntu21.04)
=======================
Total: 27 (Critical:5 High:27 Medium:0 Low:0 ?:0)
0/32 Fixed, 6 poc, 0 exploits, en: 0, ja: 0 alerts
1212 installed
+---------------+--------------------------------------------------------------+
| CVE-2016-1585 | UNFIXED                                                      |
+---------------+--------------------------------------------------------------+
| Max Score     | 9.8 CRITICAL (nvd)                                           |
| nvd           | 9.8/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H CRITICAL    |
| jvn …
```
> feat: Support Ubuntu21 ( #1230 )

- constant/constant.go
- scanner/redhatbase.go
- scanner/rocky.go
support Rocky Linux verions 8.4
https://rockylinux.org/ja/
```
as-MacBook-Pro:vuls a$ vuls scan # fast mode on oval
[Jun 27 19:18:05]  INFO [localhost] vuls-v0.15.11-build-20210625_211447_8e6351a
[Jun 27 19:18:05]  INFO [localhost] Start scanning
[Jun 27 19:18:05]  INFO [localhost] config: /Users/a/vuls/config.toml
[Jun 27 19:18:05]  INFO [localhost] Validating config...
[Jun 27 19:18:05]  INFO [localhost] Detecting Server/Container OS... 
[Jun 27 19:18:05]  INFO [localhost] Detecting OS of servers... 
[Jun 27 19:18:06]  INFO [localhost] (1/1) Detected: rocky: redhat 8.4
[Jun 27 19:18:06]  INFO [localhost] Detecting OS of containers... 
[Jun 27 19:18:06]  INFO [localhost] Checking Scan Modes... 
[Jun 27 19:18:06]  INFO [localhost] Detecting Platforms... 
[Jun 27 19:18:07]  INFO …
```
> feat(os) : support Rocky linux 

- README.md
- config/config.go
- config/os.go
- config/os_test.go
- constant/constant.go
- gost/gost.go
- models/cvecontents.go
- models/scanresults_test.go
- oval/redhat.go
- oval/util.go
- oval/util_test.go
- scanner/centos.go
- scanner/redhatbase.go
- scanner/rhel.go
- scanner/rocky.go
- scanner/serverapi.go
- scanner/utils.go
With #1260, an attempt to support Rocky Linux has been incorporated into master. However, this implementation is inadequate and will be fixed in this PR to work properly.
Please note that Trivy does not yet support Rocky Linux.(2021/07/02)
https://github.com/aquasecurity/trivy/issues/1053
https://github.com/future-architect/vuls/blob/master/contrib/trivy/parser/parser.go#L145-L169
```console
$ vuls scan
[Jul  2 16:02:03]  INFO [localhost] vuls-v0.15.11-build-20210702_160035_1179f50
[Jul  2 16:02:03]  INFO [localhost] Start scanning
[Jul  2 16:02:03]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Jul  2 16:02:03]  INFO [localhost] Validating config...
[Jul  2 16:02:03]  INFO [localhost] Detecting Server/Container OS... 
[Jul  2 16:02:03]  INFO …
```
> fix(rocky): fix Scan in Rocky Linux

- gost/ubuntu.go
URI correction for ubuntu; see gost project: https://github.com/knqyf263/gost/blob/master/server/server.go#L48
corrected the URI according to gost source code. see https://github.com/knqyf263/gost/blob/master/server/server.go#L48
When creating reports using gost for ubuntu hosts:
```
time="Jul 29 09:21:18" level=warning msg="Failed to HTTP GET. retrying in 395.339215ms seconds. err: HTTP GET error, url: http://gost:1325/ubuntu/2004/pkg/dbus/unfixed-cves, resp: &{404 Not Found 404 HTTP/1.1 1 1 map[Content-Length:[24] Content-Type:[application/json; charset=UTF-8] Date:[Thu, 29 Jul 2021 09:21:18 GMT] Retry-Count:[0]] {{\"message\":\"Not Found\"}\n    } 24 [] true false map[] 0xc003a1e100 <nil>}, err: []:\n    github.com/future-architect/vuls/gost.httpGet.func1\n …
```
> fix(gost): URI in ubuntu.go corrected, did not work

- README.md
- config/config.go
- config/os.go
- config/os_test.go
- constant/constant.go
- gost/gost.go
- models/cvecontents.go
- models/scanresults_test.go
- oval/redhat.go
- oval/util.go
- scanner/alma.go
- scanner/centos.go
- scanner/oracle.go
- scanner/redhatbase.go
- scanner/rhel.go
- scanner/rocky.go
- scanner/serverapi.go
- scanner/utils.go
support Alma Linux version 8.4.
https://almalinux.org/
on oval.
```
$vuls report #fast mode
[Jun 25 22:53:42]  INFO [localhost] vuls-v0.15.11-build-20210625_211447_8e6351a
[Jun 25 22:53:42]  INFO [localhost] Validating config...
[Jun 25 22:53:42]  INFO [localhost] cveDict.type=sqlite3, cveDict.url=, cveDict.SQLite3Path=/Users/a/vuls/cve.sqlite3
[Jun 25 22:53:42]  INFO [localhost] ovalDict.type=sqlite3, ovalDict.url=, ovalDict.SQLite3Path=/Users/a/vuls/oval.sqlite3
[Jun 25 22:53:42]  INFO [localhost] gost.type=sqlite3, gost.url=, gost.SQLite3Path=/Users/a/vuls/gost.sqlite3
[Jun 25 22:53:42]  INFO [localhost] exploit.type=sqlite3, exploit.url=, exploit.SQLite3Path=/Users/a/vuls/go-exploitdb.sqlite3
[Jun 25 22:53:42]  INFO [localhost] metasploit.type=sqlite3, metasploit.url=, …
```
> feat(os) : support Alma Linux

- detector/detector.go
- go.mod
- go.sum
Confidence setting was wrong when searching for CVE by CPE URI. 
Set the Confidence like this.
|                 search CPE URI                |      NVD only hit     |      JVN only hit     |    NVD and JVN hit    |
|:---------------------------------------------:|:---------------------:|:---------------------:|:---------------------:|
|    cpe:/o:titan:sf_rush_smart_band_firmware   | CpeVendorProductMatch | CpeVendorProductMatch | CpeVendorProductMatch |
| cpe:/o:titan:sf_rush_smart_band_firmware:1.12 |    CpeVersionMatch    | CpeVendorProductMatch |    CpeVersionMatch    |
```
// config.toml
cpeNames = [
"cpe:/o:titan:sf_rush_smart_band_firmware",
]
$ vuls report
// result/*/localhost.json
"CVE-2020-11539": {
"cveID": "CVE-2020-11539", …
```
> fix(cpescan): fix confidence in cpe uri scan

- GNUmakefile
- config/config.go
- detector/cve_client.go
- detector/detector.go
- detector/detector_test.go
- go.mod
- go.sum
- integration/int-config.toml
- integration/int-redis-config.toml
- models/cvecontents.go
- models/cvecontents_test.go
- models/scanresults.go
- models/scanresults_test.go
- models/vulninfos.go
- models/vulninfos_test.go
- reporter/slack.go
- reporter/util.go
- scanner/debian.go
- scanner/debian_test.go
- subcmds/discover.go
- subcmds/report.go
- subcmds/server.go
- subcmds/tui.go
- tui/tui.go
ref. 
- https://github.com/kotakanbe/go-cve-dictionary/pull/209
- https://github.com/vulsdoc/vuls/pull/167/files
CpeVersionMatch and CpeVendorProductMatch were removed and the following have been added.
| Detection Method       | Confidence |  type                            |Description|
|:-----------------------|-----------:|:---------------------------------|:--|
| NvdExactVersionMatch   | 100        |                         CPE scan |Range match in semantic versioning format or an exact match.|
| NvdRoughVersionMatch   |  80        |                         CPE scan |Rough version match for non-semantic versioning as defined in NVD.|
| NvdVendorProductMatch  |  10        |                         CPE scan |If the version is not defined for the CPE specified in config.toml. There is a …
> breaking-change(cpescan): Improve Cpe scan

- config/os.go
- config/os_test.go
- gost/debian.go
- gost/debian_test.go
Debian 11 has been released, OVAL etc., so vuls fully scans Debian 11.
```console
$ vuls scan && vuls report
[Sep  1 21:43:34]  INFO [localhost] vuls-v0.15.13-build-20210901_200909_b9416ae
[Sep  1 21:43:34]  INFO [localhost] Start scanning
[Sep  1 21:43:34]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Sep  1 21:43:34]  INFO [localhost] Validating config...
[Sep  1 21:43:34]  INFO [localhost] Detecting Server/Container OS... 
[Sep  1 21:43:34]  INFO [localhost] Detecting OS of servers... 
[Sep  1 21:43:35]  INFO [localhost] (1/1) Detected: vuls-target: debian 11.0
[Sep  1 21:43:35]  INFO [localhost] Detecting OS of containers... 
[Sep  1 21:43:35]  INFO [localhost] Checking Scan Modes... 
[Sep  1 21:43:35]  INFO [localhost] Detecting Platforms... …
```
> feat(debian): support Debian 11(bullseye)

- go.mod
- go.sum
- integration/data/results/rhel_8.json
Please use this revision with the latest version of goval-dictionary.
Old dictionaries can't detect it correctly.
Since the Redis schema has been changed, you have to delete Redis and fetch it again.
```console
// delete all old key
$ redis-cli keys "OVAL#*" | xargs redis-cli del
```
see https://github.com/kotakanbe/goval-dictionary/pull/145
Integration test works fine.
> breaking-change(goval): change-redis-architecture

- scanner/freebsd.go
- scanner/freebsd_test.go
> Fix the parsing logic of FreeBSD pkg-audit

- detector/detector.go
- detector/util.go
- models/scanresults.go
skip OVAL/gost search when the number of packages is 0.
Fixes #1342 
```console
...
[servers]
host                = "localhost"
port               = "local"
user               = "mainek00n"
scanModules        = ["lockfile"]
lockfiles = ["/home/mainek00n/Downloads/lockfiles/log4j-core-2.14.1.jar"]
...
$ vuls scan
[Dec 14 17:29:58]  INFO [localhost] vuls-v0.19.0-build-20211214_172301_a01f9c9
[Dec 14 17:29:58]  INFO [localhost] Start scanning
[Dec 14 17:29:58]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Dec 14 17:29:58]  INFO [localhost] Validating config...
[Dec 14 17:29:58]  INFO [localhost] Detecting Server/Container OS... 
[Dec 14 17:29:58]  INFO [localhost] Detecting OS of …
```
> fix(detector/ospkg): Skip OVAL/gost search when the number of packages is 0

- go.mod
- go.sum
If you get an error when reporting, please update go-kev to v0.1.0 and re-fetch it.
For details, see 
https://github.com/vulsio/go-kev/releases/tag/v0.1.0
> feat(go-kev): update go-kev deps

- scanner/base.go
> fix(scanner/base) export libFile struct

- gost/gost.go
`newGostDB` returns db as nil in HTTP mode. 
https://github.com/future-architect/vuls/blob/ffdb78962f9bc96df527bb468ed3d5856337a395/gost/gost.go#L83-L86
It seems to dereference the nil pointer at the time of `db.Close()`.
https://github.com/future-architect/vuls/blob/ffdb78962f9bc96df527bb468ed3d5856337a395/gost/gost.go#L50
Fixes https://github.com/future-architect/vuls/issues/1281
```console
$ vuls.master report --refresh-cve
[Feb  2 20:04:19]  INFO [localhost] vuls-v0.19.2-build-20220128_200342_b4c23c1
[Feb  2 20:04:19]  INFO [localhost] Validating config...
[Feb  2 20:04:19]  INFO [localhost] cveDict.type=sqlite3, cveDict.url=, cveDict.SQLite3Path=/usr/share/vuls-data/cve.sqlite3
[Feb  2 20:04:19]  INFO [localhost] ovalDict.type=sqlite3, ovalDict.url=, …
```
> fix(gost): add nil check

- config/config.go
- config/os.go
- gost/redhat.go
- oval/oval.go
- oval/util.go
- oval/util_test.go
- scanner/redhatbase.go
CentOS8 and CentOS Stream8 use the same OVAL and Gost (RedHat Security API), but the EOL is different.
Currently, EOL of CentOS8 is also set for CentOS Stream8, and WARN is output. Fix this.
```console
$ vuls scan
[Jan 14 13:46:55]  INFO [localhost] vuls-v0.19.1-build-20220114_134430_a3f7d1d
[Jan 14 13:46:55]  INFO [localhost] Start scanning
[Jan 14 13:46:55]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Jan 14 13:46:55]  INFO [localhost] Validating config...
[Jan 14 13:46:55]  INFO [localhost] Detecting Server/Container OS... 
[Jan 14 13:46:55]  INFO [localhost] Detecting OS of servers... 
[Jan 14 13:46:56]  INFO [localhost] (1/1) Detected: vuls-target: centos 8
[Jan 14 13:46:56]  INFO [localhost] Detecting OS of containers... 
[Jan 14 13:46:56] …
```
> fix(centos): identify CentOS and CentOS Stream

- gost/debian.go
- oval/debian.go
- scanner/base.go
- scanner/serverapi.go
- scanner/serverapi_test.go
Fixes https://github.com/future-architect/vuls/issues/846
If Debian is the scanning target, and docker is used, or if the correct kernel version cannot be obtained for some reason, it will output a warn log and will not detect OVAL or gost in the linux package.
Using the Docker environment, I reproduced the case of an invalid kernel version.
```console
// In the container to be scanned
$ root@a7226e85a420:~# uname -a
Linux a7226e85a420 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64 GNU/Linux
$ go run cmd/vuls/main.go scan
[Feb  7 06:05:09]  INFO [localhost] vuls-`make build` or `make install` will show the version-
[Feb  7 06:05:09]  INFO [localhost] Start scanning
[Feb  7 06:05:09]  INFO [localhost] config: …
```
> feat(debian): validate running kernel version

- scanner/debian.go
- scanner/serverapi.go
vuls uses SSH connection when scanning.
The SSH connection of vuls scan is basically set to `StrictHostKeyChecking=yes`, so the host's public key must be registered in known_hosts.
However, the error message does not classify whether the error is caused by the host's public key not being registered in known_hosts or not.
This PR classifies the errors that occur when the host's public key is not registered in known_hosts for the user.
```console
$ vuls scan
[Feb 10 23:13:10]  INFO [localhost] vuls-v0.19.2-build-20220128_200342_b4c23c1
[Feb 10 23:13:10]  INFO [localhost] Start scanning
[Feb 10 23:13:10]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Feb 10 23:13:10]  INFO [localhost] Validating config...
[Feb 10 23:13:10]  INFO [localhost] Detecting …
```
> feat(configtest,scan): detect known_hosts error

- config/loader.go
- config/tomlloader.go
- scanner/executil.go
- scanner/serverapi.go
- subcmds/configtest.go
- subcmds/report.go
- subcmds/saas.go
- subcmds/scan.go
- subcmds/server.go
- subcmds/tui.go
- subcmds/util.go
I would like to support the case where a user tries to scan vuls with the host written in SSH Config.
- /home/mainek00n/.ssh/config
```console
Host vuls-target
HostName 127.0.0.1
Port 2222
Identityfile ~/github/github.com/MaineK00n/vuls-targets-docker/.ssh/id_rsa
Identitiesonly yes
User root
KexAlgorithms +diffie-hellman-group1-sha1
```
> ssh(1) obtains configuration data from the following sources in the following order:
1.   command-line options
2.   user's configuration file (~/.ssh/config)
3.   system-wide configuration file (/etc/ssh/ssh_config)
ref: https://man7.org/linux/man-pages/man5/ssh_config.5.html
- config.toml
```toml
[default]
[servers.vuls-target]
host                = "vuls-target"
```
It seems that user is …
> fix(configtest,scan): support SSH config file

- util/util.go
- util/util_test.go
Fixes https://github.com/future-architect/vuls/issues/1390
When Major() is performed on a major version, the method of obtaining the index results in an index of -1, which causes out-of-range access. This has been fixed by implementing split with `.`.
```console
$ vuls configtest -debug
[Feb 15 05:14:48]  INFO [localhost] vuls-v0.19.3-build-20220215_051246_0733561
[Feb 15 05:14:48]  INFO [localhost] Validating config...
[Feb 15 05:14:48]  INFO [localhost] Detecting Server/Container OS... 
[Feb 15 05:14:48]  INFO [localhost] Detecting OS of servers... 
[Feb 15 05:14:48] DEBUG [localhost] Validating SSH Settings for Server:vuls-target ...
[Feb 15 05:14:48] DEBUG [localhost] Executing... /usr/bin/ssh -G -F /home/mainek00n/.ssh/config -p 2222 -l root 127.0.0.1
[Feb 15 05:14:48] DEBUG …
```
> fix(util): Major() behavior for major version

- scanner/serverapi.go
Fixes https://github.com/future-architect/vuls/issues/1389
If ServerType is pseudo, SSH config check does not run.
Also, if StrictHostKeyChecking is no, it will not check if the host's public key is registered in known_hosts.
In addition, if there is a description of proxyjump or proxycommand, it is difficult to follow the destination of the proxy, so once the check of known_hosts is abandoned.
- config.toml
```toml
[servers]
[servers.forti]
cpeNames = [
"cpe:/o:fortinet:fortios:4.3.0",
]
[servers.vuls-target]
host                = "vuls-target"
sshConfigPath		= "/home/mainek00n/.ssh/config"
```
- /home/mainek00n/.ssh/config
```
Host vuls-target
HostName 127.0.0.1
Port 2222
Identityfile …
```
> fix(configtest,scan): fix validateSSHConfig

- oval/suse.go
In goval-dictionary, when fetching with `--no-details`, the title will be `""`.
In vuls, there was a bug in the title-dependent part.
Fix this.
```console
$ goval-dictionary fetch suse --suse-type opensuse-leap 15.3 --no-details
$ vuls report
[Feb 17 10:50:39]  INFO [localhost] vuls-v0.19.4-build-20220217_104818_716bf30
[Feb 17 10:50:39]  INFO [localhost] Validating config...
[Feb 17 10:50:39]  INFO [localhost] cveDict.type=sqlite3, cveDict.url=, cveDict.SQLite3Path=/usr/share/vuls-data/cve.sqlite3
[Feb 17 10:50:39]  INFO [localhost] ovalDict.type=sqlite3, ovalDict.url=, ovalDict.SQLite3Path=/usr/share/vuls-data/oval.sqlite3
[Feb 17 10:50:39]  INFO [localhost] gost.type=sqlite3, gost.url=, gost.SQLite3Path=/usr/share/vuls-data/gost.sqlite3
[Feb 17 10:50:39]  INFO [localhost] …
```
> fix(oval/suse): use def.Advisory.Cves[0].CveID instead of def.Title

- contrib/trivy/parser/v2/parser.go
- contrib/trivy/parser/v2/parser_test.go
I added error handling to trivy-to-vuls.
If Trivy scan the image that is not Trivy supported OS or Libraries, Vuls behave the result is not parsable and is error.
1. write a test code
2. I have tried to parse result of `./trivy -q image --list-all-pkgs -f json hello-world:latest` and confirmed outputting error as expected
3. I have tried to parse result of `./trivy -q image --list-all-packages -f json ubuntu:latest` and confirmed outputing no error as usual
> fix: handling when image contains no trivy-target

- reporter/util.go
- scanner/scanner.go
Replace NVD column with PACKAGES column at the output of `vuls report` and add table row lines.
+fix spelling mistake
```
❯ vuls report
[Mar  7 20:49:10]  INFO [localhost] vuls-v0.19.4-build-20220307_202611_dc9ae7a
[Mar  7 20:49:10]  INFO [localhost] Validating config...
[Mar  7 20:49:10]  INFO [localhost] cveDict.type=sqlite3, cveDict.url=, cveDict.SQLite3Path=/home/masato/go/src/github.com/future-architect/vuls/cve.sqlite3
[Mar  7 20:49:10]  INFO [localhost] ovalDict.type=sqlite3, ovalDict.url=, ovalDict.SQLite3Path=/home/masato/go/src/github.com/future-architect/vuls/oval.sqlite3
[Mar  7 20:49:10]  INFO [localhost] gost.type=sqlite3, gost.url=, gost.SQLite3Path=/home/masato/go/src/github.com/future-architect/vuls/gost.sqlite3
[Mar  7 …
```
> feat: replace NVD-column with packages-column at output of report

- models/library.go
- scanner/base.go
- subcmds/discover.go
Fixes #1416
Increase the scope of automatic library detection by findLock=true.
```console
$ go run cmd/vuls/main.go scan -config=./config.toml library
[Mar 14 21:01:10]  INFO [localhost] vuls-`make build` or `make install` will show the version-
[Mar 14 21:01:10]  INFO [localhost] Start scanning
[Mar 14 21:01:10]  INFO [localhost] config: ./config.toml
[Mar 14 21:01:10]  INFO [localhost] Validating config...
[Mar 14 21:01:10]  INFO [localhost] Detecting Server/Container OS... 
[Mar 14 21:01:10]  INFO [localhost] Detecting OS of servers... 
[Mar 14 21:01:10]  INFO [localhost] (1/1) Detected: library: ubuntu 20.04
[Mar 14 21:01:10]  INFO [localhost] Detecting OS of containers... 
[Mar 14 21:01:10]  INFO [localhost] Checking Scan Modes... 
[Mar 14 21:01:10]  INFO [localhost] Detecting …
```
> feat(library): add auto detect library

- .dockerignore
- .github/workflows/docker-publish.yml
- contrib/Dockerfile
When master and tag are pushed, a Docker image for FutureVuls is also created.
```console
$ docker build -t vuls/fvuls -f ./contrib/Dockerfile .
$ docker run -it --rm vuls/fvuls /bin/sh
/vuls # vuls -v
vuls v0.19.4 build-20220323_024728_a1cc152e
/vuls # trivy-to-vuls version
trivy-to-vuls-v0.19.4-build-20220323_024821_a1cc152e
/vuls # future-vuls version
future-vuls-v0.19.4-build-20220323_025131_a1cc152e
```
> chore: add fvuls image

- scanner/scanner.go
I implemented Server mode for SUSE with `text/plain`.
(`application/json` has already been implemented)
I run vuls with Server mode and scan SLES in practice.
The actual requst and response are below.
I checked that packages are scanned and CVES are detected expectedly.
<details><summary>Request</summary><div>
```
curl -X POST -H "Content-Type: text/plain" -H "X-Vuls-OS-Family: suse.linux.enterprise.server" -H "X-Vuls-OS-Release: 12.5" -H "X-Vuls-Kernel-Release: 4.12.14-122.103-default" -H "X-Vuls-Server-Name: ip-192-168-0-181" --data-binary "
libsmbconf0 0 4.10.18+git.339.c912385a5e1 3.41.1 x86_64
mozilla-nspr 0 4.32 19.18.1 x86_64 …
```
> feat: support server scan for suse with text/plain

- .golangci.yml
- GNUmakefile
- contrib/Dockerfile
- detector/util.go
- gost/gost.go
- oval/pseudo.go
- reporter/util.go
- reporter/util_test.go
- scanner/redhatbase.go
Fixed a lint error caused by revive and golangci-lint.
Reviewed the tasks in GNUmakefile and changed (pre)test to be done in all instead of build.
Also, Trivy binary is now included with fvuls image.
```console
$ docker run -it --rm vuls/fvuls /bin/sh
/vuls # ls /usr/local/bin
future-vuls    trivy          trivy-to-vuls  vuls
```
```console
$ make test
$ make golangci
```
> chore: fix lint error

- detector/detector.go
Currently, we use '.ScanndeBy' in order to judge the result was scanned by trivy. But '.ScannedBy' may have been changed when the result was  scanned by trivy indirectly. So I guess that we should use '.ScannedVia' to judge it is scanned by trivy.  
refs:  https://github.com/future-architect/vuls/pull/1444
Run at local
> refactor: judge by scannedVia

- scanner/base.go
Fix getting wp core version string via ssh.
Expected: "5.7.4"
Actual:  "sudo: unable to resolve host ubuntu\n5.7.4"
```
config.toml
[servers.ubuntu]
host        = "192.0.2.1"
port        = "22"
user        = "vuls"
keyPath     = "/var/db/vuls/.ssh/id_rsa"
scanModules = ["wordpress"]
[servers.ubuntu.wordpress]
cmdPath     = "/usr/local/bin/wp"
osUser      = "vuls"
docRoot     = "/var/www/html"
```
```
$ vuls scan ubuntu
$ cat results/current/ubuntu.json
...
"WordPressPackages": [
{
"name": "core",
"version": "sudo: unable to resolve host ubuntu\n5.7.4",
"type": "core"
},
```
scan in debug mode
```
$ vuls scan -debug  ubuntu
...
[Dec 16 21:26:28] DEBUG [localhost] Executing... sudo -u vuls -i -- /usr/local/bin/wp core version --path=/var/www/html --allow-root
[Dec 16 …
```
> fix getting wp core version string via ssh

- config/config.go
- config/tomlloader.go
- config/tomlloader_test.go
- go.mod
- go.sum
- subcmds/configtest.go
- subcmds/discover.go
- subcmds/scan.go
The host section of config.toml can be written in CIDR Range.
This allows a single server section to represent a single network, and when users and keys are common, server sections that were written separately can be combined into one.
```console
$ vagrant up
$ ssh vagrant@192.168.56.10 -i ../../.ssh/id_rsa
$ ssh vagrant@192.168.56.11 -i ../../.ssh/id_rsa
```
`../../.ssh/id_rsa.pub` should be changed according to your environment.
- Vagrantfile
```ruby
Vagrant.configure("2") do |config|
config.vm.define "host1" do |host1|
host1.vm.box = "ubuntu/focal64"
host1.vm.network :private_network, ip: "192.168.56.10"
end
config.vm.define "host2" do |host2|
host2.vm.box = "ubuntu/focal64"
host2.vm.network :private_network, ip: "192.168.56.11"
end
if Vagrant.has_plugin?("vagrant-vbguest") …
```
> feat(config): support CIDR range

- Dockerfile
- config/os.go
- config/os_test.go
support Alpine Linux 3.16.
```console
$ vuls scan
[Jun 14 22:45:16]  INFO [localhost] vuls-v0.19.7-build-20220614_225652_f571918c
[Jun 14 22:45:16]  INFO [localhost] Start scanning
[Jun 14 22:45:16]  INFO [localhost] config: ./config.toml
[Jun 14 22:45:16]  INFO [localhost] Validating config...
[Jun 14 22:45:16]  INFO [localhost] Detecting Server/Container OS... 
[Jun 14 22:45:16]  INFO [localhost] Detecting OS of servers... 
[Jun 14 22:45:16]  INFO [localhost] (1/1) Detected: vuls-target: alpine 3.16.0
[Jun 14 22:45:16]  INFO [localhost] Detecting OS of containers... 
[Jun 14 22:45:16]  INFO [localhost] Checking Scan Modes... 
[Jun 14 22:45:16]  INFO [localhost] Detecting Platforms... 
[Jun 14 22:45:16]  INFO [localhost] (1/1) vuls-target is running on other
[Jun 14 22:45:16]  INFO …
```
> feat(os): support Alpine Linux 3.16

- scanner/scanner.go
- scanner/scanner_test.go
Detects cases where SSH fails due to a mismatch between the host key in known_host and the host key provided by the server.
```console
$ docker run --rm -itd -p 2222:22 --name vuls-target vuls-target:ubuntu22.04
$ ssh vuls-target
$ docker stop vuls-target
$ docker run --rm -itd -p 2222:22 --name vuls-target vuls-target:debian11
$ ssh vuls-target
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is …
```
> feat(scanner): detect host key change

- go.mod
- go.sum
- gost/microsoft.go
- models/vulninfos.go
- subcmds/discover.go
Import gost:MaineK00n/new-windows and use DetectCVE to detect CVEs.
> feat(ms): import gost:MaineK00n/new-windows

- gost/microsoft.go
It is rare for the same KB to be added to the distro advisory by multiple products because the KB is basically filtered by Product. However, when scanning without determining the OS, duplicate distro advisories may be added. This PR corrects this problem and makes the KBs added to the distro advisory unique.
> fix(ms): remove duplicate advisories

- models/library.go
- scanner/base.go
When vulnerability was detected in pnpm-lock.yaml and *.deps.json, the key of libraryFixedIns in the report result was not set. 
This PR fixes that.
Also, pnpm-lock.yaml and *.deps.json are added to the target of findLock.
The key of libraryFixedIns in the report result is filled.
```json
"scannedCves": {
"CVE-2021-23566": {
"cveID": "CVE-2021-23566",
"confidences": [
{
"score": 100,
"detectionMethod": "TrivyMatch"
}
],
"libraryFixedIns": [
{
"name": "nanoid",
"fixedIn": "3.1.31",
"path": "/home/mainek00n/github/github.com/MaineK00n/vuls/integration/data/lockfile/pnpm-lock.yaml"
}
]
},
"GHSA-5crp-9r3c-p9vr": {
"cveID": "GHSA-5crp-9r3c-p9vr",
"confidences": [
{
"score": 100,
"detectionMethod": "TrivyMatch"
}
],
"libraryFixedIns": [
{
"name": "Newtonsoft.Json",
"fixedIn": "13.0.1",
"path": …
```
> fix(library): fill libraryFixedIns{}.key in ftypes.Pnpm and ftypes.DotNetCore

- config/os.go
- config/os_test.go
Rocky Linux 9.0 is now GA and EOL is set.
https://rockylinux.org/news/rocky-linux-9-0-ga-release/
```console
$ vuls scan
[Jul 19 10:00:41]  INFO [localhost] vuls-v0.19.8-build-20220719_095936_d1a617c
[Jul 19 10:00:41]  INFO [localhost] Start scanning
[Jul 19 10:00:41]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Jul 19 10:00:41]  INFO [localhost] Validating config...
[Jul 19 10:00:41]  INFO [localhost] Detecting Server/Container OS... 
[Jul 19 10:00:41]  INFO [localhost] Detecting OS of servers... 
[Jul 19 10:00:42]  INFO [localhost] (1/1) Detected: vuls-target: rocky 9.0
[Jul 19 10:00:42]  INFO [localhost] Detecting OS of containers... 
[Jul 19 10:00:42]  INFO [localhost] Checking Scan Modes... 
[Jul 19 10:00:42]  INFO [localhost] Detecting …
```
> chore(rocky): set Rocky Linux 9 EOL

- cwe/cwe.go
add cwe top25 2022.
```console
$ vuls report --format-full-text
...
+------------------------+----------------------------------------------------------------------------------+
| CVE-2020-25743         | UNFIXED                                                                          |
+------------------------+----------------------------------------------------------------------------------+
| Max Score              | 3.9 LOW (ubuntu)                                                                 |
| nvd                    | 3.2/CVSS:3.1/AV:L/AC:L/PR:H/UI:N/S:C/C:N/I:N/A:L LOW                             |
| jvn                    | 3.2/CVSS:3.0/AV:L/AC:L/PR:H/UI:N/S:C/C:N/I:N/A:L LOW                             |
| ubuntu                 | 0.1-3.9 LOW …
```
> feat(cwe): add cwe top25 2022

- scanner/base.go
Enable to get EC2 instance ID by IMDSv2.
Tried locally the commands that are executed.
```shell
$ curl -X PUT --max-time 1 --noproxy 169.254.169.254 -H "X-aws-ec2-metadata-token-ttl-seconds: 300" http://169.254.169.254/latest/ api/token
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
$ curl -H "X-aws-ec2-metadata-token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" --max-time 1 --noproxy 169.254.169. 254 http://169.254.169.254/latest/meta-data/instance-id
i-XXXXXXXXXXXXXXXXX
```
> Fix func to get EC2 instance ID by IMDSv2.

- scanner/base.go
lockfile scan searches for the target lockfile and retrieves its contents from the scan destination.
Until now, even in fast-root mode, all command execution has been done as the executing user.
This PR grants privileges to the command according to its execution mode.
```console
$ vagrant ssh
vagrant@ubuntu-focal:~$ find / -type f -and -name "Cargo.lock" 2>&1 | grep -v "find:"
vagrant@ubuntu-focal:~$ sudo find / -type f -and -name "Cargo.lock" 2>&1 | grep -v "find:"
/root/Cargo.lock
```
- config.toml
```toml
[servers.vagrant]
host = "127.0.0.1"
port = "2222"
user = "vagrant"
keyPath            = "/home/mainek00n/github/github.com/MaineK00n/vuls-targets-docker/.ssh/id_rsa"
scanModules = ["lockfile"]
findLock = true
```
- before
```console
$ vuls scan
[Aug  8 …
```
> fix(lockfiles): fix privileges in lockfile scan

- README.md
Invitation to vuls-github slack does not seem to be working properly.
This PR will change from using the google form to using the Slack invite link.
> docs: update slack invite URL

- detector/detector.go
When family is windows, always set isPkgCvesDetactable to true.
> fix(ms): always sets isPkgCvesDetactable to true

- scanner/redhatbase.go
Error in identifying the OS in the scan process when an empty /etc/redhat-release exists on the server.
```
[root@ip-192-168-0-61 etc]# touch /etc/redhat-release
```
```
./vuls scan ama
[Sep 29 10:23:25]  INFO [localhost] vuls-v0.20.3-build-20220929_101358_379fc8a
[Sep 29 10:23:25]  INFO [localhost] Start scanning
[Sep 29 10:23:25]  INFO [localhost] config: /home/ubuntu/go/src/github.com/future-architect/vuls/config.toml
[Sep 29 10:23:25]  INFO [localhost] Validating config...
[Sep 29 10:23:25]  INFO [localhost] Detecting Server/Container OS... 
[Sep 29 10:23:25]  INFO [localhost] Detecting OS of servers... 
[Sep 29 10:23:26] ERROR [localhost] (1/1) Failed: ama, err: [Failed to parse /etc/redhat-release. r.Stdout: :
github.com/future-architect/vuls/scanner.detectRedhat …
```
> fix(scan): detect AL2 even when empty /etc/redhat-release

- saas/uuid.go
```
panic: runtime error: comparing uncomparable type config.PortScanConf [recovered]
panic: runtime error: comparing uncomparable type config.PortScanConf
goroutine 1 [running]:
github.com/BurntSushi/toml.(*Encoder).safeEncode.func1()
/home/runner/go/pkg/mod/github.com/!burnt!sushi/toml@v1.2.0/encode.go:152 +0x78
panic({0xece920, 0xc002cb4380})
/opt/hostedtoolcache/go/1.18.6/x64/src/runtime/panic.go:838 +0x207
github.com/BurntSushi/toml.isEmpty({0xf77940?, 0xc000078460?, 0x0?})
/home/runner/go/pkg/mod/github.com/!burnt!sushi/toml@v1.2.0/encode.go:656 +0xf9
github.com/BurntSushi/toml.(*Encoder).eStruct.func2({0xc0000a5380?, 0x3, 0xfc7100?})
/home/runner/go/pkg/mod/github.com/!burnt!sushi/toml@v1.2.0/encode.go:507 +0x23e
github.com/BurntSushi/toml.(*Encoder).eStruct(0xc0031b8e00, …
```
> fix(saas): panic: runtime error: comparing uncomparable type config.PortScanConf

- go.mod
- go.sum
https://github.com/vulsio/go-cve-dictionary/pull/283
```
$ grep -C1 forti config.toml
[servers.forti]
cpeNames = ["cpe:/h:fortinet:fortigate-100d:v6.2.9"]
$ ./vuls scan forti
$./vuls report
forti (pseudo)
==============
Total: 2 (Critical:0 High:0 Medium:2 Low:0 ?:0)
0/0 Fixed, 1 poc, 0 exploits, cisa: 0, uscert: 0, jpcert: 0 alerts
0 installed
+---------------+------+--------+-----+-----------+---------+----------+
|    CVE-ID     | CVSS | ATTACK | POC |   ALERT   |  FIXED  | PACKAGES |
+---------------+------+--------+-----+-----------+---------+----------+
| CVE-2012-4948 |  5.3 |  AV:A  |     |           |         |          |
+---------------+------+--------+-----+-----------+---------+----------+
| CVE-2013-1414 |  5.1 |  AV:N  | POC |           |         | …
```
> fix(cpescan): match if affected version is NA

- config/os.go
- config/os_test.go
set Ubuntu 22.10
```console
$ vuls scan
[Oct 27 02:14:50]  INFO [localhost] vuls-v0.20.5-build-20221027_015659_6eb4c5a
[Oct 27 02:14:50]  INFO [localhost] Start scanning
[Oct 27 02:14:50]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Oct 27 02:14:50]  INFO [localhost] Validating config...
[Oct 27 02:14:50]  INFO [localhost] Detecting Server/Container OS... 
[Oct 27 02:14:50]  INFO [localhost] Detecting OS of servers... 
[Oct 27 02:14:50]  INFO [localhost] (1/1) Detected: vuls-target: ubuntu 22.10
[Oct 27 02:14:50]  INFO [localhost] Detecting OS of containers... 
[Oct 27 02:14:50]  INFO [localhost] Checking Scan Modes... 
[Oct 27 02:14:50]  INFO [localhost] Detecting Platforms... 
[Oct 27 02:14:52]  INFO [localhost] (1/1) vuls-target is running on …
```
> chore(ubuntu): set Ubuntu 22.10 EOL

- config/config.go
- logging/logutil.go
- scanner/base.go
- scanner/debian.go
- scanner/executil.go
- subcmds/discover.go
When I ran config.toml with FindLock specified, it found lock files, jars, etc., in all directories under root. Unfortunately, due to a rough implementation, the contents of the detected files were stored on a Map, which increased memory usage when the number of detected files was large. In some cases, this resulted in Kernel Out of memory.
- before: Res: 707MB
```
$ /usr/bin/time -v ./vuls scan localhost
....
Maximum resident set size (kbytes): 707428
....
```
- after: Res: 250MB
```
$ /usr/bin/time -v ./vuls scan localhost
....
Maximum resident set size (kbytes): 249820
....
```
- Allow FindLockDirs to be specified.
Enabled to specify multiple directories to be detected.
> fix(libscan): delete map that keeps all file contents detected by FindLock to save memory

- GNUmakefile
- models/library.go
- scanner/base.go
support conan.lock C/C++
|file|master|bc8c562cff0c1a1dc278fd16743419416eb8baf9|
|-------------------------------|------|------|
| **conan.json**                    | 0    | 1    |
| amazon_2.json                 | 392  | 392  |
| bundler.json                  | 80   | 80   |
| cargo.json                    | 27   | 27   |
| centos_7.json                 | 392  | 392  |
| composer.json                 | 19   | 19   |
| debian_10.json                | 1001 | 1001 |
| dotnet-deps.json              | 1    | 1    |
| gobinary.json                 | 3    | 3    |
| gomod.json                    | 13   | 13   |
| gosum.json                    | 56   | 56   |
| gradle.json                   | 68   | 68   |
| jar.json                      | 4    | 4    |
| jvn_vendor_product.json       | 1    | 1 …
> feat(libscan): support conan.lock C/C++

- reporter/email.go
This PR adds Criticals to the email summary.
Fixes #1564 
I've been trying to get set up to run the integration tests, but haven't been successful in running them yet. I can switch this to a WIP until I'm able to run the tests if you'd prefer.
> fix(report/email): add Critical to email summary

- cache/bolt.go
- config/config.go
- detector/detector.go
- detector/github.go
- detector/wordpress.go
- logging/logutil.go
- models/github.go
- models/scanresults.go
- models/vulninfos.go
- reporter/sbom/cyclonedx.go
- reporter/slack.go
- reporter/util.go
- scanner/executil.go
- scanner/freebsd.go
- scanner/redhatbase.go
- scanner/redhatbase_test.go
- tui/tui.go
- When you integrate with GitHub Security Alerts, Vuls did NOT take non-vulnerable packages in SBOM
- From now on SBOM reporting, it fetches Dependency graph together with GitHub Security Alerts
- And that becomes components and dependencies
- Also, Package URL of vulnerable packages are linked to vulnerabilities in affects
```
or 
```
https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph
> feat(report): Include dependencies into scan result and cyclondex for supply chain security on Integration with GitHub Security Alerts

- detector/detector.go
- detector/github.go
- models/github.go
- models/vulninfos.go
- reporter/sbom/cyclonedx.go
In case of multiple repository scan, dependency graph is included INCORRECTLY, because last scanned repo overwrite the others.
This PR tidies dependency by repository and manifest file, and set which repo the component come from in SBOM.
```
or 
```
> fix(report): tidy dependencies for multiple repo on integration with GSA

- gost/ubuntu.go
- gost/ubuntu_test.go
gost/Ubuntu.ConvertToModel() is public method now
> fix(ubuntu): dependency problem

- detector/util.go
- models/cvecontents.go
- models/cvecontents_test.go
- models/vulninfos.go
- reporter/util.go
CVSS information and Primary Src of Ubuntu vulnerabilities detected by Gost are now displayed correctly.
> fix: use GetCveContentTypes instead of NewCveContentType

- config/os.go
- config/os_test.go
- oval/redhat.go
- oval/util.go
- scanner/redhatbase.go
support Amazon Linux 2023
```console
$ docker build -t vuls-target:amzn2023 -f Dockerfile .
$ docker run --rm -itd -p 2222:22 --name vuls-target vuls-target:amzn2023
$ ssh -i /home/mainek00n/.ssh/id_rsa -p 2222 root@127.0.0.1
[root@51484e96c59a ~]# dnf install -y vim-common-2:9.0.1160-1.amzn2023.0.2.x86_64
[root@51484e96c59a ~]# exit
$ vuls scan
...
[Mar 16 16:55:03]  INFO [localhost] Validating config...
[Mar 16 16:55:03]  INFO [localhost] Detecting Server/Container OS... 
[Mar 16 16:55:03]  INFO [localhost] Detecting OS of servers... 
[Mar 16 16:55:03]  INFO [localhost] (1/1) Detected: docker: amazon 2023
[Mar 16 16:55:03]  INFO [localhost] Detecting OS of containers... 
[Mar 16 16:55:03]  INFO [localhost] Checking Scan Modes... 
[Mar 16 16:55:03]  INFO [localhost] Detecting …
```
> feat(os): support Amazon Linux 2023

- scanner/scanner.go
- scanner/windows.go
- scanner/windows_test.go
support installationType Domain Controller
- systeminfo.txt
```txt
Host Name:                 vuls
OS Name:                   Microsoft Windows Server 2019 Datacenter
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Primary Domain Controller
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00430-00000-00000-AA602
Original Install Date:     1/16/2023, 10:04:07 AM
System Boot Time:          3/28/2023, 8:37:14 AM
System Manufacturer:       Microsoft Corporation
System Model:              Virtual Machine
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
[01]: Intel64 Family 6 Model 85 …
```
> fix(scanner/windows): support installationType Domain Controller

- config/config.go
- config/config_windows.go
- scanner/base.go
- subcmds/discover.go
Support for environments where sudo cannot be used or when the shell is csh, so that users of the following rental servers can use WordPress scan.
https://help.sakura.ad.jp/rs/2251/?article_anchor=js-nav-3
```console
$ pwd 
/home/mainek00n/github/github.com/MaineK00n/vuls-targets-docker/wordpress
$ vagrant up
$ vagrant ssh-config
Host default
HostName 127.0.0.1
User vagrant
Port 2222
UserKnownHostsFile /dev/null
StrictHostKeyChecking no
PasswordAuthentication no
IdentityFile /home/mainek00n/github/github.com/MaineK00n/vuls-targets-docker/wordpress/.vagrant/machines/default/virtualbox/private_key
IdentitiesOnly yes
LogLevel FATAL
$ ssh -i /home/mainek00n/github/github.com/MaineK00n/vuls-targets-docker/wordpress/.vagrant/machines/default/virtualbox/private_key -p 2222 vagrant@127.0.0.1
``` …
> feat(wp): support csh, no sudo scan

- scanner/scanner.go
The `G` option to the ssh command was introduced in OpenSSH 6.8.
Under OpenSSH 6.8, there was a issue that prevented scanning even though the SSH connection was properly configured.
With this PR, when G is an unknown option (= less than OpenSSH 6.8), SSH configuration validation is skipped.
>  * ssh(1): Add a -G option to ssh that causes it to parse its
configuration and dump the result to stdout, similar to "sshd -T".
REF: https://www.openssh.com/txt/release-6.8
Fixes #1631 
```console
root@1e3a45606d6c:/# ssh -V
OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.13, OpenSSL 1.0.1f 6 Jan 2014
root@1e3a45606d6c:/# ssh -G 127.0.0.1
unknown option -- G
usage: ssh [-1246AaCfgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
[-D [bind_address:]port] [-E log_file] [-e escape_char]
[-F configfile] [-I pkcs11] …
```
> feat(scanner): skip ssh config validation if G option is unknown option

- scanner/amazon.go
In amazon linux 2022, 2023, repoquery is provided by dnf-utils, not yum-utils.
```
$ vuls configtest
[Apr 10 09:00:11]  INFO [localhost] vuls-0.23.0-abdb081af78974b6650cc9f00cfabecea8a67703-2023-04-04T09:50:17Z
[Apr 10 09:00:11]  INFO [localhost] Validating config...
[Apr 10 09:00:11]  INFO [localhost] Detecting Server/Container OS... 
[Apr 10 09:00:11]  INFO [localhost] Detecting OS of servers... 
[Apr 10 09:00:11]  INFO [localhost] (1/1) Detected: docker: amazon 2022
[Apr 10 09:00:11]  INFO [localhost] Detecting OS of containers... 
[Apr 10 09:00:11]  INFO [localhost] Checking Scan Modes...
[Apr 10 09:00:11]  INFO [localhost] Checking dependencies...
[Apr 10 09:00:11] ERROR [docker] yum-utils is not installed
[Apr 10 09:00:11] ERROR [localhost] Error on docker, err: [yum-utils is not …
```
> fix(configtest): amazon linux 2022, 2023 require dnf-utils

- detector/github.go
- go.mod
Dependency Graph API calling has possibility of timeout when query touches a lot of data.
This PR decreases maximum response data of it by 1/5.
```
or 
```
`...`
> fix(detector/github): Dependency graph API calling uses smaller query at once to avoid timeout

- gost/debian.go
Fix the bug that causes false positives in the vulnerability detection process of Debian packages.
The issue occurs under the following conditions:
- When scanning Debian
- When scanning libraries
- During the vulnerability detection process of the package, searching the package list from Gost's vulnerability database. If the vulnerability detected in the library is included in Gost's search results
In this case, since the version comparison process for affected packages is skipped, it is considered detected in Gost as well
confirmed the diff in the Scan Result containing the following package information:
```
"runningKernel": {
"release": "8.19.0-23-cloud-amd64",
"version": "8.19.269-1",
"rebootRequired": false
},
"packages": {
"zlib1g": {
"name": "zlib1g",
"version": …
```
> fix(scan): false positives in Debian Pkg for CVE-IDs already detected by Trivy

- reporter/googlechat.go
- reporter/telegram.go
- scanner/windows.go
refactoring TelegramWriter, GoogleChatWriter
use regexp.MatchString instead of regexp.Match
remove unnecessary line break
> refactor(reporter): refactoring TelegramWriter, GoogleChatWriter

- scanner/redhatbase.go
fixing the order of determining what is the amazon linux version
https://github.com/future-architect/vuls/issues/1651
Bug fix
> fix order in identifying amazon linux version

- detector/github.go
Dependency graph API request can be failed for some reason like timeout at busy server time.
so this PR gives chances to retry request up to 3 times, and enhanced error handling a little bit.
```
or 
```
#1642
> fix(detector/github): Github dependency graph API request will be retried on error

- go.mod
- go.sum
Because the version of the goval-dictionary specified in go.mod was out of date, 2023 was not recognized and was always determined to be 1.
https://github.com/vulsio/goval-dictionary/compare/v0.8.2...v0.8.3#diff-30c25f2a7d8ae335d2aada4b0a6013ad9d159595bb6a2a14b1d0022451b6753fR123-R125
Fixes #1670 
Since it is determined to be 1, there are as many as 1587 OVAL defs in the before case.
```console
$ vuls report
[May  2 11:57:22]  INFO [localhost] vuls-v0.23.1-build-20230502_114921_3cc7e92
...
[May  2 11:57:22]  INFO [localhost] OVAL amazon 2023 found. defs: 1587
[May  2 11:57:22]  INFO [localhost] OVAL amazon 2023 is fresh. lastModified: 2023-05-02T11:52:56+09:00
[May  2 11:57:22]  INFO [localhost] docker: 0 CVEs are detected with OVAL
[May  2 11:57:22]  INFO [localhost] docker: 0 unfixed …
```
> chore(deps): update goval-dictionary v0.8.3

- config/os.go
- config/os_test.go
- gost/debian.go
- gost/debian_test.go
- scanner/base.go
because we now rely only in gost and not oval... and debian security tracker has data about debian 12 we can support it
support debian 12 in gost
```console
$ vuls scan
[May 13 00:11:58]  INFO [localhost] vuls-v0.23.2-build-20230513_005405_cf5e1bb
[May 13 00:11:58]  INFO [localhost] Start scanning
[May 13 00:11:58]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[May 13 00:11:58]  INFO [localhost] Validating config...
[May 13 00:11:58]  INFO [localhost] Detecting Server/Container OS... 
[May 13 00:11:58]  INFO [localhost] Detecting OS of servers... 
[May 13 00:11:58]  INFO [localhost] (1/1) Detected: vagrant: debian 12
[May 13 00:11:58]  INFO [localhost] Detecting OS of containers... 
[May 13 00:11:58]  INFO [localhost] Checking Scan Modes... 
[May …
```
> feat(os): support debian 12

- detector/github.go
Despite PR #1642, the Dependency graph API call times out. This issue occurs specifically on a big repository that contains numerous manifest files and dependencies.
It suggests the need to further reduce the amount of data per page.
And I have resolved the issue by properly initializing the `graph` variable upon retrying in #1650.
```
or 
```
- #1642 
- #1650
> fix(detector/github): Dependency graph API touches fewer data per page than before

- detector/github.go
I have made enhancements to the timeout retry mechanism in the Dependency Graph API by reducing the number of dependencies to be fetched per retry.
```
or 
```
- #1654
> fix(detector/github): Enhance the dependency graph API call on the big repository

- contrib/future-vuls/pkg/fvuls/fvuls.go
- contrib/trivy/parser/parser.go
Fix error log when uploading results of trivy runs using trivy-to-vuls and future-vuls
previous errorlog
```
trivy image python:3.4-alpin -f json |./trivy-to-vuls parse --stdin | ./future-vuls upload --stdin --group-id 2603 --token fvgr-528ec289-2516-11ee-b1e6-0a58a9feac02 --uuid 506b2ede-ebf8-82da-f25f-43932a5d290
2023-09-22T16:05:28.733+0900	INFO	Vulnerability scanning is enabled
2023-09-22T16:05:28.733+0900	INFO	Secret scanning is enabled
2023-09-22T16:05:28.733+0900	INFO	If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2023-09-22T16:05:28.733+0900	INFO	Please see also https://aquasecurity.github.io/trivy/v0.44/docs/scanner/secret/#recommendatio
n for faster secret detection
2023-09-22T16:05:30.510+0900	FATAL …
```
> refactor(contrib): Fix error log when trivy scan failed

- scanner/executil.go
Fixes #1713 
In this implementation, the length of strings such as servername, user name, port number, etc. is not constant and the scan fails when the controlpath becomes long.
https://github.com/future-architect/vuls/blob/a23abf48fd52e0cffa0fd0053908152755b63c22/scanner/executil.go#L216
> [TOKENS](https://man.openbsd.org/ssh_config.5#TOKENS)
...
%C
Hash of %l%h%p%r.
...
%p
The remote port.
%r
The remote username.
...
CertificateFile, ControlPath, IdentityAgent, IdentityFile, KnownHostsCommand, LocalForward, Match exec, RemoteCommand, RemoteForward, RevokedHostKeys, and UserKnownHostsFile accept the tokens %%, %C, %d, %h, %i, %k, %L, %l, %n, %p, %r, and %u.
Therefore, by using hash of `%C` and hash of servername, the length of the socket filename is fixed to make this problem less likely …
> fix(scanner): fix socket file name length of SSH ControlPath

- server/server.go
Fixes #1704 
```console
$ vuls server -cvss-over=7.0
[Jul 19 20:19:08]  INFO [localhost] vuls-v0.23.3-build-20230719_201853_f9276a7
[Jul 19 20:19:08]  INFO [localhost] Validating config...
[Jul 19 20:19:08]  INFO [localhost] cveDict.type=sqlite3, cveDict.url=, cveDict.SQLite3Path=/usr/share/vuls-data/cve.sqlite3
[Jul 19 20:19:08]  INFO [localhost] ovalDict.type=sqlite3, ovalDict.url=, ovalDict.SQLite3Path=/usr/share/vuls-data/oval.sqlite3
[Jul 19 20:19:08]  INFO [localhost] gost.type=sqlite3, gost.url=, gost.SQLite3Path=/usr/share/vuls-data/gost.sqlite3
[Jul 19 20:19:08]  INFO [localhost] exploit.type=sqlite3, exploit.url=, exploit.SQLite3Path=/usr/share/vuls-data/go-exploitdb.sqlite3
[Jul 19 20:19:08]  INFO [localhost] metasploit.type=sqlite3, metasploit.url=, …
```
> fix(server): add filter cves

- .goreleaser.yml
- README.md
- config/os.go
- config/os_test.go
- constant/constant.go
- detector/detector.go
- scanner/base.go
- scanner/base_test.go
- scanner/freebsd.go
- scanner/freebsd_test.go
- scanner/macos.go
- scanner/macos_test.go
- scanner/scanner.go
Until Apple's security advisory is ready, NVD data will be used to support macOS vulnerability detection.
```console
$ vuls scan localhost
[Jul 25 05:56:21]  INFO [localhost] vuls-v0.23.3-build-20230725_031757_a23abf4
[Jul 25 05:56:21]  INFO [localhost] Start scanning
[Jul 25 05:56:21]  INFO [localhost] config: /Users/user/Downloads/config.toml
[Jul 25 05:56:21]  INFO [localhost] Validating config...
[Jul 25 05:56:21]  INFO [localhost] Detecting Server/Container OS... 
[Jul 25 05:56:21]  INFO [localhost] Detecting OS of servers... 
[Jul 25 05:56:21]  INFO [localhost] (1/1) Detected: localhost: macos 13.4.0
[Jul 25 05:56:21]  INFO [localhost] Detecting OS of containers... 
[Jul 25 05:56:21]  INFO [localhost] Checking Scan Modes... 
[Jul 25 05:56:21]  INFO [localhost] Detecting Platforms... …
```
> feat(macos): support macOS

- config/tomlloader.go
- reporter/util.go
- scanner/base.go
- tui/tui.go
`len` returns 0 if the slice is nil. From the Go specification [^1]:
> "1. For a nil slice, the number of iterations is 0."
Therefore, an additional `len(v) != 0` check for before the loop is unnecessary.
[^1]: https://go.dev/ref/spec#For_range
`make test`
> refactor: remove redundant `len` check

- contrib/future-vuls/README.md
- contrib/future-vuls/cmd/main.go
- contrib/future-vuls/pkg/config/config.go
- contrib/future-vuls/pkg/discover/discover.go
Changed `future-vuls discover` command to allow specifying community when running `snmp2cpe`.
Default is  `public`.
```
./future-vuls discover -h
discover hosts with CIDR range. Run snmp2cpe on active host to get CPE. Default outputFile is ./discover_list.toml
Usage:
future-vuls discover --cidr <CIDR_RANGE> --output <OUTPUT_FILE> [flags]
Examples:
future-vuls discover --cidr 192.168.0.0/24 --output discover_list.toml
Flags:
--cidr string           cidr range
--community string      snmp community name. default: public
-h, --help                  help for discover
--output string         output file
--snmp-version string   snmp version v1,v2c and v3. default: v2c
```
***Is this …
> fix(contrib/fvuls): Add flag to specify snmp community for future-vuls discover

- scanner/redhatbase.go
- scanner/redhatbase_test.go
I fixed a bug where a nil pointer exception occurred in needs-restarting when the path is empty ("").
```
time="Oct 13 15:28:21" level=debug msg="Executing... LANGUAGE=en_US.UTF-8 needs-restarting" 
time="Oct 13 15:28:30" level=debug msg="execResult: servername: \n  cmd: sudo LANGUAGE=en_US.UTF-8 needs-restarting\n  exitstatus: 0\n  stdout: 30020 : /usr/sbin/httpd -DFOREGROUND \n30170 : \n30399 : /usr/sbin/httpd -DFOREGROUND \n\n  stderr: \n  err: %!s(<nil>)" 
time="Oct 13 15:28:30" level=debug msg="Panic: runtime error: index out of range [0] with length 0 on ***" 
time="Oct 13 17:28:02" level=error msg="Timed out: ***\n    github.com/future-architect/vuls/scanner.parallelExec\n        /home/runner/work/futurevuls-backend/futurevuls-backend/scanner-src/scanner/executil.go:130" 
```
Run …
> fix(scan): fix nil poiter in needs-restarting

- config/os.go
- config/os_test.go
- go.mod
- go.sum
- gost/ubuntu.go
add ubuntu 23.10
```console
$ vuls scan
[Oct  3 00:40:42]  INFO [localhost] vuls-v0.24.3-build-20231019_014948_c02e9ab
[Oct  3 00:40:42]  INFO [localhost] Start scanning
[Oct  3 00:40:42]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Oct  3 00:40:42]  INFO [localhost] Validating config...
[Oct  3 00:40:42]  INFO [localhost] Detecting Server/Container OS... 
[Oct  3 00:40:42]  INFO [localhost] Detecting OS of servers... 
[Oct  3 00:40:43]  INFO [localhost] (1/1) Detected: docker: ubuntu 23.10
[Oct  3 00:40:43]  INFO [localhost] Detecting OS of containers... 
[Oct  3 00:40:43]  INFO [localhost] Checking Scan Modes... 
[Oct  3 00:40:43]  INFO [localhost] Detecting Platforms... 
[Oct  3 00:40:45]  INFO [localhost] (1/1) docker is running on other
[Oct …
```
> feat(ubuntu): add ubuntu 23.10(mantic)

- scanner/alma.go
- scanner/amazon.go
- scanner/centos.go
- scanner/debian.go
- scanner/fedora.go
- scanner/rhel.go
- scanner/rocky.go
- scanner/suse.go
Change the lsof cmd that should be executed successfully without a password.
```console
$ cat /etc/sudoers.d/vagrant
vagrant ALL=(ALL) NOPASSWD:SETENV: /usr/bin/apt-get update, /usr/bin/stat *, /usr/sbin/checkrestart, /bin/ls -l /proc/*/exe, /bin/cat /proc/*/maps, /usr/bin/lsof -i -P -n
$ vuls configtest
[Oct 18 18:08:57]  INFO [localhost] vuls-v0.24.3-build-20231019_024423_75e9883
[Oct 18 18:08:57]  INFO [localhost] Validating config...
[Oct 18 18:08:57]  INFO [localhost] Detecting Server/Container OS... 
[Oct 18 18:08:57]  INFO [localhost] Detecting OS of servers... 
[Oct 18 18:08:57]  INFO [localhost] (1/1) Detected: localhost: ubuntu 22.04
[Oct 18 18:08:57]  INFO [localhost] Detecting OS of containers... 
[Oct 18 18:08:57]  INFO [localhost] Checking Scan Modes...
[Oct 18 18:08:57] …
```
> fix(scanner): change lsof cmd that  should succeed without password

- scanner/debian.go
- scanner/debian_test.go
The repository for [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) has a different format for `apt-cache policy`.
```
$ LANGUAGE=en_US.UTF-8 apt-cache policy wget
wget:
Installed: 1.20.3-1ubuntu1
Candidate: 1.20.3-1ubuntu2
Version table:
1.20.3-1ubuntu2 500
500 http://ap-northeast-1.ec2.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
*** 1.20.3-1ubuntu1 500
500 http://ap-northeast-1.ec2.archive.ubuntu.com/ubuntu focal/main amd64 Packages
100 /var/lib/dpkg/status
```
All other packages have 5 fields separated by whitespace.
```
$ LANGUAGE=en_US.UTF-8 apt-cache policy nvidia-container-toolkit
nvidia-container-toolkit:
Installed: 1.14.3-1
Candidate: 1.14.3-1
Version table:
*** 1.14.3-1 500
500 …
```
> fix(scanner): parsing apt cache policy for nvidia-container-toolkit

- saas/saas.go
Added definition of the HTTPS_PROXY environment variable to load proxy settings into the aws sdk used for uploading scan results to S3.
To correct the following error.
`Failed to upload ...  dial tcp 3.5.156.15:443: i/o timeout`
> fix(subcmds/saas): Add env HTTPS_PROXY for aws sdk

- scanner/windows.go
When you specify a CabPath and scan, the Cab is extracted and saved to `C:\Windows\SoftwareDistribution\ScanFile\<Update Service.ServiceID>`.
To remove this, it is necessary to release the UpdateService, but that task was missing.
This PR adds the task.
```console
C:\Program Files\vuls>vuls scan
time="Nov 20 11:22:52" level=info msg="vuls--build-20230926_105414_f5d2fad"
time="Nov 20 11:22:52" level=info msg="Start scanning"
time="Nov 20 11:22:52" level=info msg="config: C:\\Program Files\\vuls\\config.toml"
time="Nov 20 11:22:52" level=info msg="Validating config..."
time="Nov 20 11:22:52" level=info msg="Detecting Server/Container OS... "
time="Nov 20 11:22:52" level=info msg="Detecting OS of servers... "
time="Nov 20 11:22:53" level=info msg="(1/1) Detected: localhost: windows Windows …
```
> fix(scanner/windows): remove unnecessary cab

- config/os.go
- config/os_test.go
Fixes #1796 
There are currently no errata for FreeBSD 14, so the number of detected cases is 0.
https://www.freebsd.org/releases/14.0R/errata/
```console
$ vuls scan
[Nov 25 08:21:06]  INFO [localhost] vuls-v0.24.6-build-20231125_081606_32a9cfa
[Nov 25 08:21:06]  INFO [localhost] Start scanning
[Nov 25 08:21:06]  INFO [localhost] config: /home/user/vuls/config.toml
[Nov 25 08:21:06]  INFO [localhost] Validating config...
[Nov 25 08:21:06]  INFO [localhost] Detecting Server/Container OS... 
[Nov 25 08:21:06]  INFO [localhost] Detecting OS of servers... 
[Nov 25 08:21:06]  INFO [localhost] (1/1) Detected: vagrant: freebsd 14.0-RELEASE
[Nov 25 08:21:06]  INFO [localhost] Detecting OS of containers... 
[Nov 25 08:21:06]  INFO [localhost] Checking Scan Modes... 
[Nov 25 08:21:06]  INFO …
```
> feat(os): add FreeBSD 14 EOL

- go.mod
- go.sum
- models/utils.go
Group CVSS and CWE in the NVD section in CveContent by source.
```console
"cveContents": {
"nvd": [
{
"type": "nvd",
"cveID": "CVE-2023-1194",
"title": "",
"summary": "An out-of-bounds (OOB) memory read flaw was found in parse_lease_state in the KSMBD implementation of the in-kernel samba server and CIFS in the Linux kernel. When an attacker sends the CREATE command with a malformed payload to KSMBD, due to a missing check of `NameOffset` in the `parse_lease_state()` function, the `create_context` object can access invalid memory.\nSe encontró una falla de lectura de memoria Out-Of-Bounds (OOB) en parse_lease_state en la implementación KSMBD del servidor samba en el kernel y CIFS en el kernel de Linux. Cuando un atacante envía el comando CREATE con un payload mal formada a KSMBD, debido a …
```
> feat(models/nvd): group by source

- scanner/redhatbase.go
When scanning for redhat, there was an error in the execution part of the following command.
```
dnf --nogpgcheck --cacheonly --color=never --quiet module list --enabled
```
The cacheonly flag was specified for this command, so that module information was retrieved by referencing the cache.
The scan was failing because the `dnf --nogpgcheck --cacheonly --color=never --quiet module list --enabled` was executed before the `yum makecache` command to create the cache was executed.
This problem does not occur if the cache is created before the scan.
```
[root@ip-192-168-0-193 vuls-saas]# yum clean all
Updating Subscription Management repositories.
25 files removed
[root@ip-192-168-0-193 vuls-saas]# ./vuls scan
[Dec 14 06:00:47]  INFO [localhost] vuls-v0.24.4-build-b9db541
[Dec 14 06:00:47] …
```
> fix(scanner): yum makecache was not working when scanning redhat

- go.mod
- go.sum
- reporter/sbom/cyclonedx.go
- This PR replaces #1809 for compatibility
- Array of `metadata.tools` is deprecated in CycloneDX spec v1.5
```
or 
```
check cyclondx
```
...
"metadata": {
"timestamp": "2023-05-30T13:02:36+09:00",
"tools": [
{
"vendor": "future-architect",
"name": "vuls",
"version": "-"
}
],
...
```
```
...
"metadata": {
"timestamp": "2024-01-12T13:44:56+09:00",
"tools": {
"components": [
{
"type": "application",
"author": "future-architect",
"name": "vuls",
"version": "-"
}
]
},
...
```
https://cyclonedx.org/docs/1.5/json/#metadata_tools
> chore(deps): bump github.com/CycloneDX/cyclonedx-go from 0.7.2 to 0.8.0

- config/windows.go
Removed cabPath validation for remote scanning using cab files
> feat(config/windows): remove unnecessary os.Stat() to cabPath

- contrib/trivy/parser/v2/parser_test.go
- contrib/trivy/pkg/converter.go
- models/packages.go
Fixes #1841 
In trivy v0.35.0, it was included in the os package version in the `(<epoch>:)<version>(-<release>)` format. However, in the latest version, epoch, version, and release are now stored separately.
In order to receive the latest trivy results correctly, the divided epoch, version, and release are combined and saved as version.
Also, the source package was saved only when the binary package name and source package name were different, but now the source package will always be saved.
- debian12.json
```json
{
"SchemaVersion": 2,
"CreatedAt": "2024-02-01T04:18:32.375239841+09:00",
"ArtifactName": "debian:12",
"ArtifactType": "container_image",
"Metadata": {
"OS": {
"Family": "debian",
"Name": "12.1"
},
"ImageID": "sha256:df89715852d4e9045673b3d22dc80b7846d563e18af1b14648d6bfe068391 …
```
> fix(contrib/trivy): fix convert for src package

- scanner/executil.go
- scanner/windows.go
- scanner/windows_test.go
Fixes #1835 
The issue of failing to identify the OS when the default shell when connecting via SSH is powershell.exe will be fixed by identifying the shell that executes the command and reviewing the escaping of each command.
```console
$ vuls scan
[Feb  2 12:10:40]  INFO [localhost] vuls-0.24.8-bbf53c7639b266e3a658e8f0a8b2ff7bf17e8e62-2023-12-17T20:41:46Z
[Feb  2 12:10:40]  INFO [localhost] Start scanning
[Feb  2 12:10:40]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Feb  2 12:10:40]  INFO [localhost] Validating config...
[Feb  2 12:10:40]  INFO [localhost] Detecting Server/Container OS... 
[Feb  2 12:10:40]  INFO [localhost] Detecting OS of servers... 
[Feb  2 12:10:44]  INFO [localhost] (1/1) Detected: vagrant: windows Windows Server 2022 …
```
> fix(scanner/windows): support when default shell is powershell

- .github/workflows/codeql-analysis.yml
install go version of go.mod
>    2024/02/28 05:28:21 Autobuilder was built with go1.21.7, environment has go1.20.14
2024/02/28 05:28:21 LGTM_SRC is /home/runner/work/vuls/vuls
2024/02/28 05:28:21 Found go.mod, enabling go modules
2024/02/28 05:28:21 The go.mod file requires version v1.21 of Go, but version v1.20.14 is installed. Consider adding an actions/setup-go step to your workflow.
go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20
https://github.com/future-architect/vuls/actions/runs/8075744361/job/22063101584?pr=1856
>    2024/02/28 07:07:58 Autobuilder was built with go1.21.7, environment has go1.21.7
https://github.com/future-architect/vuls/actions/runs/8076575378/job/22065274478?pr=1858
***Is this …
> fix(ci): use go version of go.mod

- detector/javadb/javadb.go
- detector/library.go
- go.mod
- models/library.go
Because the `detector` package may be used as library-like way in some places.
Avoid to use sync.Once in trivy's java db Updator.
Instead, Use trivy-java-db's interface functions directly.
Manually.
Preparation: Execute vuls scan with two servers with JAR libs.
```
% CGO_ENABLED=0 go run cmd/vuls/main.go scan -config ./integration/int-config.toml jar jar-wrong-name-log4j-core
[Mar  4 17:12:01]  INFO [localhost] vuls-`make build` or `make install` will show the version-
[Mar  4 17:12:01]  INFO [localhost] Start scanning
[Mar  4 17:12:01]  INFO [localhost] config: ./integration/int-config.toml
[Mar  4 17:12:01]  INFO [localhost] Validating config...
[Mar  4 17:12:01]  INFO [localhost] Detecting Server/Container OS...
[Mar  4 17:12:01]  INFO [localhost] Detecting OS of servers...
[Mar  4 …
```
> Avoid to use sync.Once inside trivy javadb Updater

- detector/library.go
- models/library.go
move library.Scan from models/library.go to detector/library.go to satisfy the build constraints.
https://github.com/future-architect/vuls/actions/runs/8152149470/job/22281138184
```console
$ make build-scanner 
CGO_ENABLED=0 go build -tags=scanner -a -ldflags "-X 'github.com/future-architect/vuls/config.Version=v0.24.9' -X 'github.com/future-architect/vuls/config.Revision=build-20240305_161924_54dae08'" -o vuls ./cmd/scanner
package github.com/future-architect/vuls/cmd/scanner
imports github.com/future-architect/vuls/subcmds
imports github.com/future-architect/vuls/models
imports github.com/future-architect/vuls/detector/javadb: build constraints exclude all Go files in /home/mainek00n/github/github.com/MaineK00n/vuls/detector/javadb
make: *** …
```
> fix(detector): library.Scan move to detector

- contrib/trivy/parser/v2/parser_test.go
- contrib/trivy/pkg/converter.go
- models/library.go
- models/library_test.go
- scanner/library.go
We have [updated the version of Trivy used in Vuls to 0.49.1.](https://github.com/future-architect/vuls/pull/1806)
As a result, the results of filesystem scan and container image scan now include a Package URL.
Therefore, we will also include Package URL in the results of trivy-to-vuls and lockfile scan.
Manually.
```bash
$ trivy -q fs -f json poetry.lock --list-all-pkgs | CGO_ENABLED=0 go run contrib/trivy/cmd/main.go parse --stdin
```
The PackageURL does not exist in the libraries.Libs.
<details close>
<summary>before</summary>
```json
"libraries": [
{
"Type": "poetry",
"Libs": [
{
"Name": "anyio",
"Version": "3.7.1",
"FilePath": ""
},
{
"Name": "appnope",
"Version": "0.1.3",
"FilePath": ""
},
{
"Name": "argon2-cffi",
"Version": "21.3.0",
"FilePath": ""
},
etc...
]
}
]
```
</details> …
> feat(PackageURL):add package URL for library scan result

- scanner/scanner.go
When running `vuls scan`, there was a difference in behavior between cases where all servers failed and cases where only some servers failed in terms of generating results. 
In this PR, we modify it to output results for all servers regardless of the situation.
In the display of the Scan Summary, you can confirm the generation of results.
```console
$ vuls scan
[Mar  6 18:53:41]  INFO [localhost] vuls-v0.24.9-build-20240306_185212_bf14b5f
[Mar  6 18:53:41]  INFO [localhost] Start scanning
[Mar  6 18:53:41]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Mar  6 18:53:41]  INFO [localhost] Validating config...
[Mar  6 18:53:41]  INFO [localhost] Detecting Server/Container OS... 
[Mar  6 18:53:41]  INFO [localhost] Detecting OS of servers... 
[Mar  6 …
```
> fix(scanner): output all results even if all fail

- .github/workflows/goreleaser.yml
After trivy update (#1806), build time gets longer and release build failed
https://github.com/future-architect/vuls/actions/runs/8196741906
This PR changes timeout of release build by goreleaser from default 30 min to 60 min.
beta builds have passed: https://github.com/future-architect/vuls/actions/runs/8199170928
> fix(build): Change timeout to 60 minutes

- config/os.go
- config/os_test.go
- oval/oval.go
- oval/util.go
- scanner/redhatbase.go
It seems that the latest Amazon Linux version has been changed to major.minor.patch version instead of major version.
ref: https://github.com/aquasecurity/trivy-db/issues/390
Security advisories and EOL are in major version units, so the major version is always used for detection and EOL checks.
```console
$ vuls scan
[Mar 15 17:27:06]  INFO [localhost] vuls-v0.25.1-build-20240315_172553_426eb53
[Mar 15 17:27:06]  INFO [localhost] Start scanning
[Mar 15 17:27:06]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Mar 15 17:27:06]  INFO [localhost] Validating config...
[Mar 15 17:27:06]  INFO [localhost] Detecting Server/Container OS... 
[Mar 15 17:27:06]  INFO [localhost] Detecting OS of servers... 
[Mar 15 17:27:07]  INFO [localhost] (1/1) Detected: …
```
> fix(amazon): use major version for checking eol, security advisories

- detector/library.go
Before this pull request, JAR-like files' names and versions are partially correct and partially wrong, beause correction by Trivy's Java DB is performed in `vuls report` phase.
For example, one entry in "libraries" list of scan result looks like below
```json
{
"Name": ":spring-web",  ## <== NOT correct, does not have organization (before colon)
"Version": "3.2.18.RELEASE",
"PURL": "",
"FilePath": "home/shino/g/vuls/integration/data/lockfile/juddiv3-war-3.3.5.war/WEB-INF/lib/spring-web-3.2.18.RELEASE.jar",
"Digest": "sha1:bc0bdade0a7a52b8fae88e1febc8479383a2acad"
},
```
and libraryFixedIns of `vuls report` result 
```json
"libraryFixedIns": [
{
"key": "java",
"name": "org.springframework:spring-web",  ## <== Correct name, thanks to Java DB!
"fixedIn": "6.0.0",
"path": …
```
> feat(detector/library): update JAR-like files' Name/Version in library list

- detector/wordpress.go
- detector/wordpress_test.go
- models/cvecontents.go
There are two versions of wpscan:
・Free researcher version
・Paid enterprise version
This PR have accommodated the values obtained in the enterprise version.
And changed the structure that is only used for unmarshal of json in wpscan to unexported.
I ran `make test` in the local environment.
And I have also confirmed the passing of the following tests added this time.
```sh
$ go test -v -run Test_convertToVinfos
=== RUN   Test_convertToVinfos
=== RUN   Test_convertToVinfos/WordPress_vulnerabilities_Enterprise
=== RUN   Test_convertToVinfos/WordPress_vulnerabilities_Researcher
--- PASS: Test_convertToVinfos (0.00s)
--- PASS: Test_convertToVinfos/WordPress_vulnerabilities_Enterprise (0.00s)
--- PASS: …
```
> feat(wpscan): support enterprise feature

- config/smtpconf.go
- reporter/email.go
- subcmds/discover.go
TLSInsecureSkipVerify added to SMTPConf struct
```
TLSInsecureSkipVerify bool `toml:"tlsInsecureSkipVerify,omitempty" json:"-"`
```
InsecureSkipVerify added to tlsConfig in sendMail
```
tlsConfig := &tls.Config {
ServerName:         emailConf.SMTPAddr,
InsecureSkipVerify: emailConf.TLSInsecureSkipVerify,
}
```
Fixes #1219 
```console
$ wget https://raw.githubusercontent.com/rnwood/smtp4dev/master/docker-compose.yml
11c11
<       - '25:25'
---
>       - '465:465'
66a67,68
>       - ServerOptions__Port=465
>       - ServerOptions__TlsMode=ImplicitTls
$ docker compose up -d
[cveDict]
type = "sqlite3"
sqlite3Path = "/data/vulsctl/docker/cve.sqlite3"
[ovalDict]
type = "sqlite3"
[gost]
type = "sqlite3"
[exploit]
type = "sqlite3"
[metasploit]
type = "sqlite3"
[kevuln]
type = …
```
> TLS insecure option adding

- GNUmakefile
- detector/javadb/javadb.go
- scanner/library.go
At 0.25.1, there is regression of npm's package-lock.json scan where dev dependencies are included in library list.
This PR fixes it.
Trivy of 0.50 has dev dependencies excluding feature of three types;
1. npm (package-lock.json), the main point of this fix PR
2. yarn, dev deps exclusion is triggered only when package.json is there alongside of yarn.lock, not the case for vuls (as a consequence, yarn lock file scans *include* dev dependencies)
3. maven (pom.xml) only for integration test cases, it has very specific path pattern "**/[src|target]/it/*/pom.xml" 
Realistically, only effect is npm.
Manually.
Results will be added as comments.
> (fix) Exclude dev dependencies from npm's package-lock.json and Fix Java DB download endpoint

- contrib/trivy/parser/v2/parser.go
- contrib/trivy/parser/v2/parser_test.go
I have fixed the broken link to the following trivy docs page.
* https://aquasecurity.github.io/trivy/dev/docs/coverage/os/
* https://aquasecurity.github.io/trivy/dev/docs/coverage/language/
I have run tests related to the edited parts and confirmed that they have passed.
```sh
$ go test -v -run TestParse
=== RUN   TestParse
--- PASS: TestParse (0.00s)
=== RUN   TestParseError
--- PASS: TestParseError (0.00s)
PASS
ok      github.com/future-architect/vuls/contrib/trivy/parser/v2        0.005s
```
> style(log) fix trivy docs link

- models/packages.go
- oval/util.go
- oval/util_test.go
- scanner/base.go
- scanner/redhatbase.go
- scanner/redhatbase_test.go
I think that instead of having a group of enable modules, each package should have a modularitylabel of the module it belongs to.
```console
[vagrant@rhel8 ~]$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.9 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.9 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
[vagrant@rhel8 ~]$ dnf …
```
> feat(scanner/redhat): each package has modularitylabel

- gost/debian.go
- gost/debian_test.go
- models/vulninfos.go
- models/vulninfos_test.go
Fixes #1913 
[docker.json](https://github.com/future-architect/vuls/files/15247171/docker.json)
[gost.sqlite3.zip](https://github.com/future-architect/vuls/files/15247190/gost.sqlite3.zip)
Either `unimportant` or `not yet assigned` is assigned to severity.
```console
$ vuls report --refresh-cve
$ cat results/2024-05-08T12-10-02+0900/docker.json | jq '.scannedCves."CVE-2023-48795".cveContents'
{
"debian_security_tracker": [
{
"type": "debian_security_tracker",
"cveID": "CVE-2023-48795",
"title": "",
"summary": "The SSH transport protocol with certain OpenSSH extensions, found in OpenSSH before 9.6 and other products, allows remote attackers to bypass integrity checks such that some packets are omitted (from the extension negotiation message), and a client and server may consequently end up …
```
> fix(gost/debian): show all severities that appeared

- contrib/trivy/parser/v2/parser_test.go
- contrib/trivy/pkg/converter.go
- detector/library.go
- models/cvecontents.go
- models/vulninfos.go
- tui/tui.go
Fixes #1919 
- config.toml
```toml
[servers.pseudo]
lockfiles = ["integration/data/lockfile/juddiv3-war-3.3.5.war"]
```
```console
$ vuls scan
$ vuls report --refresh-cve
$ cat results/2024-05-16T00-24-28+0900/pseudo.json | jq '.scannedCves."CVE-2022-22965".cveContents[][] | {type,cveID,cvss2Score,cvss2Vector,cvss2Severity,cvss3Score,cvss3Vector,cvss3Severity}'
{
"type": "nvd",
"cveID": "CVE-2022-22965",
"cvss2Score": 7.5,
"cvss2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
"cvss2Severity": "HIGH",
"cvss3Score": 9.8,
"cvss3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
"cvss3Severity": "CRITICAL"
}
{
"type": "nvd",
"cveID": "CVE-2022-22965",
"cvss2Score": 0,
"cvss2Vector": "",
"cvss2Severity": "",
"cvss3Score": 0,
"cvss3Vector": "",
"cvss3Severity": ""
}
{
"type": …
```
> feat(detector, contrib/trivy-to-vuls): collect vendor severity and cvss

- contrib/trivy/parser/v2/parser_test.go
- contrib/trivy/pkg/converter.go
> fix(trivy-to-vuls): remove cvss/severity duplicates, list all severities

- config/awsconf.go
- reporter/s3.go
- subcmds/discover.go
Fixes #1605
```console
$ docker run --rm --name minio -p 9000:9000 -p 9001:9001 quay.io/minio/minio server /data --console-address ":9001"
$ docker exec -it minio bash
bash-5.1# mc config host add local http://localhost:9000 minioadmin minioadmin
bash-5.1# mc mb local/vuls
```
```console
$ docker exec -it minio bash
bash-5.1# mc anonymous set public local/vuls
bash-5.1# mc anonymous get-json local/vuls
{
"Statement": [
{
"Action": [
"s3:GetBucketLocation",
"s3:ListBucket",
"s3:ListBucketMultipartUploads"
],
"Effect": "Allow",
"Principal": {
"AWS": [
"*"
]
},
"Resource": [
"arn:aws:s3:::vuls"
]
},
{
"Action": [
"s3:AbortMultipartUpload",
"s3:DeleteObject",
"s3:GetObject",
"s3:ListMultipartUploadParts",
"s3:PutObject"
],
"Effect": "Allow",
"Principal": {
"AWS": [
"*"
]
},
"Resource": [ …
```
> feat(reporter/s3): support minio

- gost/debian.go
- gost/debian_test.go
- gost/ubuntu.go
- gost/ubuntu_test.go
- gost/util.go
- models/packages.go
- models/packages_test.go
- scanner/debian.go
- scanner/debian_test.go
Fixes #1933 
```console
$ cat Vagrantfile
Vagrant.configure("2") do |config|
config.vm.box = "ubuntu/jammy64"
config.vm.box_version = "20220423.0.0"
#
#
#
config.vm.provision "shell", inline: <<-SHELL
apt-get update
apt-get install -y openssh-server lsof iproute2
DEBIAN_FRONTEND=noninteractive apt-get install -y debian-goodies
DEBIAN_FRONTEND=noninteractive apt-get install --install-suggests -y linux-image-5.15.0-107-generic
SHELL
end
$ vagrant up --provision
$ vagrant ssh
vagrant@ubuntu-jammy:~$ uname -a
Linux ubuntu-jammy 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
vagrant@ubuntu-jammy:~$ dpkg-query -W -f="\${binary:Package},\${db:Status-Abbrev},\${Version},\${source:Package},\${source:Version}\n" | grep linux- …
```
> fix(debian,ubuntu): collect running kernel source package

- .github/workflows/goreleaser.yml
cf.
- https://zenn.dev/pinto0309/scraps/c6413eb15a1b2a (in Japanese)
- https://github.com/actions/runner-images/issues/709
- https://github.com/future-architect/vuls/actions/runs/9432941692/job/25983315399
- actions executed in the debug branch https://github.com/future-architect/vuls/compare/master...shino/debug-release
* …
> fix(ci): Remove unused files to avoid disk full

- reporter/s3.go
- saas/saas.go
Updated to log the correct object name in the saas report log when an error occurs with an s3 upload.
> style(log): saas s3 upload error log

- reporter/s3.go
The method currently used to configure S3 endpoints is deprecated.
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/config#WithEndpointResolverWithOptions
Refer to the following to set up the S3 BaseEndpoint.
https://aws.github.io/aws-sdk-go-v2/docs/configuring-sdk/endpoints/
```console
$ docker run --rm --name minio -p 9000:9000 -p 9001:9001 quay.io/minio/minio server /data --console-address ":9001"
$ docker exec -it minio bash
bash-5.1# mc config host add local http://localhost:9000 minioadmin minioadmin
bash-5.1# mc mb local/vuls
bash-5.1# mc anonymous set public local/vuls
```
```console
[aws]
s3Endpoint = "http://localhost:9000"
region = "us-east-1"
credentialProvider = "anonymous"
s3Bucket = "vuls"
s3UsePathStyle = true
$ vuls report --to-s3
$ docker exec -it minio …
```
> refactor(report/s3): remove deprecated method for s3 endpoint

- config/os.go
- config/os_test.go
cf. https://lists.ubuntu.com/archives/ubuntu-announce/2024-June/000302.html
Fix EOL date of Ubuntu 23.10 according to official announce
Unit test
> fix(config/os): Fix EOL date of ubuntu 23.10

- detector/detector.go
- detector/util.go
- go.mod
- go.sum
- models/cvecontents.go
- models/cvecontents_test.go
- models/utils.go
- models/vulninfos.go
- models/vulninfos_test.go
- reporter/sbom/cyclonedx.go
- reporter/slack.go
- reporter/syslog.go
- reporter/util.go
- server/server.go
- tui/tui.go
A new `mitre` will be added to the go-cve-dictionary data source.
https://github.com/vulsio/go-cve-dictionary/pull/392 
`mitre` includes CVSSv4 and SSVC evaluations by CISA ADP, and this information is added to the detected vulnerabilities.
```console
$ go-cve-dictionary fetch mitre 2024
$ go-cve-dictionary fetch nvd 2024
...
[servers]
[servers.pseudo]
cpeNames = [
"cpe:2.3:a:clashforwindows:clash:0.1.0:*:*:*:*:windows:*:*"
]
$ vuls scan
$ vuls report
$ cat results/2024-06-27T22-16-01+0900/pseudo.json | jq '.scannedCves[].cveContents.mitre'
[
{
"type": "mitre",
"cveID": "CVE-2024-5732",
"title": "Clash Proxy Port improper authentication",
"summary": "A vulnerability was found in Clash up to 0.20.1 on Windows. It has been declared as critical. This …
```
> feat(cve/mitre): support go-cve-dictionary:mitre

- scanner/suse.go
- scanner/suse_test.go
Fixes #1977 
```console
$ git clone https://github.com/MaineK00n/vuls-targets.git
$ cd vuls-targets/suse/leap/15.6
$ vagrant up --provision
// TODO: add known_hosts
[servers.vagrant]
host = "127.0.0.1"
port = "2222"
user = "vagrant"
keyPath = "/home/vuls/vuls-targets/.ssh/id_rsa"
scanMode           = ["fast-root"]
```
```console
$ vuls scan
[Jul  4 14:57:44]  INFO [localhost] vuls-v0.26.0-build-20240704_144346_ac55380
...
[Jul  4 14:57:47]  INFO [localhost] (1/1) vagrant is running on other
[Jul  4 14:57:47]  INFO [vagrant] Scanning OS pkg in fast-root mode
[Jul  4 14:57:48]  WARN [vagrant] err: Failed to scan updatable packages: …
```
> fix(scanner/suse): skip new line in zyper -q lu

- contrib/trivy/parser/v2/parser_test.go
- contrib/trivy/pkg/converter.go
- detector/library.go
trivy-to-vuls support CVSS v4.0
https://github.com/aquasecurity/trivy-db/pull/414
unit test
> feat(contrib/trivy): support CVSS v4.0

- oval/util.go
- oval/util_test.go
Previously, for Oracle's ksplice advisory, we only considered `.ksplice1.`, but sometimes it was `.ksplice2.`. This PR makes the comparison for ksplice advisory more accurate.
```console
$ vuls report
docker (oracle8.10)
===================
Total: 14 (Critical:0 High:6 Medium:7 Low:1 ?:0)
14/14 Fixed, 0 poc, 0 exploits, cisa: 0, uscert: 0, jpcert: 0 alerts
235 installed
+----------------+------+--------+-----+-----------+---------+--------------------------------+
|     CVE-ID     | CVSS | ATTACK | POC |   ALERT   |  FIXED  |            PACKAGES            |
+----------------+------+--------+-----+-----------+---------+--------------------------------+
| …
```
> fix(detect/oracle): handle ksplice advisories

- models/cvecontents.go
As a result of Trivy supporting Azure Linux, ```trivy:azure``` is now included in the cveContentType of vuls detection results. Therefore, add ```trivy:azure``` as a constant in vuls.
- https://github.com/aquasecurity/trivy-db/pull/409
> feat(trivy): add new cveContentType trivy:azure

- oval/util.go
- oval/util_test.go
> feat(oval/suse): skip comparing TDC package and non-TDC package

- .github/workflows/golangci.yml
- config/config_test.go
- config/os_test.go
- contrib/future-vuls/cmd/main.go
- contrib/future-vuls/pkg/discover/discover.go
- contrib/trivy/cmd/main.go
- detector/wordpress.go
- go.mod
- go.sum
- reporter/azureblob.go
- reporter/s3.go
- scanner/alma.go
- scanner/amazon.go
- scanner/centos.go
- scanner/debian_test.go
- scanner/fedora.go
- scanner/library.go
- scanner/oracle.go
- scanner/redhatbase.go
- scanner/redhatbase_test.go
- scanner/rhel.go
- scanner/rocky.go
- scanner/scanner.go
- scanner/suse.go
- subcmds/discover.go
- subcmds/server.go
- update go to 1.23 (latest)
- update golangci-lint to 1.61 (latest, to run on go 1.23)
To workaround the performance issue at launch time, this PR add replace directive of open-policy-agent/opa.
This should be remove in the future, I filed the issue for that https://github.com/future-architect/vuls/issues/2036 .
CI and by hand
> build: update go to 1.23

- detector/detector.go
There was a bug where when a vulnerability was detected on a CPE and that vulnerability had already been detected by another method, the information in DistroAdvisories was overwritten, resulting in the loss of the information from the previous detection.
For example, [JVNDB-2024-000098](https://github.com/vulsio/vuls-data-raw-jvn-feed-rss/blob/5224a56349ff02c7cd4a561b8a05361e43c373d5/2024/JVNDB-2024-000098.json) and [JVNDB-2024-005553](https://github.com/vulsio/vuls-data-raw-jvn-feed-rss/blob/5224a56349ff02c7cd4a561b8a05361e43c373d5/2024/JVNDB-2024-005553.json), both of which are related to CVE-2024-7263.
```console
$ go-cve-dictionary fetch jvn 2024
$ cat …
```
> fix(detector/cpe): do not overwrite distro advisories

- contrib/future-vuls/pkg/cpe/cpe.go
- contrib/snmp2cpe/pkg/util/util.go
- detector/detector.go
- go.mod
- gost/debian.go
- gost/debian_test.go
- gost/microsoft.go
- gost/ubuntu.go
- gost/util.go
- models/cvecontents.go
- models/packages.go
- oval/util.go
- reporter/sbom/cyclonedx.go
- reporter/util.go
- scanner/scanner.go
- scanner/scanner_test.go
- scanner/windows.go
- scanner/windows_test.go
- tui/tui.go
Use slices and maps from the standard library instead of experimental slices and maps.
> refactor: use std slices, maps package

- gost/microsoft.go
- gost/microsoft_test.go
- models/vulninfos.go
- models/vulninfos_test.go
Among the vulnerabilities detected in Windows, particularly in Edge, even those for which the KB or fixed build to fix them is unknown are set with a confidence level of 100, called WindowsUpdateSearch.
Because cases like this are very noisy, we set WindowsRoughMatch, which lowers the reliability to 30.
```console
$ vuls report --refresh-cve
$ cat results/2024-10-04T02-18-44+0900/localhost.json | jq '.scannedCves."CVE-2023-6112" | [.confidences,.affectedPackages]'
[
[
{
"score": 100,
"detectionMethod": "WindowsUpdateSearch"
}
],
[
{
"name": "Microsoft Edge",
"fixState": "unknown"
}
]
]
```
```console
$ vuls report --refresh-cve
$ cat …
```
> feat(detector/microsoft): set WindowsRoughMatch if KB or Version to be fixed is unknown

- contrib/snmp2cpe/pkg/cmd/v1/v1.go
- contrib/snmp2cpe/pkg/cmd/v2c/v2c.go
- contrib/snmp2cpe/pkg/cmd/v3/v3.go
- contrib/snmp2cpe/pkg/snmp/snmp.go
add --port/-P option to snmp2cpe command
```console
$ git clone https://github.com/MaineK00n/vuls-targets.git
$ docker build -t vuls-target:snmp -f vuls-targets/snmp/Dockerfile .
$ docker run --rm -itd -p 1611:161/udp --name vuls-target vuls-target:snmp
$ make build-snmp2cpe
$ snmp2cpe v2c --port 1611 127.0.0.1 juniper-mx960-13-3r9-13 | snmp2cpe convert
{"127.0.0.1":["cpe:2.3:h:juniper:mx960:-:*:*:*:*:*:*:*","cpe:2.3:o:juniper:junos:13.3r9.13:*:*:*:*:*:*:*"]}
```
> feat(contrib/snmp2cpe): add --port/-P option

- oval/util.go
- oval/util_test.go
like the ksplice and TDC in SUSE, we need not to report fips patched versions for non fips packages
by unit test
> feat(oval/oracle): ignore fips patched version for non fips package versions

- scanner/base.go
The format of `uname -a` differs for each major version as shown below.
To reliably obtain the kernel version, set the version of the `linux-image-(kernel release)` package as the kernel version.
```console
$ cat /etc/debian_version
6.0.10
$ uname -a
Linux debian-6 2.6.32-5-amd64 #1 SMP Tue May 13 16:34:35 UTC 2014 x86_64 GNU/Linux
$ dpkg-query -W -f='${Version}' linux-image-$(uname -r)
2.6.32-48squeeze6
```
```console
$ cat /etc/debian_version
7.9
$ uname -a
Linux debian-7 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64 GNU/Linux
$ dpkg-query -W -f='${Version}' linux-image-$(uname -r)
3.2.68-1+deb7u3
```
```console
$ cat /etc/debian_version
8.11
$ uname -a
Linux jessie 3.16.0-9-amd64 #1 SMP Debian …
```
> fix(scanner/debian): fill kernel version from kernel package

- scanner/scanner.go
There are cases where ssh succeeds but ssh-keyscan fails, as shown below.
What vuls actually needs is for ssh to be successful, and ssh-keyscan is merely a hint to find the cause when ssh fails.
Therefore, if ssh-keyscan and ssh-keygen fail to execute, vuls will not fail to execute, but rather it will assume that SSH configuration validation has failed, and that SSH will be possible as is, and vuls will continue to execute.
```console
PS C:\Users\shino\vagrant-vms\debian12> ssh vagrant@172.23.181.106 -i .\.vagrant\machines\default\hyperv\private_key
Last login: Tue Nov 12 01:59:54 2024 from 172.23.176.1
vagrant@debian12:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux" …
```
> feat(scanner): skip SSH configuration validation when ssh-key(scan|gen) failed

- oval/util.go
- scanner/redhatbase.go
- scanner/redhatbase_test.go
- scanner/scanner_test.go
- scanner/suse.go
collect source package from rpm package manager
[results.zip](https://github.com/user-attachments/files/18045501/results.zip)
```console
$ vuls report --format-one-line-text 2024-12-07T09-18-39+0900
[Dec  7 09:53:17]  INFO [localhost] vuls-v0.27.0-build-20241206_201629_1ab4c79
...
One Line Summary
vagrant	Total: 1994 (Critical:19 High:955 Medium:982 Low:37 ?:1)	1309/1994 Fixed	547 installed	0 poc	0 exploits	0 kevs	uscert: 0, jpcert: 0 alerts
```
```console
$ vuls report --format-one-line-text 2024-12-07T09-22-52+0900
[Dec  7 09:53:04]  INFO [localhost] vuls-v0.27.0-build-20241207_091638_97dc992
...
One Line Summary
vagrant	Total: 1994 (Critical:19 High:955 Medium:982 Low:37 ?:1)	1309/1994 Fixed	547 installed	0 poc	0 exploits	0 kevs	uscert: 0, jpcert: 0 …
```
> feat!(scanner/rpm): change queryformat (add sourcerpm)

- detector/vuls2/db.go
- detector/vuls2/db_test.go
- detector/vuls2/vuls2.go
- go.mod
- go.sum
> chore(detector/vuls2): check downloaded time before updating db

- detector/vuls2/vendor.go
- models/cvecontents.go
- models/vulninfos.go
add cve content type Alma, Rocky
vuls report ...
```json
"CVE-2024-43854": {
"cveID": "CVE-2024-43854",
"confidences": [
{
"score": 100,
"detectionMethod": "OvalMatch"
}
],
"affectedPackages": [
{
"name": "kernel",
"fixedIn": "0:5.14.0-427.42.1.el9_4"
}
],
"distroAdvisories": [
{
"advisoryID": "ALSA-2024:8617",
"severity": "moderate",
"issued": "2024-10-30T00:00:00Z",
"updated": "2024-11-03T19:17:17Z",
"description": "The kernel packages contain the Linux kernel, the core of any Linux operating system.  \n\nSecurity Fix(es):  \n\n  * hw: cpu: intel: Native Branch History Injection (BHI) (CVE-2024-2201)\n  * kernel: tcp: add sanity checks to rx zerocopy (CVE-2024-26640)\n  * kernel: mptcp: fix data re-injection from stale subflow (CVE-2024-26826)\n  * kernel: af_unix: Fix garbage collector …
```
> fix(models/cvecontents): use cve content type Alma, Rocky

- gost/ubuntu.go
- gost/ubuntu_test.go
With this PR(https://github.com/vulsio/gost/pull/185), patch information for fixes in ESM will now be returned in addition to the main release.
This can result in a situation where an issue is not fixed in the main release, but a fix is ​​released in the ESM.
For example, in the case of `focal` and `esm-apps/focal`, as shown below.
https://github.com/vulsio/vuls-data-raw-ubuntu-cve-tracker/blob/d0b60209acf5d91d3a7ca49c85550ee907bd8717/2020/CVE-2020-22039.json
Also, even if you make a fix in the ESM, it may remain needed in the main release and be judged as unfixed.
This PR fixes these bugs.
```json
"family": "ubuntu",
"release": "20.04",
"packages": {
"ffmpeg": {
"name": "ffmpeg",
"version": "7:4.2.7-0ubuntu0.1",
"release": "",
"newVersion": "",
"newRelease": "",
"arch": "",
"repository": …
```
> fix(detector/gost/ubuntu): detection logic when esm etc. are mixed

- scanner/redhatbase.go
- scanner/redhatbase_test.go
Before this PR, some rpms with not-very-good source file name format let vuls scan failed with errors like:
```
[Dec 18 18:11:36] ERROR [localhost] Error on vt-alma8, err: [Failed to scan installed packages:
github.com/future-architect/vuls/scanner.(*redhatBase).scanPackages
/home/runner/work/vuls/vuls/scanner/redhatbase.go:421
- Failed to parse installed packages. err:
github.com/future-architect/vuls/scanner.(*redhatBase).scanInstalledPackages
/home/runner/work/vuls/vuls/scanner/redhatbase.go:499
- Failed to parse sourcepkg. err:
github.com/future-architect/vuls/scanner.(*redhatBase).parseIns …
```
> fix(scanner/redhatbase): don't return error when parse failure of source file

- scanner/suse.go
- scanner/suse_test.go
The current method of skipping table headers in the output of `zypper -q lu` does not work when spaces are added. 
So, until we read a line consisting only of `-+`, we assume it is a table header.
```console
a2c6f9dcb28a:~ # zypper -q lu
S  | Repository                                                   | Name     | Current Version | Available Version | Arch
---+--------------------------------------------------------------+----------+-----------------+-------------------+-------
v  | Update repository with updates from SUSE Linux Enterprise 15 | iproute2 | 5.14-150400.1.8 | 6.4-150600.7.3.1  | x86_64
```
```console
$ vuls scan -debug
...
[Dec 18 20:36:05] DEBUG …
```
> fix(scanner/suse): skip table header in zypper -q lu

- scanner/redhatbase.go
- scanner/redhatbase_test.go
In rpm -qa, release may be empty.
When release is empty, there will be two spaces, which are rpm-qa separators.
In this case, `strings.Split` and `strings.Fields` behave differently.
Please refer to the following example.
https://go.dev/play/p/nc-MA6sPz4D
Since we expect the length to be constant (= we know which elements are empty), we should use `strings.Split`.
Also, regarding `splitFileName`, if the name part has `-`, the existing implementation passes it even if the filename is invalid.
So, although it is not standard rpm style, I would like to change it to accept the pattern `...<release>-<arch>`.
unit test
> fix(scanner/redhatbase): support for empty release in rpm -qa

- reporter/http.go
Fixes #2105 
In the current implementation, the response body is not completely read, which can result in the connection being cut off while the Response Writer is still writing. This PR will fix this so that the entire response body is read.
```console
...
[http]
url = "http://localhost:5515/vuls"
...
$ vuls server -listen localhost:5515
$ vuls report -to-http
```
```console
$ vuls server -listen localhost:5515
...
[Jan 17 10:45:50]  INFO [localhost] vagrant: 0 CVEs are detected with OVAL
[Jan 17 10:45:50]  INFO [localhost] vagrant: 0 unfixed CVEs are detected with gost
[Jan 17 10:45:50]  INFO [localhost] Fill CVE detailed with gost
[Jan 17 10:45:50]  INFO [localhost] Fill CVE detailed with …
```
> fix(reporter/http): read response body

- subcmds/discover.go
add vuls2 section to the generated config.toml
```console
$ vuls discover 127.0.0.1/32
[Jan 24 13:21:11]  INFO [localhost] vuls-v0.28.1-build-20250117_125034_0ec945d
[cveDict]
#type = ["sqlite3", "mysql", "postgres", "redis", "http" ]
#sqlite3Path = "/path/to/cve.sqlite3"
#url        = ""
[ovalDict]
#type = ["sqlite3", "mysql", "postgres", "redis", "http" ]
#sqlite3Path = "/path/to/oval.sqlite3"
#url        = ""
[gost]
#type = ["sqlite3", "mysql", "postgres", "redis", "http" ]
#sqlite3Path = "/path/to/gost.sqlite3"
#url        = ""
[exploit]
#type = ["sqlite3", "mysql", "postgres", "redis", "http" ]
#sqlite3Path = "/path/to/go-exploitdb.sqlite3"
#url        = ""
[metasploit]
#type = ["sqlite3", "mysql", "postgres", "redis", "http" ]
#sqlite3Path = "/path/to/go-msfdb.sqlite3"
#url        = …
```
> fix(cmd/discover): add vuls2 section to the generated config.toml

- models/cvecontents.go
Add some fields to sort logic.
Before this PR, "make diff" produces supurious diffs even if vuls.old and vuls.new are the same binary, such as:
```
diff -c /home/shino/g/vuls/integration/results/2025-02-04T15-50-09+0900/bundler.json /home/shino/g/vuls/integration/results/2025-02-04T15-50-10+0900/bundler.json
*** /home/shino/g/vuls/integration/results/2025-02-04T15-50-09+0900/bundler.json        Tue Feb  4 15:50:34 2025
--- /home/shino/g/vuls/integration/results/2025-02-04T15-50-10+0900/bundler.json        Tue Feb  4 15:50:34 2025
***************
*** 106600,106606 ****
"cvss2Vector": "",
"cvss2Severity": "",
"cvss3Score": 6.1,
!                         "cvss3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
"cvss3Severity": "MEDIUM",
"cvss40Score": 0,
"cvss40Vector": "",
--- …
```
> fix(models/cvecontents): a little more accurate sort

- scanner/redhatbase.go
fedora 40
```console
$ sh-5.2# repoquery --version
4.21.1
Installed: dnf-0:4.21.1-1.fc40.noarch at Thu Oct 31 05:48:20 2024
Built    : Fedora Project at Fri Aug 16 14:34:26 2024
Installed: rpm-0:4.19.1.1-1.fc40.x86_64 at Thu Oct 31 05:48:20 2024
Built    : Fedora Project at Wed Feb  7 15:55:53 2024
```
fedora 41
```console
sh-5.2# repoquery --version
4.23.0
Installed: rpm-0:4.20.1-1.fc41.x86_64 at Tue Mar 25 05:07:30 2025
Built    : Fedora Project at Tue Mar 11 09:18:03 2025
```
Since the output of `repoquery --version` in Fedora 41 does not include `dnf`, the repoquery command for dnf is not selected. Therefore, a warning is generated.
https://github.com/future-architect/vuls/blob/6aa3811800e500e83bf2b89f7daee …
> fix(scanner/redhatbase): fix cmd in scanUpdatablePackages

- .github/workflows/build.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker-publish.yml
- .github/workflows/golangci.yml
- .github/workflows/goreleaser.yml
- .github/workflows/test.yml
This pull request includes changes to multiple GitHub Actions workflow files to add permissions settings. These changes ensure that the workflows have the appropriate read or write permissions for the contents they interact with.
Changes to GitHub Actions workflows:
* [`.github/workflows/build.yml`](diffhunk://#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R6-R7): Added `contents: read` permissions.
* [`.github/workflows/codeql-analysis.yml`](diffhunk://#diff-63bd641104d10e25f141d518a16b22a151d125e12701df2f9e79734b23b90188R23-R24): Added `contents: read` permissions.
* [`.github/workflows/docker-publish.yml`](diffhunk://#diff-5b21991be47c2922383bdc0b6bf00b65af7db51b82d049dd8d6ad03e3d37ac98R10-R11): Added `contents: read` permissions.
* …
> chore(actions): Adjust GitHub Actions permissions (write for release, read-only for others)

- .github/workflows/codeql-analysis.yml
fix: https://github.com/future-architect/vuls/actions/runs/14102397791/job/39501261403
for details, see
https://github.com/github/codeql-action?tab=readme-ov-file#workflow-permissions
```
Workflow Permissions
All advanced setup code scanning workflows must have the security-events: write permission. Workflows in private repositories must additionally have the contents: read permission. For more information, see "[Assigning permissions to jobs](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs)."
```
> fix(actions): Add security-events write permission to CodeQL results upload

- reporter/sbom/cyclonedx.go
- reporter/sbom/purl.go
We made the following improvements to how OS packages are handled during SBOM generation:
- Fixed: Prevented empty `properties` from resulting in `null` values in CycloneDX `components` generated from OS packages.
- Refactored `osPkgToPURL`: Simplified the function signature by replacing multiple string parameters with a single `models.Package` struct to improve readability and reduce the risk of argument mismatch.
```
or 
```
```json
{
"$schema": "http://cyclonedx.org/schema/bom-1.6.schema.json",
"bomFormat": "CycloneDX",
"specVersion": "1.6",
...
"components": [
{
"bom-ref": "pkg:rpm/amazon/openssl@1.0.2k-24.amzn2.0.2?arch=x86_64\u0026distro=2+%28Karoo%29",
"type": "library",
"name": …
```
> fix(report): skip empty properties in OS package SBOM components

- reporter/sbom/cyclonedx.go
This pull request updates the CycloneDX SBOM generation logic to omit the `cwes` and `ratings` fields within each `vulnerability` object when they are empty, instead of including them as `null`.
```
or 
```
```json
{
"$schema": "http://cyclonedx.org/schema/bom-1.6.schema.json",
...
"vulnerabilities": [
{
"id": "CVE-2024-9370",
"ratings": null,
"cwes": null,
...
},
...
]
}
```
```json
{
"$schema": "http://cyclonedx.org/schema/bom-1.6.schema.json",
...
"vulnerabilities": [
{
"id": "CVE-2024-9370",
...
},
...
]
}
```
> fix(report): omit empty CWE and rating fields in CycloneDX SBOM

- saas/saas.go
- subcmds/saas.go
Added timeout option to the vuls-saas command.
```
C:\Program Files\vuls-saas>vuls.exe saas -h
saas:
saas
[-config=/path/to/config.toml]
[-results-dir=/path/to/results]
[-log-to-file]
[-log-dir=/path/to/log]
[-http-proxy=http://192.168.0.1:8080]
[-timeout=10]
[-debug]
[-quiet]
-config string
/path/to/toml (default "C:\\Program Files\\vuls-saas\\config.toml")
-debug
debug mode
-http-proxy string
http://proxy-url:port (default: empty)
-log-dir string
/path/to/log (default "C:\\Users\\ome-202304wada\\AppData\\Roaming\\vuls")
-log-to-file
Output log to file
-quiet
Quiet mode. No output on stdout …
```
> fix(cmd/saas): add timeout option

- config/vulnDictConf.go
- detector/cti.go
- detector/cve_client.go
- detector/exploitdb.go
- detector/kevuln.go
- detector/msf.go
- gost/microsoft.go
- gost/util.go
- oval/oval.go
- oval/util.go
- subcmds/discover.go
It is now possible to set the timeout for the entire request for each DB and for a single request.
Fixes #1695 
```console
$ vuls report --refresh-cve
[Apr 30 09:42:22]  INFO [localhost] vuls-0.30.0-358cbf59b8480330cebed319dee1bfc4c5704c7e-2025-03-18T06:42:29Z
...
[Apr 30 09:42:22]  INFO [localhost] Skip OVAL and Scan with gost alone.
[Apr 30 09:42:22]  INFO [localhost] localhost: 0 CVEs are detected with OVAL
[Apr 30 09:42:33]  WARN [localhost] Failed to HTTP GET. retrying in 349.858873ms seconds. err: HTTP GET error, url: http://127.0.0.1:1325/ubuntu/2204/pkgs/thunderbird/fixed-cves, resp: <nil>, err: [Get "http://127.0.0.1:1325/ubuntu/2204/pkgs/thunderbird/fixed-cves": read tcp …
```
> feat!(detector): timeout can be set, default is no timeout

- detector/vuls2/vuls2.go
When cvss3.1 was provided, the check was incorrect and it was always not set.
This PR fixes this.
```console
$ curl -s --create-dirs --output results/2025-05-04T13-30-00+0900/rhel_90.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/results/rhel_90.json
```
```console
$ vuls report --refresh-cve 2025-05-04T13-30-00+0900
$ jq -r '.scannedCves."CVE-2007-4559".cveContents' results/2025-05-04T13-30-00+0900/rhel_90.json
{
"redhat": [
{
"type": "redhat",
"cveID": "CVE-2007-4559",
"title": "python: tarfile module directory traversal",
"summary": "A flaw was found in the Python tarfile module. Extracting a crafted TAR archive with the tarfile.extract or tarfile.extractall functions could …
```
> fix(detector/vuls2): fix cvss v3.1 vector check

- detector/vuls2/vuls2.go
- go.mod
- go.sum
Fixes #2196 
```console
$ rm vuls.db
...
[vuls2]
Repository = "ghcr.io/vulsio/vuls-nightly-db@sha256:788456a519e7f205eb0395410f296535927c8510948937badd190bff3c2156d7"
...
$ curl -sL --create-dirs --output results/2025-05-03T09-00-00+0900/redhat.json https://github.com/user-attachments/files/20011464/redhat.json
```
```console
$ /usr/bin/time -v ./vuls report --refresh-cve 2025-05-03T09-00-00+0900 > /dev/null
[May  3 08:57:51]  INFO [localhost] vuls-0.30.0-358cbf59b8480330cebed319dee1bfc4c5704c7e-2025-03-18T06:42:29Z
...
[May  3 08:57:51]  INFO [localhost] Loaded: /home/vuls/results/2025-05-03T09-00-00+0900
[May  3 08:57:59]  INFO [localhost] : 1155 CVEs are detected with vuls2
[May  3 08:57:59]  INFO [localhost] : 0 unfixed CVEs are detected with gost
[May  3 08:57:59] …
```
> chore(deps): bump github.com/MaineK00n/vuls2

- contrib/future-vuls/pkg/discover/discover.go
- subcmds/discover.go
fix vuls discover on windows
- cmd.exe
```console
vagrant@WIN-NI76NHOHQTA C:\Users\vagrant>ping -c1 127.0.0.2
Bad value for option -c1.
vagrant@WIN-NI76NHOHQTA C:\Users\vagrant>ping -n 1 127.0.0.2 
Pinging 127.0.0.2 with 32 bytes of data:
Reply from 127.0.0.2: bytes=32 time<1ms TTL=128
Ping statistics for 127.0.0.2:
Packets: Sent = 1, Received = 1, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
Minimum = 0ms, Maximum = 0ms, Average = 0ms
```
- powershell
```powershell
PS C:\Users\vagrant> ping -c1 127.0.0.2 
Bad value for option -c1.
PS C:\Users\vagrant> ping -n 1 127.0.0.2
Pinging 127.0.0.2 with 32 bytes of data:
Reply from 127.0.0.2: bytes=32 time<1ms TTL=128
Ping statistics for …
```
> fix(cmd/discover): fix ping options for windows

- scanner/base.go
- scanner/pseudo.go
- scanner/utils/filepath/unix/unix.go
- scanner/utils/filepath/windows/windows.go
- scanner/windows.go
Fixes #2207 #2208 #2209 
```console
$ curl -sL --create-dirs --output Downloads/package-lock.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/lockfile/npm-v3/package-lock.json
```
```console
version = "v2"
[default]
[servers]
[servers.lockfile]
scanModules        = ["lockfile"]
lockfiles = ["/home/vagrant/Downloads/package-lock.json"]
EOS
$ ./vuls scan
[May 18 21:12:59]  INFO [localhost] vuls-v0.32.0-build-20250519_061016_916f9da
[May 18 21:12:59]  INFO [localhost] Start scanning
[May 18 21:12:59]  INFO [localhost] config: /home/vagrant/config.toml
[May 18 …
```
> fix(scanner): scan lockfiles

- detector/vuls2/db.go
- detector/vuls2/db_test.go
should download db when the schema versions are different
by unit test
> feat(detector/vuls2): should download db when the schema versions are different

- detector/vuls2/db.go
get metadata after opening db
```console
$ curl -s --create-dirs --output results/2025-05-22T00-00-00+0900/rhel_90.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/results/rhel_90.json
```
```console
$ vuls report --refresh-cve 2025-05-22T00-00-00+0900
[May 22 02:30:50]  INFO [localhost] vuls-v0.32.0-build-20250522_022918_e52fa8d
[May 22 02:30:50]  INFO [localhost] Validating config...
[May 22 02:30:50]  INFO [localhost] cveDict.type=sqlite3, cveDict.url=, cveDict.SQLite3Path=/home/vuls/cve.sqlite3
[May 22 02:30:50]  INFO [localhost] ovalDict.type=sqlite3, ovalDict.url=, ovalDict.SQLite3Path=/home/vuls/oval.sqlite3
[May 22 02:30:50]  INFO [localhost] gost.type=sqlite3, gost.url=, gost.SQLite3Path=/home/vuls/gost.sqlite3
[May 22 02:30:50]  INFO [localhost] …
```
> fix(detector/vuls2): get metadata after opening db

- scanner/redhatbase.go
- scanner/redhatbase_test.go
Fixes #2217 
```console
$ vuls scan
...
Scan Summary
docker	amazon2023.7.20250512	165 installed, 4 updatable
To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```
> refactor(scanner/redhatbase): strictly parse updatable package line

- scanner/windows.go
Fixes #2231 
```console
version = "v2"
[default]
[servers]
[server.windows]
host = "127.0.0.1"
port = "2222"
user = "vagrant"
keyPath = "/home/vuls/vuls-targets-docker/.ssh/id_rsa"
EOS
```
```console
$ vuls scan -debug 2>&1 | grep -A 2 "osInfo(Registry):"
(empty)
```
```console
$ vuls scan -debug 2>&1 | grep -A 2 "osInfo(Registry):"
time="Jun  9 12:12:05" level=debug msg="osInfo(Registry): {productName:Windows Server 2022 Standard Evaluation version:10.0 build:20348 revision:2159 edition:ServerStandardEval servicePack: arch:x64-based installationType:Server}" 
time="Jun  9 12:12:05" level=debug msg="Windows. Host: …
```
> fix(scanner/windows): print debug log in detect

- reporter/util.go
add row separator for --format-list
```console
$ vuls report
[Jun 13 08:10:19]  INFO [localhost] vuls-0.32.0-6accfb855ea1523c5a70b79c30c5430fd3b7a1a5-2025-05-16T07:24:16Z
...
rhel_90 (redhat9.0)
===================
Total: 3715 (Critical:4 High:524 Medium:3058 Low:116 ?:13)
1983/3715 Fixed, 0 poc, 0 exploits, 0 kevs, uscert: 0, jpcert: 0 alerts
496 installed
+------------------+------+--------+-----+-----+-----------+---------+-------------------------------------+
|      CVE-ID      | CVSS | ATTACK | POC | KEV |   ALERT   |  FIXED  |              PACKAGES               |
+------------------+------+--------+-----+-----+-----------+---------+-------------------------------------+
| CVE-2022-32207   |  9.8 | …
```
> feat(reporter): add row separator for --format-list

- detector/vuls2/vuls2.go
- detector/vuls2/vuls2_test.go
Fixes #2246 
```console
$ curl -s --create-dirs --output results/2025-06-19T05-00-00+0900/rhel_90.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/results/rhel_90.json
version = "v2"
[cveDict]
type = "sqlite3"
[ovalDict]
type = "sqlite3"
[gost]
type = "sqlite3"
[exploit]
type = "sqlite3"
[metasploit]
type = "sqlite3"
[kevuln]
type = "sqlite3"
[cti]
type = "sqlite3"
[vuls2]
repository = "ghcr.io/vulsio/vuls-nightly-db@sha256:788456a519e7f205eb0395410f296535927c8510948937badd190bff3c2156d7"
[default]
[servers]
EOS
$ vuls -v
vuls-v0.32.0-build-20250619_063336_6179618
$ rm vuls.db
$ for i in $(seq 10); do    vuls report --refresh-cve 2025-06-19T05-00-00+0900 …
```
> fix(detector/vuls2): filter VulnerabilityData by Root ID

- subcmds/saas.go
- WHY
- In the previous implementation, the results directory was not deleted when an upload failed. This could cause stale files from the failed run to be included in subsequent processes, potentially leading to inaccurate results.
- WHAT
- Updated the logic to purge the results directory after each upload attempt, regardless of whether the upload succeeds or fails.
```
./vuls -v
vuls v0.29.0 build-4e3ee6a
```
```
ls
2025-06-19T11-36-43+0900  2025-06-20T14-58-57+0900
```
```
./vuls saas
[Jun 20 15:06:29]  INFO [localhost] vuls-v0.29.0-build-4e3ee6a
[Jun 20 15:06:29]  INFO [localhost] Validating config...
[Jun 20 15:06:29]  INFO [localhost] Loaded: /XXX/XXXX/results/2025-06-20T14-58-57+0900
[Jun 20 15:06:35] …
```
> fix(subcmds/saas): remove timestamped directory in results-dir 

- contrib/trivy/parser/v2/parser.go
- contrib/trivy/parser/v2/parser_test.go
This pull request includes changes to the `parser.go` file in the `contrib/trivy/parser/v2` package. The updates primarily focus on simplifying code and improving type usage for better readability and consistency.
* Removed the `fmt.Sprintf` call in the `setScanResultMeta` function, directly assigning `imageName` to `scanResult.ServerName` for improved clarity and reduced overhead.
* Replaced `map[string]interface{}` with `map[string]any` in the `setScanResultMeta` function to use the modern type alias introduced in Go 1.18, enhancing code readability and consistency.
* Removed the unused `fmt` import from the file, reducing unnecessary dependencies.
> feat!(contrib/trivy): delete image tag from server name when scanning by trivy

- .github/dependabot.yml
Publish Docker image action failed:
https://github.com/future-architect/vuls/actions/runs/16016441115/job/45183876489
Dockerfile at the root directory was updated in https://github.com/future-architect/vuls/pull/2235/files but contrib/Dockerfile was not.
This PR adds contrib/ to dependabot's settings for both to be updated.
`directories` setting item is described here: 
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference?learn=dependency_version_updates&learnProduct=code-security#directories-or-directory--
Waiting dep-bot work 🤞 
> fix(ci): add contrib to dependabot's docker settings

- scanner/windows.go
- scanner/windows_test.go
During scanning an 32-bit windows machine, "Failed to detect os name." error occured. By investigation, it is found that formatArch function is called twice during scanning. When first time it is called, it converts the os arch string to "32-bit" , but when it is called second time, with input string 32-bit, it returns "unknown architecture" as there is no switch case to handle "32-bit" case. formatArch function is updated to match proper "x86" or "32-bit" switch case and make the scan to progress and successful.
time="Jul 17 10:34:40" level=info msg="Detecting OS of servers... "
time="Jul 17 10:34:52" level=error msg="(1/1) Failed: 127.0.0.1, err: [Failed to detect os name. err:\n github.com/future-architect/vuls/scanner.detectWindows\n …
> fix(scanner/windows): do not format arch in parseRegistry

- go.mod
- go.sum
To fix https://github.com/future-architect/vuls/security/dependabot/212 , force v1.7.9 of go-getter.
The dependency chain is:
```
% go mod why -m github.com/hashicorp/go-getter
github.com/future-architect/vuls/detector/javadb
github.com/aquasecurity/trivy/pkg/oci
github.com/aquasecurity/trivy/pkg/downloader
github.com/hashicorp/go-getter
```
Once Trivy incorporate the change, we can remove replace line of go.mod.
The library is used in downloading javadb.
Confirmed by scanning `war` server and reporting the result:
```
% ./vuls scan war
[Aug 19 15:53:18]  INFO [localhost] vuls-v0.33.2-build-20250819_155100_9fdd1d0
[Aug 19 15:53:18]  INFO [localhost] Start scanning …
```
> chore(deps): Force go-getter v1.7.9 to fix CVE-2025-8959

- scanner/base.go
- scanner/scanner.go
- scanner/trivy/jar/parse.go
Previously, files were saved under `/tmp/analyzer-fs-*/file-*`, and since Cleanup removed `/tmp/analyzer-fs-*`, the cleanup process completed successfully.
However, due to the following commit, `analyzer-composite-*` and `analyzer-file-*` are now placed separately under `/tmp/trivy-*`. Since composite.Cleanup only deletes `analyzer-composite-*`, the `analyzer-file-*` directories remain after each scan.
https://github.com/aquasecurity/trivy/commit/8f5b56005a4e8752976524750089dc9ea2c91e40
Therefore, in this PR, I update the Cleanup process to remove `/tmp/trivy-*`.
```console
$ curl -sL --output log4j-core-2.13.0.jar https://github.com/vulsio/integration/raw/refs/heads/main/data/lockfile/log4j-core-2.13.0.jar
$ …
```
> fix(scanner/lockfile): remove /tmp/trivy-* directory

- scanner/windows.go
Fixes #2305 
```powershell
PS C:\Users\vagrant> curl.exe -sL --create-dirs --output Downloads\log4j-core-2.13.0.jar https://github.com/vulsio/integration/raw/refs/heads/main/data/lockfile/log4j-core-2.13.0.jar
PS C:\Users\vagrant> curl.exe -sL --create-dirs --output Downloads/package-lock.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/lockfile/npm-v3/package-lock.json
```
```powershell
PS C:\Users\vagrant> @"
version = "v2"
[default]
[servers]
[servers.lockfile]
port = "local"
scanModules        = ["lockfile"]
lockfiles = [
"C:\\Users\\vagrant\\Downloads\\package-lock.json",
"C:\\Users\\vagrant\\Downloads\\log4j-core-2.13.0.jar"
] …
```
> fix(scanner/lockfile): fix binary lockfile scan on windows

- .github/dependabot.yml
Add cooldown periods to dependabot settings.
- Two weeks for Github actions' SHA pins and docker images
- Three days for go modules
I want to discuss about these numbers.
cf.
- https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#cooldown-
- https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates#setting-up-a-cooldown-period-for-dependency-updates
N/A
> chore(deps): add cooldown periods

- config/config.go
- detector/javadb/javadb.go
- detector/library.go
- subcmds/report.go
- subcmds/report_windows.go
- subcmds/tui.go
Fixes #2325 
Trivy DB/JavaDB imports the "github.com/aquasecurity/trivy/pkg/log" package.
https://github.com/aquasecurity/trivy/blob/b7947b37ee47ea79dff550462c297164eb47aa9e/pkg/db/db.go#L18
https://github.com/aquasecurity/trivy/blob/b7947b37ee47ea79dff550462c297164eb47aa9e/pkg/javadb/client.go#L20
The "github.com/aquasecurity/trivy/pkg/log" package replaces the default logger with slog.
https://github.com/aquasecurity/trivy/blob/b7947b37ee47ea79dff550462c297164eb47aa9e/pkg/log/deferred.go#L9-L12
When importing packages related to Trivy DB/JavaDB from the "github.com/future-architect/vuls/config" package, it appears to affect the log output in the snmp2cpe package, which also imports the same …
> chore(config): move trivy db default value ​​to detector

- detector/vuls2/export_test.go
- detector/vuls2/vendor.go
- detector/vuls2/vuls2.go
- detector/vuls2/vuls2_test.go
Before this PR was merged, there was a bug in fast-root scan where the binary package version would be left empty when filling in NeedRestartProcs information.
The data source used in vuls2 does not use the binary package version, so for the time being we have filled the version with "0".
https://github.com/future-architect/vuls/pull/2329
```console
version = "v2"
[servers]
[servers.vagrant]
host = "127.0.0.1"
port = "2222"
user = "vagrant"
keyPath = "/home/vuls/.ssh/id_rsa"
scanMode           = ["fast-root", "offline"]
EOS
$ vuls scan
[Sep 29 13:47:34]  INFO [localhost] vuls-0.35.0-5d61693fa12d91fbe9a0d0b08b4ba51236b57e47-2025-09-25T06:11:08Z
...
Scan …
```
> fix(detector/vuls2): temporarily fill in the version

- .github/workflows/golangci.yml
- .golangci.yml
CI lint failed at https://github.com/future-architect/vuls/actions/runs/18150169777/job/51659320388
with golangci-lint 2.1.6 .
I could not reproduce this error.
Update the binary to latest, then the different error came in:
```
% golangci-lint run
util/util_test.go:1:9: var-naming: avoid meaningless package names (revive)
package util
^
1 issues:
* revive: 1
```
Add skip configuration in the same way as https://github.com/vulsio/go-cpe-dictionary/pull/242/files .
by CI https://github.com/future-architect/vuls/actions/runs/18151878378/job/51664211446?pr=2332
> chore(ci/lint): update golangci-lint to v2.5.0 and adjust config
